import { createHash } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import type { StateStore } from "../../persistence/src/index.js";
import type { ProjectOperations } from "../../project-ops/src/index.js";
import type { CompanyOperations } from "../../company-ops/src/index.js";

export type WorkflowStatus="draft"|"validated"|"published";
export interface WorkflowStep{id:string;roleTemplateId:string;dependsOn:string[];completionCriteria:string[];tools:string[]}
export interface WorkflowRecord{id:string;logicalId:string;version:number;parentVersionId:string|null;companyId:string;name:string;status:WorkflowStatus;steps:WorkflowStep[];requiredReviews:string[];requiredApprovals:string[];budgetLimit:number;contentHash:string;provenance:unknown;createdAt:string;publishedAt:string|null}
export interface PluginRecord{id:string;logicalId:string;version:number;type:"role"|"tool";companyId:string;manifest:Record<string,unknown>;manifestHash:string;signature:Record<string,unknown>;status:"registered"|"disabled";createdAt:string}
export interface ExternalAdapterRecord{id:string;companyId:string|null;contractVersion:string;status:"ready"|"open"|"disabled";failures:number;openedUntil:string|null;metadata:unknown}
const now=()=>new Date().toISOString(),json=(x:unknown)=>JSON.stringify(x??null),parse=<T>(x:unknown)=>JSON.parse(String(x)) as T;
const stable=(x:unknown):string=>Array.isArray(x)?`[${x.map(stable).join(",")}]`:x&&typeof x==="object"?`{${Object.entries(x as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(",")}}`:JSON.stringify(x);
export const contentHash=(x:unknown)=>createHash("sha256").update(stable(x)).digest("hex");
const uniq=(x:string[])=>[...new Set(x)].sort();

const INDUSTRIES={
 software:{version:1,departments:["Product","Engineering","Quality"],roles:["planner","developer","reviewer"],workflow:["plan","build","review"]},
 "public-sector":{version:1,departments:["Planning","Delivery","Audit"],roles:["requirements","implementer","compliance-reviewer"],workflow:["requirements","delivery","audit"]},
 data:{version:1,departments:["Data Platform","Analytics","Data Quality"],roles:["data-engineer","analyst","quality-reviewer"],workflow:["ingest","analyze","validate"]}
} as const;

export class PlatformOperations{
 constructor(private readonly db:DatabaseSync,private readonly state:StateStore,private readonly projects:ProjectOperations,private readonly companies:CompanyOperations){this.migrate();}
 private migrate(){this.db.exec(`
CREATE TABLE IF NOT EXISTS workflow_definitions_v5(id TEXT PRIMARY KEY,logical_id TEXT NOT NULL,version INTEGER NOT NULL,parent_version_id TEXT REFERENCES workflow_definitions_v5(id),company_id TEXT NOT NULL REFERENCES companies_v4(id) ON DELETE CASCADE,name TEXT NOT NULL,status TEXT NOT NULL,steps TEXT NOT NULL,required_reviews TEXT NOT NULL,required_approvals TEXT NOT NULL,budget_limit REAL NOT NULL,content_hash TEXT NOT NULL,provenance TEXT NOT NULL,created_at TEXT NOT NULL,published_at TEXT,UNIQUE(company_id,logical_id,version));
CREATE TABLE IF NOT EXISTS workflow_bindings_v5(workflow_id TEXT NOT NULL REFERENCES workflow_definitions_v5(id),target_type TEXT NOT NULL,target_id TEXT NOT NULL,company_id TEXT NOT NULL REFERENCES companies_v4(id),created_at TEXT NOT NULL,PRIMARY KEY(target_type,target_id));
CREATE TABLE IF NOT EXISTS plugins_v5(id TEXT PRIMARY KEY,logical_id TEXT NOT NULL,version INTEGER NOT NULL,type TEXT NOT NULL,company_id TEXT NOT NULL REFERENCES companies_v4(id) ON DELETE CASCADE,manifest TEXT NOT NULL,manifest_hash TEXT NOT NULL,signature_meta TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(company_id,logical_id,version));
CREATE TABLE IF NOT EXISTS external_adapters_v5(id TEXT PRIMARY KEY,company_id TEXT REFERENCES companies_v4(id),contract_version TEXT NOT NULL,status TEXT NOT NULL,failures INTEGER NOT NULL,opened_until TEXT,metadata TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS industry_installations_v5(id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies_v4(id),industry TEXT NOT NULL,version INTEGER NOT NULL,bundle_hash TEXT NOT NULL,provenance TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(company_id,industry,version));
CREATE TABLE IF NOT EXISTS platform_audit_v5(seq INTEGER PRIMARY KEY AUTOINCREMENT,company_id TEXT NOT NULL REFERENCES companies_v4(id),type TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL);
`);}
 private audit(companyId:string,type:string,payload:unknown){this.db.prepare("INSERT INTO platform_audit_v5(company_id,type,payload,created_at) VALUES(?,?,?,?)").run(companyId,type,json(payload),now());}
 private deny(companyId:string,type:string,message:string,payload:unknown={}):never{this.audit(companyId,type,payload);throw new Error(message);}
 workflows(companyId:string,actorId:string):WorkflowRecord[]{this.companies.require(companyId,actorId,"view");return(this.db.prepare("SELECT * FROM workflow_definitions_v5 WHERE company_id=? ORDER BY logical_id,version").all(companyId) as Record<string,unknown>[]).map(x=>this.workflowRow(x));}
 workflow(id:string,companyId:string,actorId:string):WorkflowRecord|null{this.companies.require(companyId,actorId,"view");const x=this.db.prepare("SELECT * FROM workflow_definitions_v5 WHERE id=? AND company_id=?").get(id,companyId) as Record<string,unknown>|undefined;return x?this.workflowRow(x):null;}
 private workflowRow(x:Record<string,unknown>):WorkflowRecord{return{id:String(x.id),logicalId:String(x.logical_id),version:Number(x.version),parentVersionId:x.parent_version_id===null?null:String(x.parent_version_id),companyId:String(x.company_id),name:String(x.name),status:String(x.status) as WorkflowStatus,steps:parse(x.steps),requiredReviews:parse(x.required_reviews),requiredApprovals:parse(x.required_approvals),budgetLimit:Number(x.budget_limit),contentHash:String(x.content_hash),provenance:parse(x.provenance),createdAt:String(x.created_at),publishedAt:x.published_at===null?null:String(x.published_at)};}
 createWorkflow(input:Omit<WorkflowRecord,"id"|"version"|"parentVersionId"|"status"|"contentHash"|"createdAt"|"publishedAt">,actorId:string):WorkflowRecord{this.companies.require(input.companyId,actorId,"manage-policy");const latest=this.db.prepare("SELECT id,version FROM workflow_definitions_v5 WHERE company_id=? AND logical_id=? ORDER BY version DESC LIMIT 1").get(input.companyId,input.logicalId) as {id:string;version:number}|undefined;const id=crypto.randomUUID(),version=(latest?.version??0)+1,createdAt=now(),body={...input,steps:input.steps.map(s=>({...s,dependsOn:uniq(s.dependsOn),tools:uniq(s.tools)})),requiredReviews:uniq(input.requiredReviews),requiredApprovals:uniq(input.requiredApprovals)},hash=contentHash(body);this.db.prepare("INSERT INTO workflow_definitions_v5 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,input.logicalId,version,latest?.id??null,input.companyId,input.name,"draft",json(body.steps),json(body.requiredReviews),json(body.requiredApprovals),input.budgetLimit,hash,json(input.provenance),createdAt,null);this.audit(input.companyId,"WORKFLOW_DRAFT_CREATED",{actorId,id,version,hash});return this.workflow(id,input.companyId,actorId)!;}
 validateWorkflow(id:string,companyId:string,actorId:string):WorkflowRecord{this.companies.require(companyId,actorId,"manage-policy");const w=this.workflow(id,companyId,actorId);if(!w)return this.deny(companyId,"WORKFLOW_ACCESS_DENIED","Workflow missing or cross-company",{actorId,id});if(w.status!=="draft")throw new Error("Only draft workflow can be validated");const c=this.companies.company(companyId)!;if(w.budgetLimit<0||w.budgetLimit>c.budgetLimit)this.deny(companyId,"WORKFLOW_POLICY_DENIED","Workflow budget exceeds company",{id});if(c.mandatoryReviews.some(x=>!w.requiredReviews.includes(x))||c.mandatoryApprovals.some(x=>!w.requiredApprovals.includes(x)))this.deny(companyId,"WORKFLOW_POLICY_DENIED","Workflow cannot weaken governance",{id});const ids=new Set<string>();for(const s of w.steps){if(!s.id||ids.has(s.id))this.deny(companyId,"WORKFLOW_INVALID","Duplicate or empty workflow step",{id,step:s.id});ids.add(s.id);if(!s.completionCriteria.length)this.deny(companyId,"WORKFLOW_INVALID","Completion criteria required",{id,step:s.id});const role=this.db.prepare("SELECT company_id FROM role_templates_v15 WHERE id=?").get(s.roleTemplateId) as {company_id:string}|undefined;if(!role||role.company_id!==companyId)this.deny(companyId,"WORKFLOW_INVALID","Role template missing or cross-company",{id,step:s.id});if(s.tools.some(x=>!c.allowedTools.includes(x)))this.deny(companyId,"WORKFLOW_POLICY_DENIED","Workflow tool escalation blocked",{id,step:s.id});}
 for(const s of w.steps)for(const dep of s.dependsOn)if(!ids.has(dep))this.deny(companyId,"WORKFLOW_INVALID","Orphan workflow dependency",{id,step:s.id,dep});const visiting=new Set<string>(),done=new Set<string>(),byId=new Map(w.steps.map(s=>[s.id,s]));const visit=(x:string)=>{if(visiting.has(x))this.deny(companyId,"WORKFLOW_INVALID","Workflow dependency cycle",{id,step:x});if(done.has(x))return;visiting.add(x);for(const d of byId.get(x)!.dependsOn)visit(d);visiting.delete(x);done.add(x);};for(const x of ids)visit(x);
 this.db.prepare("UPDATE workflow_definitions_v5 SET status='validated' WHERE id=? AND company_id=?").run(id,companyId);this.audit(companyId,"WORKFLOW_VALIDATED",{actorId,id});return this.workflow(id,companyId,actorId)!;}
 publishWorkflow(id:string,companyId:string,actorId:string):WorkflowRecord{this.companies.require(companyId,actorId,"manage-policy");const w=this.workflow(id,companyId,actorId);if(!w||w.status!=="validated")throw new Error("Validated workflow required");const current=contentHash({logicalId:w.logicalId,companyId:w.companyId,name:w.name,steps:w.steps,requiredReviews:w.requiredReviews,requiredApprovals:w.requiredApprovals,budgetLimit:w.budgetLimit,provenance:w.provenance});if(current!==w.contentHash)this.deny(companyId,"WORKFLOW_TAMPERED","Workflow content hash mismatch",{id});const publishedAt=now();this.db.prepare("UPDATE workflow_definitions_v5 SET status='published',published_at=? WHERE id=?").run(publishedAt,id);this.audit(companyId,"WORKFLOW_PUBLISHED",{actorId,id});return this.workflow(id,companyId,actorId)!;}
 bindWorkflow(workflowId:string,companyId:string,targetType:"project"|"task"|"run",targetId:string,actorId:string){this.companies.require(companyId,actorId,"manage-policy");const w=this.workflow(workflowId,companyId,actorId);if(!w||w.status!=="published")throw new Error("Published tenant workflow required");let projectId=targetId;if(targetType==="task"){const t=this.projects.task(targetId);if(!t)throw new Error("Workflow task target missing");projectId=t.projectId;}if(targetType==="run"){const x=this.db.prepare("SELECT project_id FROM board_tasks_v3 WHERE run_id=?").get(targetId) as {project_id:string}|undefined;if(!x)throw new Error("Workflow run target missing");projectId=x.project_id;}const tenant=this.db.prepare("SELECT 1 FROM company_projects_v4 WHERE company_id=? AND project_id=?").get(companyId,projectId);if(!tenant)this.deny(companyId,"WORKFLOW_BINDING_DENIED","Workflow target outside company",{workflowId,targetType,targetId});this.db.prepare("INSERT OR REPLACE INTO workflow_bindings_v5 VALUES(?,?,?,?,?)").run(workflowId,targetType,targetId,companyId,now());this.audit(companyId,"WORKFLOW_BOUND",{actorId,workflowId,targetType,targetId});}
 governanceForRun(runId:string){const x=this.db.prepare(`SELECT w.* FROM board_tasks_v3 t JOIN company_projects_v4 cp ON cp.project_id=t.project_id JOIN workflow_bindings_v5 b ON b.company_id=cp.company_id AND ((b.target_type='run' AND b.target_id=t.run_id) OR (b.target_type='task' AND b.target_id=t.id) OR (b.target_type='project' AND b.target_id=t.project_id)) JOIN workflow_definitions_v5 w ON w.id=b.workflow_id WHERE t.run_id=? AND w.status='published' ORDER BY CASE b.target_type WHEN 'run' THEN 1 WHEN 'task' THEN 2 ELSE 3 END LIMIT 1`).get(runId) as Record<string,unknown>|undefined;return x?{workflowId:String(x.id),companyId:String(x.company_id),requiredReviews:parse<string[]>(x.required_reviews),requiredApprovals:parse<string[]>(x.required_approvals),allowedTools:uniq(parse<WorkflowStep[]>(x.steps).flatMap(s=>s.tools)),budgetLimit:Number(x.budget_limit)}:null;}
 registerAdapter(input:ExternalAdapterRecord,actorId:string):ExternalAdapterRecord{if(input.companyId)this.companies.require(input.companyId,actorId,"manage-policy");if(!/^v\d+$/.test(input.contractVersion))throw new Error("Versioned adapter contract required");this.db.prepare("INSERT INTO external_adapters_v5 VALUES(?,?,?,?,?,?,?)").run(input.id,input.companyId,input.contractVersion,input.status,input.failures,input.openedUntil,json(input.metadata));if(input.companyId)this.audit(input.companyId,"ADAPTER_REGISTERED",{actorId,id:input.id});return input;}
 registerPlugin(input:{logicalId:string;type:"role"|"tool";companyId:string;manifest:Record<string,unknown>;manifestHash:string;signature:Record<string,unknown>},actorId:string):PluginRecord{this.companies.require(input.companyId,actorId,"manage-policy");const expected=contentHash(input.manifest);if(input.manifestHash!==expected)this.deny(input.companyId,"PLUGIN_DENIED","Plugin manifest hash mismatch",{logicalId:input.logicalId});if(!input.signature.trust||!input.signature.signer)this.deny(input.companyId,"PLUGIN_DENIED","Plugin signature metadata required",{logicalId:input.logicalId});const c=this.companies.company(input.companyId)!;if(input.type==="role"){for(const k of ["responsibility","inputSchema","outputSchema","requiredReviews","requiredApprovals","allowedTools"] as const)if(input.manifest[k]===undefined)this.deny(input.companyId,"PLUGIN_DENIED",`Role plugin ${k} required`);const reviews=input.manifest.requiredReviews as string[],approvals=input.manifest.requiredApprovals as string[],tools=input.manifest.allowedTools as string[];if(c.mandatoryReviews.some(x=>!reviews.includes(x))||c.mandatoryApprovals.some(x=>!approvals.includes(x))||tools.some(x=>!c.allowedTools.includes(x)))this.deny(input.companyId,"PLUGIN_DENIED","Role plugin violates company policy");}else{for(const k of ["inputSchema","outputSchema","capability","risk","timeoutMs","maxOutputBytes","adapterId"] as const)if(input.manifest[k]===undefined)this.deny(input.companyId,"PLUGIN_DENIED",`Tool plugin ${k} required`);if(!["low","medium","high"].includes(String(input.manifest.risk))||Number(input.manifest.timeoutMs)<=0||Number(input.manifest.timeoutMs)>120000||Number(input.manifest.maxOutputBytes)<=0||Number(input.manifest.maxOutputBytes)>1048576)this.deny(input.companyId,"PLUGIN_DENIED","Tool plugin limits invalid");const adapter=this.db.prepare("SELECT company_id,status FROM external_adapters_v5 WHERE id=?").get(String(input.manifest.adapterId)) as {company_id:string|null;status:string}|undefined;if(!adapter||adapter.status!=="ready"||(adapter.company_id&&adapter.company_id!==input.companyId))this.deny(input.companyId,"PLUGIN_DENIED","Registered ready adapter required");if(!c.allowedTools.includes(String(input.manifest.capability)))this.deny(input.companyId,"PLUGIN_DENIED","Tool capability is not allowed");}
 const latest=this.db.prepare("SELECT id,version FROM plugins_v5 WHERE company_id=? AND logical_id=? ORDER BY version DESC LIMIT 1").get(input.companyId,input.logicalId) as {id:string;version:number}|undefined,id=crypto.randomUUID(),version=(latest?.version??0)+1,createdAt=now();this.db.prepare("INSERT INTO plugins_v5 VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,input.logicalId,version,input.type,input.companyId,json(input.manifest),expected,json(input.signature),"registered",createdAt);this.audit(input.companyId,"PLUGIN_REGISTERED",{actorId,id,type:input.type,version});return{id,logicalId:input.logicalId,version,type:input.type,companyId:input.companyId,manifest:input.manifest,manifestHash:expected,signature:input.signature,status:"registered",createdAt};}
  plugins(companyId:string,actorId:string):PluginRecord[]{this.companies.require(companyId,actorId,"view");return(this.db.prepare("SELECT * FROM plugins_v5 WHERE company_id=? ORDER BY logical_id,version").all(companyId) as Record<string,unknown>[]).map(x=>({id:String(x.id),logicalId:String(x.logical_id),version:Number(x.version),type:String(x.type) as "role"|"tool",companyId:String(x.company_id),manifest:parse(x.manifest),manifestHash:String(x.manifest_hash),signature:parse(x.signature_meta),status:String(x.status) as "registered"|"disabled",createdAt:String(x.created_at)}));}
 authorizeTool(input:{companyId:string;actorId:string;toolPluginId:string;rolePluginId?:string;runId?:string}){this.companies.require(input.companyId,input.actorId,"view");const tool=this.db.prepare("SELECT * FROM plugins_v5 WHERE id=? AND company_id=? AND type='tool' AND status='registered'").get(input.toolPluginId,input.companyId) as Record<string,unknown>|undefined;if(!tool)return this.deny(input.companyId,"TOOL_GATEWAY_DENIED","Registered tenant tool plugin required",input);const manifest=parse<Record<string,unknown>>(tool.manifest),company=this.companies.company(input.companyId)!;if(!company.allowedTools.includes(String(manifest.capability)))return this.deny(input.companyId,"TOOL_GATEWAY_DENIED","Company tool allowlist denied",input);if(input.rolePluginId){const role=this.db.prepare("SELECT manifest FROM plugins_v5 WHERE id=? AND company_id=? AND type='role' AND status='registered'").get(input.rolePluginId,input.companyId) as {manifest:string}|undefined;if(!role||!parse<Record<string,unknown>>(role.manifest).allowedTools||!(parse<Record<string,unknown>>(role.manifest).allowedTools as string[]).includes(String(manifest.capability)))return this.deny(input.companyId,"TOOL_GATEWAY_DENIED","Role plugin tool policy denied",input);}if(input.runId){const g=this.governanceForRun(input.runId);if(g&&(!g.allowedTools.includes(String(manifest.capability))||g.companyId!==input.companyId))return this.deny(input.companyId,"TOOL_GATEWAY_DENIED","Workflow tool policy denied",input);}const decision={allowed:true,toolPluginId:input.toolPluginId,adapterId:String(manifest.adapterId),capability:String(manifest.capability),risk:String(manifest.risk),timeoutMs:Number(manifest.timeoutMs),maxOutputBytes:Number(manifest.maxOutputBytes)};this.audit(input.companyId,"TOOL_GATEWAY_ALLOWED",{...input,decision});return decision;}
 industryPreview(companyId:string,industry:keyof typeof INDUSTRIES,actorId:string){this.companies.require(companyId,actorId,"view");const bundle=INDUSTRIES[industry];if(!bundle)throw new Error("Industry template missing");const installed=this.db.prepare("SELECT version,bundle_hash FROM industry_installations_v5 WHERE company_id=? AND industry=? ORDER BY version DESC LIMIT 1").get(companyId,industry) as {version:number;bundle_hash:string}|undefined;return{industry,bundle,hash:contentHash(bundle),installed:installed??null,diff:installed?.bundle_hash===contentHash(bundle)?[]:["departments","roles","workflow"],requiresApproval:true,provenance:{source:"builtin",industry,version:bundle.version}};}
 installIndustry(companyId:string,industry:keyof typeof INDUSTRIES,expectedHash:string,actorId:string){this.companies.require(companyId,actorId,"manage-org");const p=this.industryPreview(companyId,industry,actorId);if(p.hash!==expectedHash)throw new Error("Industry template approval hash mismatch");this.db.prepare("INSERT INTO industry_installations_v5 VALUES(?,?,?,?,?,?,?)").run(crypto.randomUUID(),companyId,industry,p.bundle.version,p.hash,json(p.provenance),now());this.audit(companyId,"INDUSTRY_TEMPLATE_INSTALLED",{actorId,industry,version:p.bundle.version,hash:p.hash});return p;}
 metrics(companyId:string,actorId:string){this.companies.require(companyId,actorId,"view");const rows=this.db.prepare(`SELECT t.id task_id,t.status,t.run_id,r.status run_status,r.spent,r.created_at,r.updated_at FROM company_projects_v4 cp JOIN board_tasks_v3 t ON t.project_id=cp.project_id LEFT JOIN runs r ON r.id=t.run_id WHERE cp.company_id=? AND NOT EXISTS (SELECT 1 FROM goal_delivery_stage_instances_v19 s WHERE s.run_id=t.run_id AND s.status='revision-requested')`).all(companyId) as Array<Record<string,unknown>>,runIds=rows.flatMap(x=>x.run_id?[String(x.run_id)]:[]),validations=runIds.reduce((n,id)=>n+Number((this.db.prepare("SELECT COUNT(*) n FROM validation_results WHERE run_id=? AND passed=1").get(id) as {n:number}).n),0),validationTotal=runIds.reduce((n,id)=>n+Number((this.db.prepare("SELECT COUNT(*) n FROM validation_results WHERE run_id=?").get(id) as {n:number}).n),0),stale=runIds.reduce((n,id)=>this.db.prepare("SELECT 1 FROM goal_delivery_stage_instances_v19 s JOIN goal_delivery_processes_v19 p ON p.id=s.process_id WHERE s.run_id=? AND p.status='completed' LIMIT 1").get(id)?n:n+this.state.artifactVersionsForRun(id).filter(x=>x.stale&&Number((this.db.prepare("SELECT MAX(version) version FROM artifact_versions_v2 WHERE logical_id=?").get(x.logicalId) as {version:number}).version)===x.version).length,0),cost=rows.reduce((n,x)=>n+Number(x.spent??0),0);return{sampleCount:rows.length,period:{from:rows.map(x=>String(x.created_at??"")).filter(Boolean).sort()[0]??null,to:now()},completionRate:rows.length?rows.filter(x=>x.status==="done"||x.run_status==="COMPLETED").length/rows.length:0,validationRate:validationTotal?validations/validationTotal:0,staleCount:stale,cost,provenance:{taskIds:rows.map(x=>String(x.task_id)),runIds}};}
 expansionRecommendations(companyId:string,actorId:string){const m=this.metrics(companyId,actorId),blocked=Number((this.db.prepare(`SELECT COUNT(*) n FROM company_projects_v4 cp JOIN board_tasks_v3 t ON t.project_id=cp.project_id LEFT JOIN runs r ON r.id=t.run_id WHERE cp.company_id=? AND (t.status='blocked' OR r.status='BLOCKED')`).get(companyId) as {n:number}).n),items=[] as unknown[];if(blocked>0)items.push({kind:"role",reason:`${blocked} blocked tasks`,evidence:{blocked},requiresApproval:true,action:"review-capacity"});if(m.sampleCount>=3&&m.completionRate<0.5)items.push({kind:"department",reason:"low portfolio completion",evidence:{completionRate:m.completionRate,sampleCount:m.sampleCount},requiresApproval:true,action:"review-organization"});return{companyId,items,readOnly:true,provenance:m.provenance};}
 gameState(companyId:string,actorId:string){const m=this.metrics(companyId,actorId),value={milestones:[m.sampleCount>0?"work-started":null,m.completionRate===1&&m.sampleCount>0?"portfolio-complete":null].filter(Boolean),badges:[m.validationRate===1&&m.sampleCount>0?"quality-gate":null,m.staleCount===0&&m.sampleCount>0?"fresh-artifacts":null].filter(Boolean),progress:{completed:m.completionRate,total:m.sampleCount},readOnly:true,provenance:m.provenance};return{...value,stateHash:contentHash(value)};}
 snapshot(companyId:string,actorId:string){return{workflows:this.workflows(companyId,actorId),plugins:this.plugins(companyId,actorId),industries:(Object.keys(INDUSTRIES) as Array<keyof typeof INDUSTRIES>).map(x=>this.industryPreview(companyId,x,actorId)),metrics:this.metrics(companyId,actorId),recommendations:this.expansionRecommendations(companyId,actorId),game:this.gameState(companyId,actorId),adapters:this.db.prepare("SELECT id,contract_version AS contractVersion,status,failures,opened_until AS openedUntil,metadata FROM external_adapters_v5 WHERE company_id IS NULL OR company_id=? ORDER BY id").all(companyId),audit:this.auditEvents(companyId,actorId)};}
  auditEvents(companyId:string,actorId:string){this.companies.require(companyId,actorId,"view");return this.db.prepare("SELECT seq,type,payload,created_at AS createdAt FROM platform_audit_v5 WHERE company_id=? ORDER BY seq").all(companyId);}
 auditRunPolicyDenied(runId:string,payload:unknown){const g=this.governanceForRun(runId);if(g)this.audit(g.companyId,"WORKFLOW_RUN_POLICY_DENIED",{runId,...payload as object});}
}

export class PlatformRunGovernance{
 constructor(private readonly companies:CompanyOperations,private readonly platform:PlatformOperations){}
 freeze(runId:string){return this.companies.freezeRunExecution(runId);}
 context(runId:string,role:"planner"|"worker"|"reviewer"="worker"){const company=this.companies.governanceForRun(runId,role),workflow=this.platform.governanceForRun(runId);if(!company)return workflow;if(!workflow)return company;return{companyId:company.companyId,workflowId:workflow.workflowId,templateId:company.templateId,profile:company.profile,requiredReviews:uniq([...company.requiredReviews,...workflow.requiredReviews]),requiredApprovals:uniq([...company.requiredApprovals,...workflow.requiredApprovals]),allowedTools:company.allowedTools.filter(x=>workflow.allowedTools.includes(x)),budgetLimit:Math.min(workflow.budgetLimit,this.companies.company(company.companyId)!.budgetLimit)};}
 requiresReviewer(runId:string){return ((this.context(runId) as {requiredReviews?:string[]}|null)?.requiredReviews?.length??0)>0;}
 assertTools(runId:string,tools:readonly string[]){const g=this.context(runId) as {allowedTools?:string[]}|null;if(!g?.allowedTools)return;const denied=tools.filter(x=>!g.allowedTools!.includes(x));if(denied.length){this.platform.auditRunPolicyDenied(runId,{reason:"tool-denied",denied});throw new Error(`Published workflow blocks tools: ${denied.join(",")}`);}}
}

export class MockExternalAgentAdapter{
 private readonly results=new Map<string,unknown>();private failures=0;private openUntil=0;
 constructor(private readonly state:StateStore,readonly id:string,readonly contractVersion="v1",private readonly authScope="agent:invoke",private readonly threshold=2,private readonly cooldownMs=1000){}
 async invoke(input:{runId:string;requestId:string;contractVersion:string;scope:string;deadline:string;payload:unknown;simulateFailure?:boolean}){if(input.contractVersion!==this.contractVersion)throw new Error("Adapter contract mismatch");if(input.scope!==this.authScope)throw new Error("Adapter auth scope denied");if(Date.parse(input.deadline)<=Date.now())throw new Error("Adapter deadline exceeded");if(Date.now()<this.openUntil)throw new Error("Adapter circuit open");if(this.results.has(input.requestId))return this.results.get(input.requestId);if(input.simulateFailure){this.failures++;this.state.recordToolCall(input.runId,this.id,"failed",{requestId:input.requestId});if(this.failures>=this.threshold)this.openUntil=Date.now()+this.cooldownMs;throw new Error("Mock external failure");}const result={adapterId:this.id,requestId:input.requestId,output:input.payload};this.results.set(input.requestId,result);this.failures=0;this.state.recordToolCall(input.runId,this.id,"completed",{requestId:input.requestId});this.state.recordUsage(input.runId,input.requestId,0,0);this.state.audit(input.runId,"EXTERNAL_ADAPTER_INVOKED",{adapterId:this.id,requestId:input.requestId});return result;}
 status(){return{id:this.id,contractVersion:this.contractVersion,status:Date.now()<this.openUntil?"open":"ready",failures:this.failures,openedUntil:this.openUntil?new Date(this.openUntil).toISOString():null};}
}
