import { CONTRACT_VERSION, type AgentEvent, type HostCapabilities, type ModelInfo, type ModelRequest, type ModelResult, type UsageRecord, type UserContext } from "../../../packages/contracts/src/index.js";
import { AdapterError, assertContractVersion, signalForDeadline, type HostAdapter } from "../../../packages/host-adapter-sdk/src/index.js";
import { ModelClientError, type ModelClient } from "../../../packages/model-adapters/src/index.js";

export class StandaloneHostAdapter implements HostAdapter {
  readonly usage: UsageRecord[] = [];
  readonly events: AgentEvent[] = [];
  private readonly results = new Map<string, ModelResult>();
  available = true;

  constructor(private readonly modelClient?: ModelClient,readonly hostId="standalone") {}

  async capabilities(): Promise<HostCapabilities> { return { auth: true, models: true, usage: true, events: true, streamingAbort: true }; }
  async authenticate(request: unknown): Promise<UserContext> {
    if (!request || typeof request !== "object" || !("token" in request)) throw new AdapterError("AUTHENTICATION_FAILED", "token required");
    return { userId: "standalone-user", roles: ["owner"] };
  }
  async listModels(): Promise<ModelInfo[]> {
    if (this.modelClient) { const ids = await this.modelClient.listModels(); return ids.map(id => ({ id, label: id })); }
    return [{ id: "phase0-model", label: "Deterministic Phase 0 Model" }];
  }
  async invokeModel(request: ModelRequest): Promise<ModelResult> {
    assertContractVersion(request.contractVersion);
    if (!this.available) throw new AdapterError("HOST_UNAVAILABLE", "standalone unavailable");
    if (request.signal?.aborted) throw new DOMException("Aborted", "AbortError");
    const cached = this.results.get(request.requestId); if (cached) return cached;
    if (this.modelClient) {
      try {
        const completion = await this.modelClient.complete({ model: request.model, prompt: request.prompt, signal: signalForDeadline(request.deadline, request.signal) });
        const result = { requestId: request.requestId, ...completion }; this.results.set(request.requestId, result); return result;
      } catch (error) {
        if (error instanceof DOMException && error.name === "AbortError") throw error;
        if(error instanceof ModelClientError)throw new AdapterError(error.code,error.message);
        throw new AdapterError("HOST_UNAVAILABLE", error instanceof Error ? error.message : "model client unavailable");
      }
    }
    let text = `[${request.model}] ${request.prompt}`;
    try {
      const input = JSON.parse(request.prompt) as { role?: string; goal?: string; runContext?: { requestedPaths?: string[] } };
      if (input.role === "worker") text = JSON.stringify({ changes: (input.runContext?.requestedPaths ?? []).map(path => ({ path, content: `// generated by standalone worker for: ${input.goal ?? "goal"}\nexport const completed = true;\n` })) });
      else if (input.role === "planner") text = JSON.stringify({ summary: `plan created: ${input.goal ?? "goal"}`, tasks: [{ id: "implementation", role: "worker", completionCriteria: ["requested changes implemented", "all configured checks pass"], validationCommands: ["build", "test", "lint", "security"] }] });
      else if (input.role === "reviewer") text = JSON.stringify({ summary: `review completed: ${input.goal ?? "goal"}`, risks: [] });
    } catch { /* non-pipeline prompts retain deterministic echo behavior */ }
    const result = { requestId: request.requestId, text, tokens: request.prompt.length, cost: Math.min(request.prompt.length / 1000,0.25) };
    this.results.set(request.requestId, result); return result;
  }
  async recordUsage(usage: UsageRecord): Promise<void> { if (!this.usage.some(x => x.requestId === usage.requestId)) this.usage.push(usage); }
  async publishEvent(event: AgentEvent): Promise<void> { if (!this.events.some(x => x.id === event.id)) this.events.push(event); }
}

export { CONTRACT_VERSION };
