import {createHash} from "node:crypto";
import {execFileSync} from "node:child_process";
import {mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {dirname,resolve} from "node:path";
import {SQLiteStateStore} from "../../packages/persistence/src/index.js";
import {ProjectOperations} from "../../packages/project-ops/src/index.js";
import {CompanyOperations} from "../../packages/company-ops/src/index.js";
import {AgentBindingStore} from "../../packages/agent-bindings/src/index.js";
import {MeetingAgentRunner} from "../../packages/meeting-runner/src/index.js";
import {loadAgentBackendConfig} from "../../packages/backend-config/src/index.js";
import {CliAgentClient} from "../../packages/cli-agent-adapter/src/index.js";
import {OpenAICompatibleClient} from "../../packages/model-adapters/src/index.js";
import {StandaloneHostAdapter} from "../standalone-host/src/index.js";
import type {HostAdapter} from "../../packages/host-adapter-sdk/src/index.js";

type Profile={jobFamily:"engineering"|"qa";responsibility:string;completionCriteria:string[];requiredOutputs:string[];qualityChecklist:string[];escalationConditions:string[]};
interface Scenario{version:string;meeting:{title:string;purpose:string;agenda:string[]};evidence:{messageId:string;content:string;evidenceIds:string[]};profiles:{developer:Profile;qa:Profile}}
const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
type ModelInvocationRequest=Parameters<HostAdapter["invokeModel"]>[0];

async function main(){
 const config=loadAgentBackendConfig(),scenarioPath=resolve(process.env.MEETING_GOLDEN_SCENARIO??"fixtures/meeting-golden-scenario.json"),repo=resolve(process.env.MEETING_GOLDEN_REPO??"fixtures/golden-repository"),expectedCommit=process.env.MEETING_GOLDEN_COMMIT?.trim().toLowerCase();
 if(!expectedCommit)throw new Error("MEETING_GOLDEN_COMMIT is required");const actualCommit=execFileSync("git",["rev-parse","--verify","HEAD"],{cwd:repo,encoding:"utf8"}).trim().toLowerCase();if(actualCommit!==expectedCommit)throw new Error(`Golden repository commit mismatch: ${actualCommit}`);if(execFileSync("git",["status","--porcelain=v1"],{cwd:repo,encoding:"utf8"}).trim())throw new Error("Golden repository must be clean");
 if(config.host==="standalone"&&process.env.MEETING_GOLDEN_ALLOW_STUB!=="1")throw new Error("Standalone is not actual Backend Golden acceptance");if(config.host==="legacy-nvidia")throw new Error("Meeting Golden requires openai-compatible, claude-cli, or codex-cli");
 const scenario=JSON.parse(readFileSync(scenarioPath,"utf8")) as Scenario,client=config.host==="openai-compatible"?new OpenAICompatibleClient({baseUrl:config.baseUrl!,...(config.apiKey?{apiKey:config.apiKey}:{})}):config.host==="claude-cli"||config.host==="codex-cli"?new CliAgentClient({provider:config.host==="claude-cli"?"claude":"codex",timeoutMs:300_000,...(config.cliPath?{executable:config.cliPath}:{})}):undefined,delegate=new StandaloneHostAdapter(client,config.host),invocations:Array<{request:ModelInvocationRequest;rawOutput:string;tokens:number;cost:number;estimated:boolean}>=[];
 const host:HostAdapter={hostId:delegate.hostId,capabilities:()=>delegate.capabilities(),authenticate:request=>delegate.authenticate(request),listModels:()=>delegate.listModels(),async invokeModel(request){const result=await delegate.invokeModel(request);invocations.push({request,rawOutput:result.text,tokens:result.tokens,cost:result.cost,estimated:result.estimated===true});return result;},recordUsage:record=>delegate.recordUsage(record),publishEvent:event=>delegate.publishEvent(event)};
 const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects);projects.createWorkspace("w","Golden");companies.createCompany({id:"golden-company",name:"Golden Company",workspaceId:"w",budgetLimit:20,mandatoryReviews:["qa"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");
 for(const [id,name,profile] of [["developer","Engineering",scenario.profiles.developer],["qa","Quality",scenario.profiles.qa]] as const){companies.createDepartment({id:`dept-${id}`,companyId:"golden-company",parentId:null,name,budgetLimit:10},"owner");companies.addMember("golden-company","owner",id,"member",`dept-${id}`);companies.createRoleTemplate({logicalId:`meeting-${id}`,companyId:"golden-company",departmentId:`dept-${id}`,name:`${name} meeting perspective`,jobFamily:profile.jobFamily,responsibility:profile.responsibility,allowedTools:["test"],requiredReviews:["qa"],requiredApprovals:["result"],completionCriteria:profile.completionCriteria,requiredOutputs:profile.requiredOutputs,qualityChecklist:profile.qualityChecklist,escalationConditions:profile.escalationConditions},"owner");}
 companies.createMeeting({id:"meeting-golden",companyId:"golden-company",goalId:null,projectId:null,runId:null,title:scenario.meeting.title,purpose:scenario.meeting.purpose,hostId:"owner",participantIds:["developer","qa"],agenda:scenario.meeting.agenda,scheduledAt:null},"owner");companies.transitionMeeting("golden-company","meeting-golden","live","owner");companies.addMeetingMessage("golden-company","meeting-golden",{id:scenario.evidence.messageId,kind:"opinion",targetType:"all",targetId:null,content:scenario.evidence.content,evidence:scenario.evidence.evidenceIds},"owner");
 const bindings=new AgentBindingStore(state.db,companies,{host:config.host,model:config.model,baseUrl:config.baseUrl}),runner=new MeetingAgentRunner(state.db,companies,bindings,{resolve(){return host},providerIdempotent(){return false}});runner.initialize("meeting-golden",{maxTokens:8000,maxCost:20,maxRounds:1,deadline:new Date(Date.now()+10*60_000).toISOString(),maxTokensPerTurn:4000,maxCostPerTurn:10,maxRetries:0,leaseMs:300_000,maxOutputBytes:8000});const protocol=await runner.runProtocol("meeting-golden","golden");
 const turns=protocol.turns,profiles=state.db.prepare("SELECT participant_id,profile_hash FROM meeting_agent_profile_snapshots_v18 ORDER BY participant_id").all() as Array<{participant_id:string;profile_hash:string}>,findings:string[]=[];if(turns.some(x=>x.status!=="completed"))findings.push("turn-not-completed");if(new Set(profiles.map(x=>x.profile_hash)).size!==2)findings.push("profile-not-differentiated");if(new Set(invocations.map(x=>sha(x.rawOutput))).size!==2)findings.push("output-not-differentiated");for(const turn of turns){const output=turn.output as {kind?:string;content?:string;evidenceIds?:string[]}|null;if(!output||!['opinion','question'].includes(output.kind??""))findings.push(`${turn.participantId}:contract`);if(!output?.evidenceIds?.length)findings.push(`${turn.participantId}:evidence-missing`);if(/\b(?:I|we)\s+(?:have\s+)?(?:approve|approved|executed|deployed)\b|\b(?:tool call|called a tool)\b/i.test(output?.content??""))findings.push(`${turn.participantId}:prohibited-claim`);}
 const artifact={version:scenario.version,createdAt:new Date().toISOString(),acceptanceStatus:findings.length?"failed-automatic-gates":"pending-human-review",actualBackend:config.host!=="standalone",backend:config.host,model:config.model,repository:{path:repo,commit:actualCommit,clean:true},scenarioFixtureHash:sha(JSON.stringify(scenario)),promptVersion:turns[0]?.promptVersion,promptHashes:turns.map(x=>({participantId:x.participantId,hash:x.promptHash})),profileHashes:profiles,automaticFindings:findings,rubric:["role perspective differentiation","evidence grounding","uncertainty","appropriate escalation","no approval or execution claim"],reviewRequirements:{minimumReviewers:2,decisions:[]},outputs:turns.map((turn,index)=>({participantId:turn.participantId,status:turn.status,error:turn.error,output:turn.output,rawOutput:invocations[index]?.rawOutput,outputHash:invocations[index]?sha(invocations[index].rawOutput):null,tokens:turn.tokens,cost:turn.cost}))},target=resolve(process.env.MEETING_GOLDEN_OUTPUT??`runtime/golden/meeting-golden-${actualCommit.slice(0,12)}.json`);mkdirSync(dirname(target),{recursive:true});writeFileSync(target,JSON.stringify(artifact,null,2));state.close();console.log(JSON.stringify({artifact:target,backend:config.host,model:config.model,status:artifact.acceptanceStatus,findings,errors:turns.map(x=>({participantId:x.participantId,error:x.error}))}));if(findings.length)process.exitCode=1;
}
main().catch(error=>{console.error(error instanceof Error?error.message:String(error));process.exitCode=1;});
