import { createHash } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import type { CompanyMode } from "../../contracts/src/index.js";
import type { OperationalStore } from "../../operations/src/index.js";
import { mapLegacyEvent } from "../../event-mapper/src/index.js";

type Skill="delivery"|"quality"|"efficiency"|"risk";
export interface GameIncident { sourceEventId:string;runId:string|null;type:string;severity:"warning"|"critical";reason:string;occurredAt:string;resolvedAt:string|null;resolution:string|null }
export interface GameBriefing { sourceEventId:string;runId:string|null;summary:string;reward:number;incidentCount:number;provenance:string[] }
export interface GameProgression {
  companyId:string;mode:CompanyMode;companyXp:number;level:number;unlocks:string[];
  agents:Array<{agentId:string;xp:number;skills:Record<Skill,number>}>;
  metrics:{completedRuns:number;qualityPasses:number;validationFailures:number;incidents:number;rewardedEvents:number;provenance:{rewardEventIds:string[];incidentEventIds:string[];briefingEventIds:string[]}};
  achievements:string[];ledger:Array<{sourceEventId:string;agentId:string;amount:number;reason:string}>;
  incidents:GameIncident[];briefings:GameBriefing[];lastSequence:number;stateHash:string;
}
const stable=(x:unknown)=>JSON.stringify(x,(_,v)=>v&&typeof v==="object"&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v);
const hash=(x:unknown)=>createHash("sha256").update(stable(x)).digest("hex");
const companyLevel=(xp:number)=>xp>=3000?10:xp>=2400?9:xp>=1900?8:xp>=1450?7:xp>=1000?6:xp>=500?5:xp>=300?4:xp>=150?3:xp>=50?2:1;
const unlocksFor=(level:number)=>["starter-office",...(level>=2?["team-board"]:[]),...(level>=3?["quality-lab"]:[]),...(level>=4?["incident-room","second-project-view"]:[]),...(level>=5?["executive-floor","specialist-floor","professional-reviewers"]:[]),...(level>=6?["parallel-run-advice"]:[]),...(level>=7?["advanced-cost-analysis"]:[]),...(level>=8?["office-themes","executive-suite"]:[]),...(level>=9?["organization-expansion-simulation"]:[]),...(level>=10?["multi-company-entry","archive-floor"]:[])];
const safetyType=(type:string)=>type.includes("scope_blocked")||type.includes("policy_denied")||type.includes("authorization_denied")||type.includes("gateway_denied")||type.includes("tampered")||type.startsWith("security.");
const emptySkills=():Record<Skill,number>=>({delivery:0,quality:0,efficiency:0,risk:0});

export class GameProgressionStore{
  constructor(private readonly db:DatabaseSync,private readonly operations:OperationalStore){this.db.exec(`
CREATE TABLE IF NOT EXISTS game_reward_ledger_v7(id TEXT PRIMARY KEY,company_id TEXT NOT NULL,agent_id TEXT NOT NULL,source_event_id TEXT NOT NULL,reward_type TEXT NOT NULL,amount INTEGER NOT NULL CHECK(amount>=0),reason TEXT NOT NULL,mode TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(company_id,mode,source_event_id,reward_type));
CREATE TABLE IF NOT EXISTS game_achievements_v7(id TEXT PRIMARY KEY,company_id TEXT NOT NULL,achievement TEXT NOT NULL,source_event_id TEXT NOT NULL,mode TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(company_id,mode,achievement));
CREATE TABLE IF NOT EXISTS game_projection_cursor_v7(company_id TEXT NOT NULL,mode TEXT NOT NULL,last_sequence INTEGER NOT NULL,PRIMARY KEY(company_id,mode));
CREATE TABLE IF NOT EXISTS game_agent_skills_v8(company_id TEXT NOT NULL,mode TEXT NOT NULL,agent_id TEXT NOT NULL,source_event_id TEXT NOT NULL,skill TEXT NOT NULL,amount INTEGER NOT NULL CHECK(amount>=0),created_at TEXT NOT NULL,PRIMARY KEY(company_id,mode,source_event_id,skill));
CREATE TABLE IF NOT EXISTS game_incidents_v8(company_id TEXT NOT NULL,mode TEXT NOT NULL,source_event_id TEXT NOT NULL,run_id TEXT,type TEXT NOT NULL,severity TEXT NOT NULL,reason TEXT NOT NULL,occurred_at TEXT NOT NULL,PRIMARY KEY(company_id,mode,source_event_id));
CREATE TABLE IF NOT EXISTS game_briefings_v8(company_id TEXT NOT NULL,mode TEXT NOT NULL,source_event_id TEXT NOT NULL,run_id TEXT,summary TEXT NOT NULL,reward INTEGER NOT NULL,incident_count INTEGER NOT NULL,provenance TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(company_id,mode,source_event_id));CREATE TABLE IF NOT EXISTS incident_resolutions_v9(incident_id TEXT PRIMARY KEY,run_id TEXT NOT NULL,resolution TEXT NOT NULL,actor_id TEXT NOT NULL,created_at TEXT NOT NULL);`);}
  catchUp(companyId:string,mode:CompanyMode):GameProgression{let cursor=this.cursor(companyId,mode);for(;;){const rows=this.operations.events(companyId,cursor,1000);if(!rows.length)break;for(const row of rows){const event=mapLegacyEvent(row,mode);this.apply(event);cursor=event.sequence;}if(rows.length<1000)break;}return this.snapshot(companyId,mode);}
  rebuild(companyId:string,mode:CompanyMode):GameProgression{this.db.exec("BEGIN IMMEDIATE");try{for(const table of ["game_reward_ledger_v7","game_achievements_v7","game_projection_cursor_v7","game_agent_skills_v8","game_incidents_v8","game_briefings_v8"])this.db.prepare(`DELETE FROM ${table} WHERE company_id=? AND mode=?`).run(companyId,mode);this.db.exec("COMMIT");}catch(e){try{this.db.exec("ROLLBACK");}catch{}throw e;}return this.catchUp(companyId,mode);}
  snapshot(companyId:string,mode:CompanyMode):GameProgression{
    const ledger=this.db.prepare("SELECT source_event_id AS sourceEventId,agent_id AS agentId,amount,reason FROM game_reward_ledger_v7 WHERE company_id=? AND mode=? ORDER BY source_event_id,reward_type").all(companyId,mode) as Array<{sourceEventId:string;agentId:string;amount:number;reason:string}>;
    const achievements=(this.db.prepare("SELECT achievement FROM game_achievements_v7 WHERE company_id=? AND mode=? ORDER BY achievement").all(companyId,mode) as Array<{achievement:string}>).map(x=>x.achievement);
    const skillRows=this.db.prepare("SELECT agent_id agentId,skill,amount FROM game_agent_skills_v8 WHERE company_id=? AND mode=? ORDER BY agent_id,skill").all(companyId,mode) as Array<{agentId:string;skill:Skill;amount:number}>;
    const agentIds=[...new Set([...ledger.map(x=>x.agentId),...skillRows.map(x=>x.agentId)])].sort(),agents=agentIds.map(agentId=>{const skills=emptySkills();for(const row of skillRows.filter(x=>x.agentId===agentId))skills[row.skill]+=Number(row.amount);return{agentId,xp:ledger.filter(x=>x.agentId===agentId).reduce((n,x)=>n+Number(x.amount),0),skills};});
    const incidents=this.db.prepare("SELECT i.source_event_id sourceEventId,i.run_id runId,i.type,i.severity,i.reason,i.occurred_at occurredAt,r.created_at resolvedAt,r.resolution FROM game_incidents_v8 i LEFT JOIN incident_resolutions_v9 r ON r.incident_id=i.source_event_id WHERE i.company_id=? AND i.mode=? ORDER BY i.occurred_at,i.source_event_id").all(companyId,mode) as unknown as GameIncident[];
    const briefings=(this.db.prepare("SELECT source_event_id sourceEventId,run_id runId,summary,reward,incident_count incidentCount,provenance FROM game_briefings_v8 WHERE company_id=? AND mode=? ORDER BY created_at,source_event_id").all(companyId,mode) as Array<Omit<GameBriefing,"provenance">&{provenance:string}>).map(x=>({...x,provenance:JSON.parse(x.provenance) as string[]}));
    const completedRuns=briefings.length,qualityPasses=Number((this.db.prepare(`SELECT COUNT(*) n FROM events_v6 WHERE tenant_id=? AND type='VALIDATION_COMPLETED' AND json_extract(payload,'$.passed')=1`).get(companyId) as {n:number}).n),validationFailures=Number((this.db.prepare("SELECT COUNT(*) n FROM events_v6 WHERE tenant_id=? AND type='VALIDATION_FAILED'").get(companyId) as {n:number}).n),companyXp=ledger.reduce((n,x)=>n+Number(x.amount),0),level=companyLevel(companyXp),metrics={completedRuns,qualityPasses,validationFailures,incidents:incidents.length,rewardedEvents:ledger.length,provenance:{rewardEventIds:ledger.map(x=>x.sourceEventId),incidentEventIds:incidents.map(x=>x.sourceEventId),briefingEventIds:briefings.map(x=>x.sourceEventId)}},body={companyId,mode,companyXp,level,unlocks:unlocksFor(level),agents,metrics,achievements,ledger,incidents,briefings,lastSequence:this.cursor(companyId,mode)};return{...body,stateHash:hash(body)};
  }
  private apply(event:ReturnType<typeof mapLegacyEvent>):void{
    if(event.sequence<=this.cursor(event.companyId,event.mode))return;const payload=event.payload as Record<string,unknown>;
    this.db.exec("BEGIN IMMEDIATE");try{
      if(safetyType(event.type))this.db.prepare("INSERT OR IGNORE INTO game_incidents_v8 VALUES(?,?,?,?,?,?,?,?)").run(event.companyId,event.mode,event.eventId,event.runId??null,event.type,"critical",`${event.type} blocked by safety policy`,event.occurredAt);
      if(event.type==="validation.failed")this.db.prepare("INSERT OR IGNORE INTO game_incidents_v8 VALUES(?,?,?,?,?,?,?,?)").run(event.companyId,event.mode,event.eventId,event.runId??null,event.type,"warning","Validation failed and requires revision",event.occurredAt);
      if(event.type==="workflow.completed")this.complete(event,payload);
      this.db.prepare("INSERT OR REPLACE INTO game_projection_cursor_v7 VALUES(?,?,?)").run(event.companyId,event.mode,event.sequence);this.db.exec("COMMIT");
    }catch(e){try{this.db.exec("ROLLBACK");}catch{}throw e;}
  }
  private complete(event:ReturnType<typeof mapLegacyEvent>,payload:Record<string,unknown>):void{
    const runId=event.runId??null,run=runId?this.db.prepare("SELECT risk,budget_limit budgetLimit,spent FROM runs WHERE id=?").get(runId) as {risk:string;budgetLimit:number;spent:number}|undefined:undefined;
    const incidentCount=Number((this.db.prepare("SELECT COUNT(*) n FROM game_incidents_v8 WHERE company_id=? AND mode=? AND run_id IS ?").get(event.companyId,event.mode,runId) as {n:number}).n),safetyCount=Number((this.db.prepare("SELECT COUNT(*) n FROM game_incidents_v8 WHERE company_id=? AND mode=? AND run_id IS ? AND severity='critical'").get(event.companyId,event.mode,runId) as {n:number}).n);
    const validations=runId?this.db.prepare("SELECT passed FROM validation_results WHERE run_id=?").all(runId) as Array<{passed:number}>:[],failures=Math.max(validations.filter(x=>!x.passed).length,incidentCount-safetyCount),passes=validations.filter(x=>x.passed).length,recovery=failures>0||!!this.db.prepare("SELECT 1 FROM events_v6 WHERE tenant_id=? AND cursor<? AND type='VALIDATION_FAILED' AND json_extract(payload,'$.runId') IS ? LIMIT 1").get(event.companyId,event.sequence,runId);
    const riskBonus=run?({low:0,medium:2,high:4,critical:6}[run.risk]??0):0,costBonus=run&&run.budgetLimit>0&&run.spent/run.budgetLimit<=.5?3:0,qualityBonus=passes>0?5:0,recoveryPenalty=recovery?2:0,reward=safetyCount?0:run?Math.max(1,20+riskBonus+qualityBonus+costBonus-recoveryPenalty):recovery?23:25;
    const agentId=typeof payload.contributorAgentId==="string"?payload.contributorAgentId:event.agentId??"unassigned",reason=safetyCount?"Reward blocked by safety incident":`Completed workflow: risk +${riskBonus}, quality +${qualityBonus}, efficiency +${costBonus}, recovery -${recoveryPenalty}`;
    if(reward>0){this.db.prepare("INSERT OR IGNORE INTO game_reward_ledger_v7 VALUES(?,?,?,?,?,?,?,?,?)").run(crypto.randomUUID(),event.companyId,agentId,event.eventId,"workflow-completion",reward,reason,event.mode,event.occurredAt);for(const [skill,amount] of [["delivery",20],["quality",qualityBonus],["efficiency",costBonus],["risk",riskBonus]] as Array<[Skill,number]>)if(amount)this.db.prepare("INSERT OR IGNORE INTO game_agent_skills_v8 VALUES(?,?,?,?,?,?,?)").run(event.companyId,event.mode,agentId,event.eventId,skill,amount,event.occurredAt);for(const achievement of ["first-delivery",...(qualityBonus?["quality-delivery"]:[]),...(costBonus?["efficient-delivery"]:[]),...(recovery&&run?["revision-recovery"]:[])])this.db.prepare("INSERT OR IGNORE INTO game_achievements_v7 VALUES(?,?,?,?,?,?)").run(crypto.randomUUID(),event.companyId,achievement,event.eventId,event.mode,event.occurredAt);}
    const provenance=[event.eventId,...this.incidentIds(event.companyId,event.mode,runId)].sort(),summary=safetyCount?`Run ${runId??"unknown"} completed but reward was blocked by ${safetyCount} safety incident(s).`:`Run ${runId??"unknown"} completed with ${reward} XP; ${passes} validation(s) passed and ${failures} revision signal(s) recorded.`;
    this.db.prepare("INSERT OR IGNORE INTO game_briefings_v8 VALUES(?,?,?,?,?,?,?,?,?)").run(event.companyId,event.mode,event.eventId,runId,summary,reward,incidentCount,JSON.stringify(provenance),event.occurredAt);
  }
  private incidentIds(companyId:string,mode:CompanyMode,runId:string|null):string[]{return(this.db.prepare("SELECT source_event_id id FROM game_incidents_v8 WHERE company_id=? AND mode=? AND run_id IS ? ORDER BY source_event_id").all(companyId,mode,runId) as Array<{id:string}>).map(x=>x.id);}
  private cursor(companyId:string,mode:CompanyMode):number{return Number((this.db.prepare("SELECT last_sequence FROM game_projection_cursor_v7 WHERE company_id=? AND mode=?").get(companyId,mode) as {last_sequence:number}|undefined)?.last_sequence??0);}
}
