import test from "node:test";
import assert from "node:assert/strict";
import { SQLiteStateStore } from "../packages/persistence/src/index.js";
import { ProjectOperations } from "../packages/project-ops/src/index.js";
import { CompanyOperations } from "../packages/company-ops/src/index.js";
import { AgentBindingStore } from "../packages/agent-bindings/src/index.js";
import { RunController } from "../packages/runtime/src/index.js";
import { RolePipeline } from "../packages/role-pipeline/src/index.js";
import { StandaloneHostAdapter } from "../apps/standalone-host/src/index.js";

function setup(mode:"live"|"demo"="live"){
 const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects);projects.createWorkspace("w","W");projects.createProject({id:"p",workspaceId:"w",name:"P",repoPath:".",defaultBranch:"main",runtimePath:".",organizationProfile:{},budgetLimit:10},"owner");projects.createTask({id:"t",projectId:"p",milestoneId:null,title:"T",status:"ready",priority:1,completionCriteria:["done"],budgetLimit:5},{id:"owner"});companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:20,mandatoryReviews:["review"],mandatoryApprovals:["result"],allowedTools:["test"],mode},"owner");companies.createDepartment({id:"d",companyId:"c",parentId:null,name:"D",budgetLimit:20},"owner");companies.addMember("c","owner","worker-agent","member","d");companies.addMember("c","owner","review-agent","member","d");companies.linkProject("c","d","p",1,"owner");state.createRun({id:"r",requestId:"q",goal:"g",risk:"high",status:"CREATED",budgetLimit:5,spent:0,checkpoint:null});projects.linkRun("t","r",{id:"owner"});projects.assign("t",{id:"owner"},"worker-agent","agent","executor");projects.assign("t",{id:"owner"},"review-agent","agent","reviewer");return{state,projects,companies,bindings:new AgentBindingStore(state.db,companies,{host:"standalone",model:"runtime-model",baseUrl:null})};
}

test("binding resolution uses member then role then company and freezes the Run snapshot",()=>{const{state,bindings}=setup();bindings.set("c","owner",{targetKind:"company",backend:"openai-compatible",modelId:"company-model"});bindings.set("c","owner",{targetKind:"role",targetId:"reviewer",backend:"claude-cli",modelId:"role-model"});bindings.set("c","owner",{targetKind:"member",targetId:"worker-agent",backend:"codex-cli",modelId:"member-model"});assert.equal(bindings.resolveRun("r","worker").resolution,"member");assert.equal(bindings.resolveRun("r","reviewer").resolution,"role");assert.equal(bindings.resolveRun("r","planner").resolution,"company");bindings.set("c","owner",{targetKind:"member",targetId:"worker-agent",backend:"claude-cli",modelId:"changed-after-start"});assert.equal(bindings.resolveRun("r","worker").modelId,"member-model");assert.equal(bindings.snapshots("r").length,3);assert.match(JSON.stringify(state.db.prepare("SELECT type,payload FROM company_audit_v4 ORDER BY seq").all()),/RUN_AGENT_BINDINGS_SNAPSHOTTED/);state.close();});
test("Demo mode always forces deterministic stub",()=>{const{state,bindings}=setup("demo");bindings.set("c","owner",{targetKind:"company",backend:"codex-cli",modelId:"forbidden-live-backend"});const resolved=bindings.resolveRun("r","worker");assert.equal(resolved.resolution,"demo-mode");assert.equal(resolved.backend,"standalone");assert.equal(resolved.modelId,"phase0-model");state.close();});
test("bindings reject credentials and cross-company members",()=>{const{state,bindings}=setup();assert.throws(()=>bindings.set("c","owner",{targetKind:"company",backend:"openai-compatible",modelId:"x",config:{apiKey:"secret"}}),/Credentials/);assert.throws(()=>bindings.set("c","owner",{targetKind:"member",targetId:"outside",backend:"codex-cli",modelId:"x"}),/outside company/);state.close();});
test("RolePipeline routes planner, worker, and reviewer through the frozen binding snapshot",async()=>{const{state,bindings}=setup();bindings.set("c","owner",{targetKind:"company",backend:"openai-compatible",modelId:"company-model"});bindings.set("c","owner",{targetKind:"role",targetId:"reviewer",backend:"claude-cli",modelId:"review-model"});bindings.set("c","owner",{targetKind:"member",targetId:"worker-agent",backend:"codex-cli",modelId:"worker-model"});const controller=new RunController(state,{async enqueue(){},async remove(){return false;}}),hosts=new Map<string,StandaloneHostAdapter>(),router={resolve(runId:string,role:"planner"|"worker"|"reviewer"){const selected=bindings.resolveRun(runId,role);let host=hosts.get(selected.backend);if(!host){host=new StandaloneHostAdapter(undefined,selected.backend);hosts.set(selected.backend,host);}return{host,model:selected.modelId};}},pipeline=new RolePipeline(state,controller,new StandaloneHostAdapter(),undefined,undefined,"fallback",router);await pipeline.process("r");pipeline.approvePlan("r","owner");await pipeline.process("r");await pipeline.review("r",[{kind:"test",passed:true}]);const calls=state.db.prepare("SELECT role,output FROM model_calls WHERE run_id='r' ORDER BY created_at").all() as Array<{role:string;output:string}>,routed=Object.fromEntries(calls.map(call=>{const output=JSON.parse(call.output) as {hostId:string;model:string};return[call.role,{host:output.hostId,model:output.model}];}));assert.deepEqual(routed,{planner:{host:"openai-compatible",model:"company-model"},worker:{host:"codex-cli",model:"worker-model"},reviewer:{host:"claude-cli",model:"review-model"}});state.close();});

test("RolePipeline preserves estimated usage from an Agent backend",async()=>{const{state}=setup();class EstimatedHost extends StandaloneHostAdapter{override async invokeModel(request:Parameters<StandaloneHostAdapter["invokeModel"]>[0]){return{...await super.invokeModel(request),estimated:true};}}const controller=new RunController(state,{async enqueue(){},async remove(){return false;}}),pipeline=new RolePipeline(state,controller,new EstimatedHost());await pipeline.process("r");pipeline.approvePlan("r","owner");await pipeline.process("r");const usage=state.db.prepare("SELECT estimated FROM usage_records WHERE run_id='r' ORDER BY created_at").all() as Array<{estimated:number}>;assert.ok(usage.length>=2);assert.ok(usage.every(row=>row.estimated===1));const worker=state.tasks("r").find(task=>task.role==="worker")?.output as {estimated?:boolean};assert.equal(worker.estimated,true);state.close();});
