import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { SQLiteStateStore } from "../packages/persistence/src/index.js";
import { RunController } from "../packages/runtime/src/index.js";
import { ApprovalIntegrity } from "../packages/approval/src/index.js";

class FakeQueue { async enqueue() {} async remove() { return false; } }
const hash = (x: string) => createHash("sha256").update(x).digest("hex");
function setup(id: string) { const store = new SQLiteStateStore(":memory:"); store.createRun({ id, requestId: `req-${id}`, goal: "edit", risk: "high", status: "RESULT_APPROVAL_WAITING", budgetLimit: 1, spent: 0, checkpoint: null }); store.createApproval({ id: `${id}:result`, runId: id, kind: "result", status: "PENDING", expectedPatchHash: null }); const integrity = new ApprovalIntegrity(store, new RunController(store, new FakeQueue())); return { store, integrity }; }

test("result approval completes only the exact bound patch", async () => { const { store, integrity } = setup("exact"); const expected = hash("patch"); integrity.bindResult("exact", expected); await integrity.approveResult("exact", expected, "owner"); assert.equal(store.getRun("exact")?.status, "COMPLETED"); store.close(); });
test("patch mutation after approval request is blocked and audited", async () => { const { store, integrity } = setup("mutated"); integrity.bindResult("mutated", hash("before")); await assert.rejects(integrity.approveResult("mutated", hash("after"), "owner"), /changed/); assert.equal(store.getRun("mutated")?.status, "BLOCKED"); assert.equal(store.db.prepare("SELECT count(*) AS n FROM audit_events WHERE type='PATCH_HASH_BLOCKED'").get()?.n, 1); store.close(); });
test("candidate failure does not consume result approval", async () => { const { store, integrity } = setup("candidate-failure"); const expected = hash("patch"); integrity.bindResult("candidate-failure", expected); await assert.rejects(integrity.approveResult("candidate-failure", expected, "owner", async () => { throw new Error("commit failed"); }), /commit failed/); assert.equal(store.getRun("candidate-failure")?.status, "RESULT_APPROVAL_WAITING"); assert.equal(store.approval("candidate-failure:result")?.status, "PENDING"); store.close(); });
test("stale artifact blocks result approval reuse", async () => { const { store, integrity } = setup("stale"); const expected = hash("patch"), first = store.createArtifactVersion({ logicalId: "code:src/a.ts", parentVersionId: null, runId: "stale", kind: "code", path: "src/a.ts", baseCommit: "a", contentHash: hash("one") }); store.createArtifactVersion({ logicalId: first.logicalId, parentVersionId: first.id, runId: "stale", kind: "code", path: first.path, baseCommit: "b", contentHash: hash("two") }); integrity.bindResult("stale", expected); await assert.rejects(integrity.approveResult("stale", expected, "owner"), /Stale artifacts/); assert.equal(store.getRun("stale")?.status, "BLOCKED"); assert.equal(store.db.prepare("SELECT count(*) AS n FROM audit_events WHERE type='STALE_APPROVAL_BLOCKED'").get()?.n, 1); store.close(); });
test("expired result approval is blocked without consuming approval",async()=>{const{store,integrity}=setup("expired"),expected=hash("patch");integrity.bindResult("expired",expected);store.db.prepare("UPDATE approvals SET expires_at=? WHERE id=?").run("2000-01-01T00:00:00.000Z","expired:result");await assert.rejects(integrity.approveResult("expired",expected,"owner"),/expired/);assert.equal(store.getRun("expired")?.status,"BLOCKED");assert.equal(store.approval("expired:result")?.status,"PENDING");assert.equal(store.db.prepare("SELECT count(*) n FROM audit_events WHERE type='APPROVAL_EXPIRED'").get()?.n,1);store.close();});
