import test from "node:test";
import assert from "node:assert/strict";
import {once} from "node:events";
import {SQLiteStateStore} from "../packages/persistence/src/index.js";
import {ProjectOperations} from "../packages/project-ops/src/index.js";
import {CompanyOperations} from "../packages/company-ops/src/index.js";
import {PlatformOperations} from "../packages/platform-ops/src/index.js";
import {LocalAuth,OperationalStore} from "../packages/operations/src/index.js";
import {RunController} from "../packages/runtime/src/index.js";
import {RunIntakeService} from "../packages/policy/src/index.js";
import {ControlPlaneApi} from "../apps/control-plane/src/index.js";

async function streamUntil(response:Response,pattern:RegExp){assert.ok(response.body);const reader=response.body.getReader(),decoder=new TextDecoder();let text="";try{while(!pattern.test(text)){const {done,value}=await reader.read();if(done)break;text+=decoder.decode(value,{stream:true});}}finally{await reader.cancel();}return text;}

test("POST /api/auth/login works without a prior token and the issued token is usable",async t=>{const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),platform=new PlatformOperations(state.db,state,projects,companies),ops=new OperationalStore(state.db),auth=new LocalAuth(state.db),controller=new RunController(state,new (class{async enqueue(){}async remove(){return false;}})()),intake=new RunIntakeService(state,controller);auth.createUser({username:"admin",password:"textadmin",principalId:"admin",role:"admin",scopes:["*"],companyIds:["*"]});const server=new ControlPlaneApi(state,intake,controller,{approvePlan(){},approveResult(){}},projects,companies,platform,auth,ops).server();server.listen(0,"127.0.0.1");await once(server,"listening");t.after(()=>{server.close();state.close();});const a=server.address();assert.ok(a&&typeof a==="object");const base=`http://127.0.0.1:${a.port}`;const bad=await fetch(`${base}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:"admin",password:"wrong"})});assert.equal(bad.status,400);const ok=await fetch(`${base}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:"admin",password:"textadmin"})});assert.equal(ok.status,200);const login=await ok.json() as {token:string;principalId:string;role:string};assert.equal(login.principalId,"admin");assert.equal(login.role,"admin");const health=await fetch(`${base}/api/health`,{headers:{authorization:`Bearer ${login.token}`}});assert.equal(health.status,200);});

test("secured Control Plane ignores claimed actor and isolates tenant events",async t=>{class Queue{async enqueue(){}async remove(){return false;}}const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),platform=new PlatformOperations(state.db,state,projects,companies),ops=new OperationalStore(state.db),auth=new LocalAuth(state.db),controller=new RunController(state,new Queue()),intake=new RunIntakeService(state,controller);projects.createWorkspace("w","W");projects.createProject({id:"p",workspaceId:"w",name:"P",repoPath:"r",defaultBranch:"main",runtimePath:".",organizationProfile:{},budgetLimit:3},"owner");projects.addMember("p",{id:"owner"},"viewer","viewer");companies.createCompany({id:"a",name:"A",workspaceId:"w",budgetLimit:4,mandatoryReviews:["r"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");companies.createCompany({id:"b",name:"B",workspaceId:"w",budgetLimit:4,mandatoryReviews:["r"],mandatoryApprovals:["result"],allowedTools:["test"]},"b-owner");auth.issue({principalId:"viewer",scopes:["api:read","api:write"],companyIds:["a"]},"viewer-token");auth.issue({principalId:"owner",scopes:["api:read","api:write"],companyIds:["a"]},"owner-token");const server=new ControlPlaneApi(state,intake,controller,{approvePlan(){},approveResult(){}},projects,companies,platform,auth,ops).server();server.listen(0,"127.0.0.1");await once(server,"listening");t.after(()=>{server.close();state.close();});const a=server.address();assert.ok(a&&typeof a==="object");const base=`http://127.0.0.1:${a.port}`,call=(path:string,token?:string,method="GET",body?:unknown)=>fetch(base+path,{method,headers:{...(token?{authorization:`Bearer ${token}`}:{ } as Record<string,string>),...(body?{"content-type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{})});assert.equal((await call("/api/projects/p")).status,400);const spoof=await call("/api/projects/p/budget","viewer-token","POST",{actorId:"owner",limit:2});assert.equal(spoof.status,400);assert.match(await spoof.text(),/Permission denied/);assert.equal((await call("/api/companies/b?actor=b-owner","owner-token")).status,400);const ok=await call("/api/companies/a?actor=wrong","owner-token");assert.equal(ok.status,200);ops.emit({tenantId:"a",aggregateType:"company",aggregateId:"a",type:"TEST",payload:{secret:"a"}});ops.emit({tenantId:"b",aggregateType:"company",aggregateId:"b",type:"TEST",payload:{secret:"b"}});const stream=await call("/api/events?companyId=a","owner-token");const text=await streamUntil(stream,/"type":"legacy\.test"/);assert.match(text,/"companyId":"a"/);assert.match(text,/"eventVersion":2/);assert.doesNotMatch(text,/"companyId":"b"/);assert.ok(auth.audits().length>=2);});

test("SSE stays open, delivers new events, and resumes strictly after the cursor",async t=>{class Queue{async enqueue(){}async remove(){return false;}}const state=new SQLiteStateStore(":memory:"),ops=new OperationalStore(state.db),controller=new RunController(state,new Queue()),intake=new RunIntakeService(state,controller),server=new ControlPlaneApi(state,intake,controller,{approvePlan(){},approveResult(){}},undefined,undefined,undefined,undefined,ops).server();server.listen(0,"127.0.0.1");await once(server,"listening");t.after(()=>{server.closeAllConnections();server.close();state.close();});const address=server.address();assert.ok(address&&typeof address==="object");const base=`http://127.0.0.1:${address.port}`;ops.emit({tenantId:"live",aggregateType:"test",aggregateId:"one",type:"FIRST",eventId:"first",payload:{order:1}});const first=ops.events("live")[0]!;const controllerAbort=new AbortController(),responsePromise=fetch(`${base}/api/events?companyId=live&after=${first.cursor}`,{signal:controllerAbort.signal});setTimeout(()=>ops.emit({tenantId:"live",aggregateType:"test",aggregateId:"two",type:"SECOND",eventId:"second",payload:{order:2}}),50);const text=await streamUntil(await responsePromise,/legacy\.second/);controllerAbort.abort();assert.doesNotMatch(text,/legacy\.first/);assert.match(text,/legacy\.second/);});
