import test from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";
import { CliAgentClient } from "../packages/cli-agent-adapter/src/index.js";
import { ModelClientError } from "../packages/model-adapters/src/index.js";

const fixture=join(process.cwd(),"tests","fixtures","fake-cli.cjs");
const client=(provider:"claude"|"codex",extra:Record<string,unknown>={})=>new CliAgentClient({provider,executable:process.execPath,executableArgsPrefix:[fixture],environment:process.env,...extra});

test("Claude CLI uses print mode with an empty tool allowlist",async()=>{const result=await client("claude").complete({model:"claude-test",prompt:"return text"}),args=JSON.parse(result.text) as string[];assert.deepEqual(args.slice(0,2),["-p","return text"]);assert.ok(args.includes("--tools"));assert.equal(args[args.indexOf("--tools")+1],"");assert.equal(result.estimated,true);});
test("Codex CLI is ephemeral, read-only, and disables autonomous tools",async()=>{const result=await client("codex").complete({model:"codex-test",prompt:"return text"}),args=JSON.parse(result.text) as string[];assert.equal(args[0],"exec");assert.ok(args.includes("--ephemeral"));assert.equal(args[args.indexOf("--sandbox")+1],"read-only");for(const feature of ["shell_tool","apps","browser_use","computer_use","image_generation","enable_mcp_apps"])assert.ok(args.includes(feature));assert.equal(result.cost,0);});
test("Codex CLI receives an output schema for structured role prompts",async()=>{const prompt=JSON.stringify({outputContract:{summary:"string",tasks:[{id:"string",role:"worker",completionCriteria:["string"],validationCommands:["test"]}]}}),result=await client("codex").complete({model:"codex-test",prompt}),args=JSON.parse(result.text) as string[];assert.ok(args.includes("--output-schema"));assert.match(args[args.indexOf("--output-schema")+1]??"",/agent-company-output-.*\.json$/);});
test("CLI adapter maps missing binary and unauthenticated session",async()=>{await assert.rejects(new CliAgentClient({provider:"claude",executable:join(process.cwd(),"missing-cli.exe")}).complete({model:"x",prompt:"x"}),error=>error instanceof ModelClientError&&error.code==="CAPABILITY_UNAVAILABLE");await assert.rejects(client("codex").complete({model:"x",prompt:"AUTH_FAIL"}),error=>error instanceof ModelClientError&&error.code==="AUTHENTICATION_FAILED");});
test("CLI adapter enforces timeout, output bound, and cancellation",async()=>{await assert.rejects(client("codex",{timeoutMs:50}).complete({model:"x",prompt:"SLOW authentication policy"}),error=>error instanceof ModelClientError&&error.code==="HOST_UNAVAILABLE");await assert.rejects(client("codex",{maxOutputBytes:100}).complete({model:"x",prompt:"LARGE"}),error=>error instanceof ModelClientError&&error.code==="HOST_UNAVAILABLE");const controller=new AbortController(),promise=client("codex").complete({model:"x",prompt:"SLOW",signal:controller.signal});controller.abort();await assert.rejects(promise,error=>error instanceof Error&&error.name==="AbortError");});
test("long prompts use stdin instead of the Windows command line",async()=>{const prompt="context:"+"x".repeat(9000);for(const provider of ["claude","codex"] as const){const result=await client(provider).complete({model:"x",prompt}),seen=JSON.parse(result.text) as {args:string[];stdinLength:number;tail:string};assert.equal(seen.stdinLength,prompt.length);assert.equal(seen.tail,"xxxxxxxx");assert.ok(provider==="claude"?!seen.args.includes(prompt):seen.args.at(-1)==="-");}});
