import test from "node:test";
import assert from "node:assert/strict";
import {once} from "node:events";
import {SQLiteStateStore} from "../packages/persistence/src/index.js";
import {ProjectOperations} from "../packages/project-ops/src/index.js";
import {CompanyOperations} from "../packages/company-ops/src/index.js";
import {RunController} from "../packages/runtime/src/index.js";
import {RunIntakeService} from "../packages/policy/src/index.js";
import {ControlPlaneApi} from "../apps/control-plane/src/index.js";
class Queue{async enqueue(){}async remove(){return false;}}
test("Company Command Center API drives organization, portfolio, review meeting, briefing and owner policy",async t=>{const store=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(store.db,store),companies=new CompanyOperations(store.db,store,projects),controller=new RunController(store,new Queue()),intake=new RunIntakeService(store,controller);projects.createWorkspace("w","W");projects.createProject({id:"p",workspaceId:"w",name:"P",repoPath:"r",defaultBranch:"main",runtimePath:"x",organizationProfile:{},budgetLimit:4},"owner");projects.createTask({id:"t",projectId:"p",milestoneId:null,title:"T",status:"ready",priority:1,completionCriteria:["done"],budgetLimit:3},{id:"owner"});store.createRun({id:"r",requestId:"q",goal:"g",risk:"high",status:"RESULT_APPROVAL_WAITING",budgetLimit:3,spent:0,checkpoint:null});projects.linkRun("t","r",{id:"owner"});const artifact=store.createArtifactVersion({logicalId:"code:x",parentVersionId:null,runId:"r",kind:"code",path:"src/x.ts",baseCommit:"base",contentHash:"a".repeat(64)});
 const server=new ControlPlaneApi(store,intake,controller,{approvePlan(){},approveResult(){}},projects,companies).server();server.listen(0,"127.0.0.1");await once(server,"listening");t.after(()=>{server.close();store.close();});const a=server.address();assert.ok(a&&typeof a==="object");const base=`http://127.0.0.1:${a.port}`,post=(path:string,body:unknown)=>fetch(base+path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const html=await(await fetch(base)).text();assert.match(html,/Company Command Center/);assert.match(html,/Owner Console/);assert.match(html,/CEO 브리핑/);assert.match(html,/필수 정책/);assert.match(html,/읽기 전용 픽셀 오피스/);assert.match(html,/renderPixel/);
 assert.equal((await post("/api/companies",{id:"c",name:"C",workspaceId:"w",budgetLimit:8,mandatoryReviews:["security"],mandatoryApprovals:["result"],allowedTools:["build","test"],ownerId:"owner"})).status,201);await post("/api/companies/c/departments",{actorId:"owner",id:"d",parentId:null,name:"Engineering",budgetLimit:6});await post("/api/companies/c/members",{actorId:"owner",principalId:"agent",role:"member",departmentId:"d"});await post("/api/companies/c/projects",{actorId:"owner",departmentId:"d",projectId:"p",priority:5});const template=await(await post("/api/companies/c/role-templates",{actorId:"owner",logicalId:"role:worker",departmentId:"d",name:"Worker",responsibility:"implementation",allowedTools:["build","test"],requiredReviews:["security"],requiredApprovals:["result"],completionCriteria:["done"]})).json() as {id:string};await post("/api/companies/c/role-template-bindings",{actorId:"owner",templateId:template.id,targetType:"task",targetId:"t"});
 const review=(reviewerId:string,verdict:string,risks:string[],summary:string)=>post("/api/companies/c/reviews",{actorId:"owner",projectId:"p",runId:"r",reviewerId,verdict,risks,evidenceIds:[artifact.id],summary});await review("security","needs-work",["risk"],"fix");await review("architecture","approve",[],"ok");const meeting=await(await post("/api/companies/c/review-meetings",{actorId:"owner",projectId:"p"})).json() as {conflicts:string[];unresolvedRisks:string[]};assert.ok(meeting.conflicts.length);assert.deepEqual(meeting.unresolvedRisks,["risk"]);const briefing=await(await post("/api/companies/c/briefings",{actorId:"owner"})).json() as {briefingHash:string;provenance:string[]};assert.match(briefing.briefingHash,/^[a-f0-9]{64}$/);assert.ok(briefing.provenance.length>=2);const denied=await post("/api/companies/c/policy",{actorId:"agent",mandatoryReviews:["security"],mandatoryApprovals:["result"],allowedTools:["build"]});assert.equal(denied.status,400);const center=await(await fetch(base+"/api/companies/c?actor=owner")).json() as {portfolio:{totals:{projects:number};snapshotHash:string};meetings:unknown[];briefings:unknown[];recommendations:unknown[];pixel:{readOnly:boolean;stateHash:string};audit:unknown[]};assert.equal(center.portfolio.totals.projects,1);assert.equal(center.meetings.length,1);assert.equal(center.briefings.length,1);assert.equal(center.recommendations.length,1);assert.equal(center.pixel.readOnly,true);assert.match(center.pixel.stateHash,/^[a-f0-9]{64}$/);assert.ok(center.audit.length>=8);});
