import test from "node:test";
import assert from "node:assert/strict";
import {mkdtempSync,rmSync} from "node:fs";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {SQLiteStateStore} from "../packages/persistence/src/index.js";
import {ProjectOperations} from "../packages/project-ops/src/index.js";
import {CompanyOperations,CompanyRunGovernance} from "../packages/company-ops/src/index.js";
import {RunController} from "../packages/runtime/src/index.js";
import {RolePipeline} from "../packages/role-pipeline/src/index.js";
import {StandaloneHostAdapter} from "../apps/standalone-host/src/index.js";

test("Phase 4 company lineage, governance, portfolio, reviews, briefing and pixel state survive restart",()=>{
 const root=mkdtempSync(join(tmpdir(),"agent-company-v4-")),db=join(root,"state.sqlite");try{let store=new SQLiteStateStore(db),projects=new ProjectOperations(store.db,store),companies=new CompanyOperations(store.db,store,projects);const owner="owner";
 projects.createWorkspace("ws","Workspace");projects.createProject({id:"p",workspaceId:"ws",name:"Project",repoPath:"D:/repo",defaultBranch:"main",runtimePath:"D:/run",organizationProfile:{management_depth:2},budgetLimit:6},owner);projects.createMilestone({id:"m",projectId:"p",title:"M",status:"active",completionCriteria:["done"],budgetLimit:5,dueAt:null},{id:owner});projects.createTask({id:"t",projectId:"p",milestoneId:"m",title:"Task",status:"ready",priority:2,completionCriteria:["tested"],budgetLimit:4},{id:owner});store.createRun({id:"r",requestId:"q",goal:"goal",risk:"high",status:"RESULT_APPROVAL_WAITING",budgetLimit:4,spent:1,checkpoint:null});projects.linkRun("t","r",{id:owner});store.createApproval({id:"r:result",runId:"r",kind:"result",status:"PENDING",expectedPatchHash:"a".repeat(64)});const artifact=store.createArtifactVersion({logicalId:"code:src/a.ts",parentVersionId:null,runId:"r",kind:"code",path:"src/a.ts",baseCommit:"base",contentHash:"b".repeat(64)});
 companies.createCompany({id:"c",name:"Company",workspaceId:"ws",budgetLimit:10,mandatoryReviews:["security"],mandatoryApprovals:["result"],allowedTools:["build","test","security"]},owner);companies.createDepartment({id:"engineering",companyId:"c",parentId:null,name:"Engineering",budgetLimit:8},owner);companies.createDepartment({id:"platform",companyId:"c",parentId:"engineering",name:"Platform",budgetLimit:7},owner);assert.throws(()=>companies.moveDepartment("engineering","platform",owner),/cycle/);companies.addMember("c",owner,"agent-a","member","platform");companies.addMember("c",owner,"reviewer-a","member","platform");companies.linkProject("c","platform","p",10,owner);assert.throws(()=>companies.setCompanyStatus("c",owner,"archived"),/active Run/);
 const template1=companies.createRoleTemplate({logicalId:"role:secure-worker",companyId:"c",departmentId:"platform",name:"Secure Worker",responsibility:"implementation",allowedTools:["build","test"],requiredReviews:["security"],requiredApprovals:["result"],completionCriteria:["checks pass"]},owner),template2=companies.createRoleTemplate({logicalId:"role:secure-worker",companyId:"c",departmentId:"platform",name:"Secure Worker v2",responsibility:"implementation",allowedTools:["build","test","security"],requiredReviews:["security"],requiredApprovals:["result"],completionCriteria:["checks pass","security pass"]},owner);assert.equal(template2.version,2);assert.equal(template2.parentVersionId,template1.id);companies.bindRoleTemplate("c",template2.id,"project","p",owner);companies.setProjectPriority("c","p",20,owner);assert.equal(companies.setDepartmentBudget("platform",7.5,owner).budgetLimit,7.5);assert.throws(()=>companies.setDepartmentBudget("platform",5,owner),/violates/);assert.throws(()=>companies.createRoleTemplate({logicalId:"bad",companyId:"c",departmentId:"platform",name:"Bad",responsibility:"x",allowedTools:["deploy"],requiredReviews:[],requiredApprovals:[],completionCriteria:["x"]},owner),/(governance|escalation)/);assert.throws(()=>companies.updatePolicy("c",owner,{mandatoryReviews:[],mandatoryApprovals:[],allowedTools:["build"]}),/weakened/);
 const base={companyId:"c",projectId:"p",runId:"r",verdict:"needs-work" as const,risks:["security-risk"],evidenceIds:[artifact.id],summary:"fix security"};companies.addReview({...base,reviewerId:"reviewer-a"},owner);companies.addReview({...base,reviewerId:"reviewer-b"},owner);companies.addReview({...base,reviewerId:"reviewer-c",verdict:"approve",risks:[],summary:"acceptable"},owner);const meeting=companies.aggregateReviews("c","p",owner);assert.equal(meeting.duplicates.length,1);assert.ok(meeting.conflicts.length>=2);assert.deepEqual(meeting.unresolvedRisks,["security-risk"]);assert.equal(meeting.recommendation,"needs-work");const changed=store.createArtifactVersion({logicalId:artifact.logicalId,parentVersionId:artifact.id,runId:"r",kind:"code",path:artifact.path,baseCommit:"next",contentHash:"c".repeat(64)});assert.throws(()=>companies.addReview({...base,reviewerId:"late"},owner),/Stale/);assert.ok(changed);
 const portfolio=companies.portfolio("c",owner) as {totals:{projects:number;tasks:number;approvals:number};snapshotHash:string};assert.equal(portfolio.totals.projects,1);assert.equal(portfolio.totals.tasks,1);assert.equal(portfolio.totals.approvals,1);const briefing1=companies.createBriefing("c",owner),briefing2=companies.createBriefing("c",owner);assert.equal(briefing1.briefingHash,briefing2.briefingHash);assert.ok(briefing1.provenance.includes(meeting.id));const pixel1=companies.pixelState("c",owner),pixel2=companies.pixelState("c",owner);assert.equal(pixel1.stateHash,pixel2.stateHash);assert.equal(pixel1.readOnly,true);const recommendations=companies.recommendAssignments("c",owner) as Array<{taskId:string;suggestedAgent:string;requiresApproval:boolean}>;assert.deepEqual(recommendations.map(x=>x.taskId),["t"]);assert.equal(recommendations[0]?.suggestedAgent,"agent-a");assert.equal(recommendations[0]?.requiresApproval,true);assert.ok(JSON.stringify(companies.auditEvents("c")).includes("COMPANY_POLICY_DENIED"));
 store.close();store=new SQLiteStateStore(db);projects=new ProjectOperations(store.db,store);companies=new CompanyOperations(store.db,store,projects);assert.equal(companies.company("c")?.name,"Company");assert.equal(companies.roleTemplates("c").length,2);const restored=companies.commandCenter("c",owner) as {portfolio:{snapshotHash:string};meetings:unknown[];briefings:unknown[];pixel:{stateHash:string}};assert.equal(restored.portfolio.snapshotHash,portfolio.snapshotHash);assert.equal(restored.meetings.length,1);assert.equal(restored.briefings.length,2);assert.equal(restored.pixel.stateHash,pixel1.stateHash);companies.updatePolicy("c",owner,{mandatoryReviews:["security","architecture"],mandatoryApprovals:["result"],allowedTools:["build","test","security"]});assert.deepEqual(companies.recommendAssignments("c",owner),[]);assert.ok(companies.auditEvents("c").length>8);store.close();}finally{rmSync(root,{recursive:true,force:true});}
});

test("company mode defaults to live, accepts demo, and backfills on pre-existing databases",()=>{
 const root=mkdtempSync(join(tmpdir(),"agent-company-mode-")),db=join(root,"state.sqlite"),legacyDb=join(root,"legacy.sqlite");try{
  let store=new SQLiteStateStore(db),projects=new ProjectOperations(store.db,store),companies=new CompanyOperations(store.db,store,projects);
  projects.createWorkspace("w","W");
  companies.createCompany({id:"live-co",name:"Live Co",workspaceId:"w",budgetLimit:2,mandatoryReviews:["r"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");
  companies.createCompany({id:"demo-co",name:"Demo Co",workspaceId:"w",budgetLimit:2,mandatoryReviews:["r"],mandatoryApprovals:["result"],allowedTools:["test"],mode:"demo"},"owner");
  assert.equal(companies.company("live-co")?.mode,"live");
  assert.equal(companies.company("demo-co")?.mode,"demo");
  store.close();
  // Build a separate legacy fixture so renaming a referenced tenant table cannot rewrite newer foreign keys.
  store=new SQLiteStateStore(legacyDb);projects=new ProjectOperations(store.db,store);projects.createWorkspace("legacy-w","Legacy");
  store.db.exec("CREATE TABLE companies_v4(id TEXT PRIMARY KEY,name TEXT NOT NULL,workspace_id TEXT NOT NULL,budget_limit REAL NOT NULL,mandatory_reviews TEXT NOT NULL,mandatory_approvals TEXT NOT NULL,allowed_tools TEXT NOT NULL,created_at TEXT NOT NULL)");
  store.db.prepare("INSERT INTO companies_v4 VALUES(?,?,?,?,?,?,?,?)").run("legacy-co","Legacy Co","legacy-w",2,'["r"]','["result"]','["test"]',new Date().toISOString());
  const columnsBefore=store.db.prepare("PRAGMA table_info(companies_v4)").all() as Array<{name:string}>;
  assert.ok(!columnsBefore.some(c=>c.name==="mode"));
  companies=new CompanyOperations(store.db,store,projects);
  const columnsAfter=store.db.prepare("PRAGMA table_info(companies_v4)").all() as Array<{name:string}>;
  assert.ok(columnsAfter.some(c=>c.name==="mode"));
  assert.equal(companies.company("legacy-co")?.mode,"live");
  store.close();
 }finally{rmSync(root,{recursive:true,force:true});}
});

test("company access and cross-company organization boundaries are enforced",()=>{const store=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(store.db,store),companies=new CompanyOperations(store.db,store,projects);projects.createWorkspace("w","W");companies.createCompany({id:"a",name:"A",workspaceId:"w",budgetLimit:2,mandatoryReviews:["reviewer"],mandatoryApprovals:["result"],allowedTools:["test"]},"a-owner");companies.createCompany({id:"b",name:"B",workspaceId:"w",budgetLimit:2,mandatoryReviews:["reviewer"],mandatoryApprovals:["result"],allowedTools:["test"]},"b-owner");companies.createDepartment({id:"a-dept",companyId:"a",parentId:null,name:"A",budgetLimit:2},"a-owner");assert.throws(()=>companies.addMember("b","b-owner","x","member","a-dept"),/Cross-company/);assert.throws(()=>companies.portfolio("a","outsider"),/permission denied/);assert.ok(companies.auditEvents("a").length>=2);store.close();});

test("company owner can update, archive and restore a company with audit history",()=>{const store=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(store.db,store),companies=new CompanyOperations(store.db,store,projects);projects.createWorkspace("w","W");companies.createCompany({id:"c",name:"Before",workspaceId:"w",budgetLimit:10,mandatoryReviews:["review"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");companies.addMember("c","owner","member","member",null,"agent");const agents=(companies.pixelState("c","owner") as {agents:Array<{principal_id:string;kind:string}>}).agents;assert.equal(agents.find(x=>x.principal_id==="owner")?.kind,"human");assert.equal(agents.find(x=>x.principal_id==="member")?.kind,"agent");const updated=companies.updateCompany("c","owner",{name:"After",budgetLimit:20,mode:"demo"});assert.equal(updated.name,"After");assert.equal(updated.mode,"demo");assert.throws(()=>companies.updateCompany("c","member",{name:"No",budgetLimit:20,mode:"live"}),/permission denied/);assert.equal(companies.setCompanyStatus("c","owner","archived").status,"archived");assert.equal(companies.setCompanyStatus("c","owner","active").status,"active");const audit=JSON.stringify(companies.auditEvents("c"));assert.match(audit,/COMPANY_UPDATED/);assert.match(audit,/COMPANY_ARCHIVED/);assert.match(audit,/COMPANY_RESTORED/);store.close();});

test("company-bound low-risk Run cannot skip its mandatory Reviewer",async()=>{class Queue{async enqueue(){}async remove(){return false;}}const store=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(store.db,store),companies=new CompanyOperations(store.db,store,projects),controller=new RunController(store,new Queue());projects.createWorkspace("w","W");projects.createProject({id:"p",workspaceId:"w",name:"P",repoPath:"r",defaultBranch:"main",runtimePath:"x",organizationProfile:{},budgetLimit:5},"owner");projects.createTask({id:"t",projectId:"p",milestoneId:null,title:"T",status:"ready",priority:1,completionCriteria:["done"],budgetLimit:4},{id:"owner"});companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:6,mandatoryReviews:["security"],mandatoryApprovals:["result"],allowedTools:["build","test","lint","security"]},"owner");companies.createDepartment({id:"d",companyId:"c",parentId:null,name:"D",budgetLimit:5},"owner");companies.linkProject("c","d","p",1,"owner");const template=companies.createRoleTemplate({logicalId:"role",companyId:"c",departmentId:"d",name:"Role",responsibility:"work",allowedTools:["build","test","lint","security"],requiredReviews:["security"],requiredApprovals:["result"],completionCriteria:["done"]},"owner");companies.bindRoleTemplate("c",template.id,"task","t","owner");await controller.create({id:"r",requestId:"q",goal:"g",risk:"low",status:"CREATED",budgetLimit:5,spent:0,checkpoint:null});projects.linkRun("t","r",{id:"owner"});const governance=new CompanyRunGovernance(companies),pipeline=new RolePipeline(store,controller,new StandaloneHostAdapter(),undefined,governance);assert.throws(()=>governance.assertTools("r",["deploy"]),/blocks tools/);assert.ok(JSON.stringify(companies.auditEvents("c")).includes("RUN_POLICY_DENIED"));governance.assertTools("r",["build","test"]);await pipeline.process("r");pipeline.approvePlan("r","owner");await pipeline.process("r");await pipeline.review("r",[{kind:"test",passed:true}]);assert.deepEqual(store.tasks("r").map(x=>x.role),["worker","reviewer"]);assert.equal(store.getRun("r")?.status,"VALIDATING");store.close();});
