import test from "node:test";
import assert from "node:assert/strict";
import {once} from "node:events";
import {SQLiteStateStore} from "../packages/persistence/src/index.js";
import {RunController} from "../packages/runtime/src/index.js";
import {RunIntakeService} from "../packages/policy/src/index.js";
import {ProjectOperations} from "../packages/project-ops/src/index.js";
import {CompanyOperations} from "../packages/company-ops/src/index.js";
import {OperationalStore} from "../packages/operations/src/index.js";
import {ControlPlaneApi} from "../apps/control-plane/src/index.js";

test("delegation API closes create-review-consume path",async t=>{const state=new SQLiteStateStore(":memory:"),controller=new RunController(state,{async enqueue(){},async remove(){return false;}}),intake=new RunIntakeService(state,controller),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),operations=new OperationalStore(state.db);projects.createWorkspace("w","W");companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:20,mandatoryReviews:["review"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");companies.createDepartment({id:"source",companyId:"c",parentId:null,name:"Source",budgetLimit:10},"owner");companies.createDepartment({id:"target",companyId:"c",parentId:null,name:"Target",budgetLimit:10},"owner");companies.addMember("c","owner","source-manager","department-manager","source");companies.addMember("c","owner","target-manager","department-manager","target");companies.addMember("c","owner","target-agent","member","target");const server=new ControlPlaneApi(state,intake,controller,{approvePlan(){},approveResult(){}},projects,companies,undefined,undefined,operations).server();server.listen(0,"127.0.0.1");await once(server,"listening");t.after(()=>{server.close();state.close();});const address=server.address();assert.ok(address&&typeof address==="object");const base=`http://127.0.0.1:${address.port}`,createdResponse=await fetch(`${base}/api/companies/c/delegations`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({actorId:"source-manager",requestId:"api-1",sourceDepartmentId:"source",targetDepartmentId:"target",ownerId:"source-manager",completionCriteria:["accepted"],allowedScope:["docs/**"],evidence:[{id:"e1",provenance:"run:r"}],deadline:new Date(Date.now()+60_000).toISOString()})});assert.equal(createdResponse.status,201);const created=await createdResponse.json() as {id:string;status:string};assert.equal(created.status,"pending-review");const reviewed=await fetch(`${base}/api/companies/c/delegations/${created.id}/review`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({actorId:"target-manager",decision:"approve",assigneeId:"target-agent",reason:"accepted"})});assert.equal(reviewed.status,200);assert.equal((await reviewed.json() as {status:string}).status,"approved");const started=await fetch(`${base}/api/companies/c/delegations/${created.id}/actions/start`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({actorId:"target-agent"})});assert.equal(started.status,200);assert.equal((await started.json() as {status:string}).status,"in-progress");const list=await (await fetch(`${base}/api/companies/c/delegations?actor=target-agent`)).json() as Array<{id:string}>;assert.deepEqual(list.map(x=>x.id),[created.id]);});
