import test from "node:test";
import assert from "node:assert/strict";
import {SQLiteStateStore} from "../packages/persistence/src/index.js";
import {ProjectOperations} from "../packages/project-ops/src/index.js";
import {CompanyOperations} from "../packages/company-ops/src/index.js";
import {OperationalStore} from "../packages/operations/src/index.js";
import {DelegationService} from "../packages/delegation/src/index.js";

function fixture(){const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects);new OperationalStore(state.db);projects.createWorkspace("w","W");companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:20,mandatoryReviews:["review"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");companies.createDepartment({id:"source",companyId:"c",parentId:null,name:"Source",budgetLimit:10},"owner");companies.createDepartment({id:"target",companyId:"c",parentId:null,name:"Target",budgetLimit:10},"owner");companies.addMember("c","owner","source-manager","department-manager","source");companies.addMember("c","owner","target-manager","department-manager","target");companies.addMember("c","owner","target-agent","member","target");companies.addMember("c","owner","outsider","member","source");return{state,companies,delegations:new DelegationService(state.db,companies)};}
const request=()=>({requestId:"request-1",companyId:"c",sourceDepartmentId:"source",targetDepartmentId:"target",ownerId:"source-manager",completionCriteria:["tests pass","handoff accepted"],allowedScope:["src/**"],evidence:[{id:"artifact-1",provenance:"run:r1",contentHash:"abc"}],deadline:new Date(Date.now()+60_000).toISOString()});

test("cross-department delegation snapshots contract and is idempotent",()=>{const{state,delegations}=fixture(),first=delegations.create(request(),"source-manager"),again=delegations.create(request(),"source-manager");assert.equal(first.id,again.id);assert.equal(first.status,"pending-review");assert.equal(first.ownerId,"source-manager");assert.deepEqual(first.evidence,[{id:"artifact-1",provenance:"run:r1",contentHash:undefined,trust:"untrusted-evidence",sha256:"abc"}].map(({contentHash:_,...x})=>x));assert.ok(first.snapshotHash);assert.equal(state.db.prepare("SELECT COUNT(*) n FROM delegations_v17").get()?.n,1);state.close();});

test("target department manager review and assignee transitions enforce evidence",()=>{const{state,delegations}=fixture(),item=delegations.create(request(),"source-manager");assert.throws(()=>delegations.review("c",item.id,"source-manager",{decision:"approve",assigneeId:"target-agent",reason:"ok"}),/Target department manager/);assert.throws(()=>delegations.review("c",item.id,"target-manager",{decision:"approve",assigneeId:"outsider",reason:"ok"}),/target department/);const approved=delegations.review("c",item.id,"target-manager",{decision:"approve",assigneeId:"target-agent",reason:"capacity confirmed"});assert.equal(approved.status,"approved");assert.equal(delegations.act("c",item.id,"target-agent",{action:"start"}).status,"in-progress");assert.throws(()=>delegations.act("c",item.id,"target-agent",{action:"complete",evidenceIds:["validation:1"],completedCriteria:["tests pass"]}),/incomplete/);assert.equal(delegations.act("c",item.id,"target-agent",{action:"partial",evidenceIds:["validation:1"]}).status,"partially-completed");const complete=delegations.act("c",item.id,"target-agent",{action:"complete",evidenceIds:["validation:1","acceptance:1"],completedCriteria:["handoff accepted","tests pass"]});assert.equal(complete.status,"completed");assert.deepEqual(complete.completionEvidenceIds,["acceptance:1","validation:1"]);assert.match(JSON.stringify(state.db.prepare("SELECT type,payload FROM company_audit_v4").all()),/DELEGATION_TRANSITIONED/);state.close();});

test("rejection, reassignment, partial failure and expiry are explicit",()=>{const{state,delegations}=fixture(),rejected=delegations.create({...request(),requestId:"reject"},"source-manager");assert.equal(delegations.review("c",rejected.id,"target-manager",{decision:"reject",reason:"no capacity"}).status,"rejected");const active=delegations.create({...request(),requestId:"active"},"source-manager");delegations.review("c",active.id,"target-manager",{decision:"approve",assigneeId:"target-agent",reason:"ok"});assert.equal(delegations.act("c",active.id,"target-manager",{action:"reassign",assigneeId:"target-agent",reason:"rotation"}).status,"reassigned");delegations.act("c",active.id,"target-agent",{action:"start"});assert.equal(delegations.act("c",active.id,"target-agent",{action:"fail",evidenceIds:["error:1"],reason:"handoff contract mismatch"}).status,"handoff-failed");const expiring=delegations.create({...request(),requestId:"expire"},"source-manager");assert.equal(delegations.expireDue("c",new Date(Date.now()+120_000).toISOString()),1);assert.equal(delegations.get(expiring.id)?.status,"expired");state.close();});

test("tenant, source authority, scope and provenance fail closed",()=>{const{state,delegations}=fixture();assert.throws(()=>delegations.create({...request(),requestId:"same",sourceDepartmentId:"target",targetDepartmentId:"target"},"source-manager"),/different departments/);assert.throws(()=>delegations.create({...request(),requestId:"authority"},"outsider"),/authority denied/);assert.throws(()=>delegations.create({...request(),requestId:"scope",allowedScope:[]},"source-manager"),/scope required/);assert.throws(()=>delegations.create({...request(),requestId:"evidence",evidence:[{id:"x",provenance:""}]},"source-manager"),/provenance required/);state.close();});
