import test from "node:test";
import assert from "node:assert/strict";
import { SQLiteStateStore } from "../packages/persistence/src/index.js";
import { ProjectOperations } from "../packages/project-ops/src/index.js";
import { CompanyOperations } from "../packages/company-ops/src/index.js";
import { OperationalStore } from "../packages/operations/src/index.js";
import { RunController } from "../packages/runtime/src/index.js";

class Queue{async enqueue(){}async remove(){return false;}}
test("linking a project backfills audit events that predate the company relationship",async()=>{const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),operations=new OperationalStore(state.db),controller=new RunController(state,new Queue());projects.createWorkspace("w","W");projects.createProject({id:"p",workspaceId:"w",name:"P",repoPath:".",defaultBranch:"main",runtimePath:".",organizationProfile:{},budgetLimit:3},"owner");projects.createTask({id:"t",projectId:"p",milestoneId:null,title:"T",status:"ready",priority:1,completionCriteria:["done"],budgetLimit:2},{id:"owner"});await controller.create({id:"r",requestId:"q",goal:"g",risk:"low",status:"CREATED",budgetLimit:2,spent:0,checkpoint:null});projects.linkRun("t","r",{id:"owner"});assert.equal(operations.events("c").length,0);companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:4,mandatoryReviews:["review"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");companies.createDepartment({id:"d",companyId:"c",parentId:null,name:"D",budgetLimit:3},"owner");companies.linkProject("c","d","p",1,"owner");const events=operations.events("c");assert.ok(events.some(x=>x.type==="RUN_CREATED"&&x.aggregateId==="r"));assert.ok(events.some(x=>x.type==="BOARD_TASK_CREATED"&&x.aggregateId==="p"));const count=events.length;new OperationalStore(state.db);assert.equal(operations.events("c").length,count);state.close();});

test("OperationalStore startup backfills events for relationships created before event storage",async()=>{const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),controller=new RunController(state,new Queue());projects.createWorkspace("w","W");projects.createProject({id:"p",workspaceId:"w",name:"P",repoPath:".",defaultBranch:"main",runtimePath:".",organizationProfile:{},budgetLimit:3},"owner");projects.createTask({id:"t",projectId:"p",milestoneId:null,title:"T",status:"ready",priority:1,completionCriteria:["done"],budgetLimit:2},{id:"owner"});await controller.create({id:"r",requestId:"q",goal:"g",risk:"low",status:"CREATED",budgetLimit:2,spent:0,checkpoint:null});projects.linkRun("t","r",{id:"owner"});companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:4,mandatoryReviews:["review"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");companies.createDepartment({id:"d",companyId:"c",parentId:null,name:"D",budgetLimit:3},"owner");companies.linkProject("c","d","p",1,"owner");const operations=new OperationalStore(state.db);assert.ok(operations.events("c").some(x=>x.type==="RUN_CREATED"));assert.ok(operations.events("c").some(x=>x.type==="PROJECT_LINKED"));state.close();});
