import test from "node:test";
import assert from "node:assert/strict";
import { SQLiteStateStore } from "../packages/persistence/src/index.js";
import { ProjectOperations } from "../packages/project-ops/src/index.js";
import { CompanyOperations } from "../packages/company-ops/src/index.js";
import { OperationalStore } from "../packages/operations/src/index.js";
import { DemoScenarioService } from "../packages/demo-scenario/src/index.js";
import { GameProgressionStore } from "../packages/game-progression/src/index.js";

test("reward ledger pays completion once, separates mode and rebuilds deterministically",()=>{const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),operations=new OperationalStore(state.db),scenarios=new DemoScenarioService(state.db,operations);companies.bootstrapDemo("owner");const scenario=scenarios.start({requestId:"reward-demo",goal:"Deliver safely",requestedBy:"owner"}),game=new GameProgressionStore(state.db,operations),first=game.catchUp("demo-company","demo"),again=game.catchUp("demo-company","demo");assert.equal(first.companyXp,23);assert.equal(first.agents[0]?.agentId,"demo-developer");assert.deepEqual(first.achievements,["first-delivery"]);assert.equal(first.ledger.length,1);assert.deepEqual(first.metrics.provenance.rewardEventIds,[`demo:${scenario.id}:12`]);assert.equal(again.stateHash,first.stateHash);assert.equal(game.snapshot("demo-company","live").companyXp,0);operations.emit({tenantId:"demo-company",aggregateType:"demo-scenario",aggregateId:scenario.id,type:"WORKFLOW_COMPLETED",eventId:`demo:${scenario.id}:12`,payload:{runId:`demo-run:${scenario.id}`,contributorAgentId:"demo-developer"}});assert.equal(game.catchUp("demo-company","demo").ledger.length,1);assert.equal(game.rebuild("demo-company","demo").stateHash,first.stateHash);state.close();});

test("risk, quality and cost drive skills while safety incidents block all reward",()=>{const state=new SQLiteStateStore(":memory:"),operations=new OperationalStore(state.db);state.createRun({id:"safe",requestId:"safe-q",goal:"safe delivery",risk:"high",status:"COMPLETED",budgetLimit:10,spent:2,checkpoint:null});state.recordValidation("safe","test",true,"ok");operations.emit({tenantId:"live-company",aggregateType:"run",aggregateId:"safe",type:"VALIDATION_COMPLETED",eventId:"safe-validation",payload:{runId:"safe",passed:true,agentId:"qa"}});operations.emit({tenantId:"live-company",aggregateType:"run",aggregateId:"safe",type:"WORKFLOW_COMPLETED",eventId:"safe-complete",payload:{runId:"safe",contributorAgentId:"developer"}});state.createRun({id:"unsafe",requestId:"unsafe-q",goal:"unsafe delivery",risk:"critical",status:"COMPLETED",budgetLimit:10,spent:1,checkpoint:null});operations.emit({tenantId:"live-company",aggregateType:"run",aggregateId:"unsafe",type:"SCOPE_BLOCKED",eventId:"unsafe-scope",payload:{runId:"unsafe",path:"../secret"}});operations.emit({tenantId:"live-company",aggregateType:"run",aggregateId:"unsafe",type:"WORKFLOW_COMPLETED",eventId:"unsafe-complete",payload:{runId:"unsafe",contributorAgentId:"developer"}});const game=new GameProgressionStore(state.db,operations),first=game.catchUp("live-company","live");assert.equal(first.companyXp,32);assert.equal(first.ledger.length,1);assert.deepEqual(first.agents[0]?.skills,{delivery:20,quality:5,efficiency:3,risk:4});assert.deepEqual(first.achievements,["efficient-delivery","first-delivery","quality-delivery"]);assert.equal(first.metrics.completedRuns,2);assert.equal(first.metrics.qualityPasses,1);assert.equal(first.metrics.incidents,1);assert.deepEqual(first.metrics.provenance.incidentEventIds,["unsafe-scope"]);assert.equal(first.incidents[0]?.severity,"critical");assert.equal(first.briefings.find(x=>x.runId==="unsafe")?.reward,0);assert.match(first.briefings.find(x=>x.runId==="unsafe")?.summary??"",/reward was blocked/);assert.equal(game.rebuild("live-company","live").stateHash,first.stateHash);state.close();});

test("company progression reaches level five and unlocks the executive floor",()=>{const state=new SQLiteStateStore(":memory:"),operations=new OperationalStore(state.db);for(let i=1;i<=20;i++)operations.emit({tenantId:"growth",aggregateType:"run",aggregateId:`r${i}`,type:"WORKFLOW_COMPLETED",eventId:`complete-${String(i).padStart(2,"0")}`,payload:{runId:`r${i}`,contributorAgentId:"builder"}});const game=new GameProgressionStore(state.db,operations).catchUp("growth","live");assert.equal(game.companyXp,500);assert.equal(game.level,5);assert.ok(game.unlocks.includes("executive-floor"));assert.equal(game.metrics.completedRuns,20);state.close();});
