import test from "node:test";
import assert from "node:assert/strict";
import { once } from "node:events";
import { SQLiteStateStore } from "../packages/persistence/src/index.js";
import { RunController } from "../packages/runtime/src/index.js";
import { RunIntakeService } from "../packages/policy/src/index.js";
import { ProjectOperations } from "../packages/project-ops/src/index.js";
import { CompanyOperations } from "../packages/company-ops/src/index.js";
import { ControlPlaneApi } from "../apps/control-plane/src/index.js";

class Queue {
  jobs: Array<{runId:string;requestId:string}>=[];
  async enqueue(job:{runId:string;requestId:string}){this.jobs.push(job);}
  async remove(){return false;}
}

test("goal launch API provisions a visible project, team, task and queued Run",async t=>{
  const state=new SQLiteStateStore(":memory:"),queue=new Queue(),controller=new RunController(state,queue as never),intake=new RunIntakeService(state,controller),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects);
  projects.createWorkspace("w","Workspace");companies.createCompany({id:"c",name:"Company",workspaceId:"w",budgetLimit:100,mandatoryReviews:["security"],mandatoryApprovals:["result"],allowedTools:["build","test","security"]},"owner");
  const server=new ControlPlaneApi(state,intake,controller,{approvePlan(){},approveResult(){}},projects,companies).server();server.listen(0,"127.0.0.1");await once(server,"listening");t.after(()=>{server.close();state.close();});const address=server.address();assert.ok(address&&typeof address==="object");
  const response=await fetch(`http://127.0.0.1:${address.port}/api/companies/c/goals/launch`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({actorId:"owner",id:"g",title:"온보딩 자동화",description:"첫 납품",ownerId:"owner",completionCriteria:["검증 통과"],budgetLimit:20,requestedPaths:["src"],requestedRisk:"medium"})});
  assert.equal(response.status,201);const body=await response.json() as any;assert.equal(body.goal.status,"active");assert.equal(body.deliveryProcess.process.currentStage,"discovery");assert.equal(body.deliveryProcess.currentStageInstance.status,"in-progress");assert.equal(body.deliveryProcess.currentStageInstance.runId,body.provisioning.runId);assert.equal(body.snapshot.projects.length,1);assert.equal(body.snapshot.projects[0].tasks.length,1);assert.equal(body.snapshot.projects[0].tasks[0].assignments.length,2);assert.equal(body.snapshot.projects[0].tasks[0].run.id,body.provisioning.runId);assert.equal(companies.members("c","owner").filter(x=>x.kind==="agent").length,2);assert.deepEqual(queue.jobs,[{runId:body.provisioning.runId,requestId:"goal-launch:g"}]);
  const deliveryResponse=await fetch(`http://127.0.0.1:${address.port}/api/companies/c/goals/g/delivery-process?actor=owner`);assert.equal(deliveryResponse.status,200);const delivery=await deliveryResponse.json() as any;assert.equal(delivery.process.id,body.deliveryProcess.process.id);
  const transitionResponse=await fetch(`http://127.0.0.1:${address.port}/api/companies/c/goals/g/delivery-process/actions/transition`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({actorId:"owner",stageInstanceId:delivery.currentStageInstance.id,to:"validation-waiting",expectedVersion:delivery.process.version,idempotencyKey:"api-transition"})});assert.equal(transitionResponse.status,200);const transitioned=await transitionResponse.json() as any;assert.equal(transitioned.currentStageInstance.status,"validation-waiting");
  const artifactResponse=await fetch(`http://127.0.0.1:${address.port}/api/companies/c/goals/g/delivery-process/stages/${encodeURIComponent(transitioned.currentStageInstance.id)}/artifacts`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({actorId:"owner",id:"api-evidence",artifactIds:["run:"+body.provisioning.runId],expectedVersion:transitioned.process.version,idempotencyKey:"api-artifact"})});assert.equal(artifactResponse.status,201);const withEvidence=await artifactResponse.json() as any;assert.equal(withEvidence.artifactSnapshots[0].artifactIds[0],"run:"+body.provisioning.runId);
  companies.createGoal({id:"legacy",companyId:"c",title:"기존 목표",description:"",ownerId:"owner",completionCriteria:["완료"],budgetLimit:10,dueAt:null,status:"draft"},"owner");const provisioned=await fetch(`http://127.0.0.1:${address.port}/api/companies/c/goals/legacy/actions/provision`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({actorId:"owner",requestedPaths:["src"]})});assert.equal(provisioned.status,201);const legacy=await provisioned.json() as any;assert.equal(legacy.goal.status,"active");assert.equal(legacy.deliveryProcess.process.currentStage,"discovery");assert.equal(legacy.deliveryProcess.currentStageInstance.runId,legacy.provisioning.runId);assert.equal(legacy.provisioning.backfilled,true);assert.equal(legacy.snapshot.projects[0].tasks[0].assignments.length,2);assert.equal(queue.jobs[1]!.requestId,"goal-provision:legacy");
});

test("legacy goal provisioning reuses its existing project, assigned team, Task and Run",async t=>{
  const state=new SQLiteStateStore(":memory:"),queue=new Queue(),controller=new RunController(state,queue as never),intake=new RunIntakeService(state,controller),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects);
  projects.createWorkspace("w","Workspace");projects.createProject({id:"p",workspaceId:"w",name:"Existing",repoPath:".",defaultBranch:"main",runtimePath:".",organizationProfile:{},budgetLimit:20},"owner");companies.createCompany({id:"c",name:"Company",workspaceId:"w",budgetLimit:100,mandatoryReviews:["security"],mandatoryApprovals:["result"],allowedTools:["build","test","security"]},"owner");companies.createDepartment({id:"d",companyId:"c",parentId:null,name:"Delivery",budgetLimit:20},"owner");companies.addMember("c","owner","builder","member","d","agent");companies.addMember("c","owner","reviewer","member","d","agent");companies.linkProject("c","d","p",1,"owner");companies.createGoal({id:"g",companyId:"c",title:"Legacy",description:"",ownerId:"owner",completionCriteria:["done"],budgetLimit:20,dueAt:null,status:"active"},"owner");companies.linkGoalProject("c","g","p","owner");projects.createTask({id:"t",projectId:"p",milestoneId:null,title:"Existing task",status:"ready",priority:1,completionCriteria:["done"],budgetLimit:20},{id:"owner"});state.createRun({id:"r",requestId:"legacy-run",goal:"Legacy",risk:"medium",status:"CREATED",budgetLimit:20,spent:0,checkpoint:{requestedPaths:["src"]}});projects.linkRun("t","r",{id:"owner"});projects.assign("t",{id:"owner"},"builder","agent","executor");projects.assign("t",{id:"owner"},"reviewer","agent","reviewer");
  const server=new ControlPlaneApi(state,intake,controller,{approvePlan(){},approveResult(){}},projects,companies).server();server.listen(0,"127.0.0.1");await once(server,"listening");t.after(()=>{server.close();state.close();});const address=server.address();assert.ok(address&&typeof address==="object");const response=await fetch(`http://127.0.0.1:${address.port}/api/companies/c/goals/g/actions/provision`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({actorId:"owner",requestedPaths:["src"]})});assert.equal(response.status,201);const body=await response.json() as any;assert.equal(body.provisioning.reused,true);assert.equal(body.provisioning.projectId,"p");assert.equal(body.provisioning.taskId,"t");assert.equal(body.provisioning.runId,"r");assert.equal(body.deliveryProcess.currentStageInstance.runId,"r");assert.equal((companies.goalSnapshot("c","g","owner") as any).projects.length,1);assert.deepEqual(queue.jobs,[{runId:"r",requestId:"legacy-run"}]);
});
