import test from "node:test";
import assert from "node:assert/strict";
import {SQLiteStateStore} from "../packages/persistence/src/index.js";
import {ProjectOperations} from "../packages/project-ops/src/index.js";
import {CompanyOperations} from "../packages/company-ops/src/index.js";
import {AgentBindingStore} from "../packages/agent-bindings/src/index.js";
import {MeetingAgentRunner,MeetingSimulatedCrash,type MeetingRunnerLimits} from "../packages/meeting-runner/src/index.js";
import type {HostAdapter} from "../packages/host-adapter-sdk/src/index.js";

const limits=():MeetingRunnerLimits=>({maxTokens:1000,maxCost:10,maxRounds:3,deadline:new Date(Date.now()+60_000).toISOString(),maxTokensPerTurn:100,maxCostPerTurn:1,maxRetries:1,leaseMs:100,maxOutputBytes:1000});
function fixture(providerIdempotent=true){const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects);projects.createWorkspace("w","W");companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:20,mandatoryReviews:["review"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");companies.createDepartment({id:"d",companyId:"c",parentId:null,name:"D",budgetLimit:20},"owner");companies.addMember("c","owner","agent-a","member","d");companies.addMember("c","owner","agent-b","member","d");companies.addMember("c","owner","human","member","d","human");companies.createMeeting({id:"m",companyId:"c",goalId:null,projectId:null,runId:null,title:"Release",purpose:"Decide readiness",hostId:"owner",participantIds:["agent-a","agent-b","human"],agenda:["readiness"],scheduledAt:null},"owner");companies.transitionMeeting("c","m","live","owner");const bindings=new AgentBindingStore(state.db,companies,{host:"standalone",model:"model",baseUrl:null}),calls:{count:number;prompts:string[]}={count:0,prompts:[]},host:HostAdapter={hostId:"fake",async capabilities(){return{auth:false,models:true,usage:true,events:false,streamingAbort:false}},async authenticate(){return{userId:"x",roles:[]}},async listModels(){return[]},async invokeModel(request){calls.count++;calls.prompts.push(request.prompt);return{requestId:request.requestId,text:JSON.stringify({kind:"opinion",content:"Readiness evidence is incomplete.",evidenceIds:["m"],uncertainty:"Validation is pending",escalation:true}),tokens:20,cost:.2}},async recordUsage(){},async publishEvent(){}};const router={resolve(){return host},providerIdempotent(){return providerIdempotent}};return{state,companies,bindings,calls,router};}

test("runner snapshots only actual Agent participants and projects one provenance message per turn",async()=>{const{state,companies,bindings,calls,router}=fixture(),runner=new MeetingAgentRunner(state.db,companies,bindings,router),initialized=runner.initialize("m",limits());assert.deepEqual(initialized.turns.map(x=>x.participantId),["agent-a","agent-b"]);assert.equal(bindings.meetingSnapshots("m").length,2);const first=await runner.runNext("m","worker-1");assert.equal(first?.status,"completed");assert.equal(first?.dispatchState,"projected");assert.ok(first?.promptHash);assert.equal(calls.count,1);assert.equal(companies.meetingMessages("m").length,1);assert.equal(state.db.prepare("SELECT COUNT(*) n FROM meeting_agent_message_provenance_v18").get()?.n,1);assert.equal(await runner.runNext("m","worker-1").then(x=>x?.status),"completed");assert.equal(calls.count,2);assert.equal(companies.meetingMessages("m").length,2);assert.equal(await runner.runNext("m","worker-1"),null);state.close();});

test("backend and organization profile snapshots remain fixed after member and binding changes",()=>{const{state,companies,bindings,router}=fixture();bindings.set("c","owner",{targetKind:"member",targetId:"agent-a",backend:"codex-cli",modelId:"gpt-a"});const runner=new MeetingAgentRunner(state.db,companies,bindings,router),before=runner.initialize("m",limits()),binding=bindings.resolveMeeting("m","agent-a");bindings.set("c","owner",{targetKind:"member",targetId:"agent-a",backend:"claude-cli",modelId:"claude-b"});companies.addMember("c","owner","agent-a","department-manager","d");const after=bindings.resolveMeeting("m","agent-a"),profile=state.db.prepare("SELECT profile FROM meeting_agent_profile_snapshots_v18 WHERE meeting_id='m' AND participant_id='agent-a'").get() as {profile:string};assert.equal(binding.modelId,"gpt-a");assert.equal(after.modelId,"gpt-a");assert.equal(JSON.parse(profile.profile).companyRole,"member");assert.equal(before.meetingSnapshotId,after.meetingSnapshotId);state.close();});

test("non-idempotent sent crash becomes execution-uncertain and requires operator resolution",async()=>{const base=fixture(false);let crash=true;const runner=new MeetingAgentRunner(base.state.db,base.companies,base.bindings,base.router,{afterInvoke(){if(crash){crash=false;throw new MeetingSimulatedCrash("after send")}}});runner.initialize("m",limits());await assert.rejects(()=>runner.runNext("m","worker"),MeetingSimulatedCrash);const turn=runner.turns("m")[0]!;base.state.db.prepare("UPDATE meeting_agent_turns_v18 SET lease_until=? WHERE id=?").run(new Date(Date.now()-1000).toISOString(),turn.id);const recovered=runner.recoverExpired("m");assert.equal(recovered.uncertain,1);assert.equal(runner.get(turn.id)?.status,"execution-uncertain");assert.ok(Number((base.state.db.prepare("SELECT reserved_tokens n FROM meeting_agent_budgets_v18 WHERE meeting_id='m'").get() as {n:number}).n)>0);assert.equal(runner.resolveUncertain(turn.id,"owner","not-executed").status,"pending");assert.equal((base.state.db.prepare("SELECT reserved_tokens n FROM meeting_agent_budgets_v18 WHERE meeting_id='m'").get() as {n:number}).n,0);base.state.close();});

test("result storage crash reprojects without a second model invocation",async()=>{const base=fixture(true);let crash=true;const first=new MeetingAgentRunner(base.state.db,base.companies,base.bindings,base.router,{afterResultStored(){if(crash){crash=false;throw new MeetingSimulatedCrash("projection crash")}}});first.initialize("m",limits());await assert.rejects(()=>first.runNext("m","worker"),MeetingSimulatedCrash);assert.equal(base.calls.count,1);assert.equal(first.turns("m")[0]?.dispatchState,"result-stored");const restarted=new MeetingAgentRunner(base.state.db,base.companies,base.bindings,base.router),completed=await restarted.runNext("m","worker-2");assert.equal(completed?.status,"completed");assert.equal(base.calls.count,1);assert.equal(base.companies.meetingMessages("m").length,1);assert.equal(await restarted.runNext("m","worker-2").then(x=>x?.status),"completed");assert.equal(base.calls.count,2);base.state.close();});

test("pause, budget, round and invented evidence gates stop Agent execution",async()=>{const paused=fixture(),runner=new MeetingAgentRunner(paused.state.db,paused.companies,paused.bindings,paused.router);runner.initialize("m",limits());paused.companies.setMeetingPaused("c","m",true,"owner");assert.equal(await runner.runNext("m","worker"),null);assert.equal(paused.calls.count,0);assert.throws(()=>runner.enqueueRound("m",4),/round limit/);paused.state.close();const budgeted=fixture(),tight={...limits(),maxTokens:50,maxTokensPerTurn:100},budgetRunner=new MeetingAgentRunner(budgeted.state.db,budgeted.companies,budgeted.bindings,budgeted.router);budgetRunner.initialize("m",tight);assert.equal(await budgetRunner.runNext("m","worker"),null);assert.equal(budgeted.companies.meeting("m")?.status,"decision-pending");budgeted.state.close();const invented=fixture(),badHost={...invented.router,resolve:()=>({...invented.router.resolve(),async invokeModel(request:any){invented.calls.count++;return{requestId:request.requestId,text:JSON.stringify({kind:"opinion",content:"Unsupported claim.",evidenceIds:["invented"],uncertainty:null,escalation:false}),tokens:1,cost:0}}})},badRunner=new MeetingAgentRunner(invented.state.db,invented.companies,invented.bindings,badHost);badRunner.initialize("m",limits());assert.equal((await badRunner.runNext("m","worker"))?.status,"failed");assert.equal(invented.companies.meetingMessages("m").length,0);invented.state.close();});

test("a pause immediately before invocation cancels the leased turn without calling the host",async()=>{const base=fixture(),runner=new MeetingAgentRunner(base.state.db,base.companies,base.bindings,base.router,{beforeInvoke(){base.companies.setMeetingPaused("c","m",true,"owner");}});runner.initialize("m",limits());const turn=await runner.runNext("m","worker");assert.equal(turn?.status,"cancelled");assert.equal(turn?.dispatchState,"leased");assert.equal(base.calls.count,0);assert.equal((base.state.db.prepare("SELECT reserved_tokens n FROM meeting_agent_budgets_v18 WHERE meeting_id='m'").get() as {n:number}).n,0);base.state.close();});

test("reported usage above a per-turn limit fails without projecting a message",async()=>{const base=fixture(),router={...base.router,resolve:()=>({...base.router.resolve(),async invokeModel(request:any){base.calls.count++;return{requestId:request.requestId,text:JSON.stringify({kind:"opinion",content:"Within the output contract.",evidenceIds:["m"],uncertainty:null,escalation:false}),tokens:101,cost:.2}}})},runner=new MeetingAgentRunner(base.state.db,base.companies,base.bindings,router);runner.initialize("m",limits());const turn=await runner.runNext("m","worker");assert.equal(turn?.status,"failed");assert.match(turn?.error??"",/usage exceeds per-turn limit/);assert.equal(base.companies.meetingMessages("m").length,0);assert.equal((base.state.db.prepare("SELECT reserved_tokens n FROM meeting_agent_budgets_v18 WHERE meeting_id='m'").get() as {n:number}).n,0);base.state.close();});

test("an automated meeting can raise a mistaken usage limit and retry only those failures",async()=>{const base=fixture(),runner=new MeetingAgentRunner(base.state.db,base.companies,base.bindings,base.router);runner.initialize("m",{...limits(),maxTokensPerTurn:10});assert.equal((await runner.runNext("m","worker"))?.status,"failed");assert.equal(runner.recoverUsageLimitFailures("m",limits()),1);assert.equal((await runner.runNext("m","worker"))?.status,"completed");assert.equal(base.companies.meetingMessages("m").length,1);assert.match(JSON.stringify(base.state.db.prepare("SELECT type FROM company_audit_v4").all()),/MEETING_AGENT_USAGE_LIMIT_RECOVERED/);base.state.close();});

test("a single JSON code fence is normalized but surrounding prose remains invalid",async()=>{const fenced=fixture(),fencedRouter={...fenced.router,resolve:()=>({...fenced.router.resolve(),async invokeModel(request:any){return{requestId:request.requestId,text:'```json\n{"kind":"opinion","content":"Grounded result.","evidenceIds":["m"],"uncertainty":null,"escalation":false}\n```',tokens:10,cost:.1}}})},fencedRunner=new MeetingAgentRunner(fenced.state.db,fenced.companies,fenced.bindings,fencedRouter);fencedRunner.initialize("m",limits());assert.equal((await fencedRunner.runNext("m","worker"))?.status,"completed");fenced.state.close();const prose=fixture(),proseRouter={...prose.router,resolve:()=>({...prose.router.resolve(),async invokeModel(request:any){return{requestId:request.requestId,text:'Result:\n```json\n{"kind":"opinion","content":"Grounded result.","evidenceIds":["m"],"uncertainty":null,"escalation":false}\n```',tokens:10,cost:.1}}})},proseRunner=new MeetingAgentRunner(prose.state.db,prose.companies,prose.bindings,proseRouter);proseRunner.initialize("m",limits());assert.equal((await proseRunner.runNext("m","worker"))?.status,"failed");prose.state.close();});

test("bounded protocol runs at most three rounds and stops at decision-pending",async()=>{const base=fixture(),runner=new MeetingAgentRunner(base.state.db,base.companies,base.bindings,base.router);runner.initialize("m",limits());const result=await runner.runProtocol("m","protocol");assert.equal(result.rounds,3);assert.equal(result.turns.length,6);assert.ok(result.turns.every(x=>x.status==="completed"));assert.equal(result.status,"decision-pending");assert.equal(base.calls.count,6);assert.equal(base.companies.meetingMessages("m").length,6);base.state.close();});
