import test from "node:test";
import assert from "node:assert/strict";
import {once} from "node:events";
import {SQLiteStateStore} from "../packages/persistence/src/index.js";
import {RunController} from "../packages/runtime/src/index.js";
import {RunIntakeService} from "../packages/policy/src/index.js";
import {ProjectOperations} from "../packages/project-ops/src/index.js";
import {CompanyOperations} from "../packages/company-ops/src/index.js";
import {OperationalStore} from "../packages/operations/src/index.js";
import {AgentBindingStore} from "../packages/agent-bindings/src/index.js";
import {MeetingAgentRunner} from "../packages/meeting-runner/src/index.js";
import {ControlPlaneApi} from "../apps/control-plane/src/index.js";

test("Meeting Agent API initializes, executes and exposes a provenance turn",async t=>{const state=new SQLiteStateStore(":memory:"),controller=new RunController(state,{async enqueue(){},async remove(){return false;}}),intake=new RunIntakeService(state,controller),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),operations=new OperationalStore(state.db),bindings=new AgentBindingStore(state.db,companies,{host:"standalone",model:"model",baseUrl:null});projects.createWorkspace("w","W");companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:20,mandatoryReviews:["review"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");companies.createDepartment({id:"d",companyId:"c",parentId:null,name:"D",budgetLimit:20},"owner");companies.addMember("c","owner","agent","member","d");companies.createMeeting({id:"m",companyId:"c",goalId:null,projectId:null,runId:null,title:"T",purpose:"P",hostId:"owner",participantIds:["agent"],agenda:["A"],scheduledAt:null},"owner");companies.transitionMeeting("c","m","live","owner");const host={hostId:"fake",async capabilities(){return{auth:false,models:true,usage:true,events:false,streamingAbort:false}},async authenticate(){return{userId:"x",roles:[]}},async listModels(){return[]},async invokeModel(request:any){return{requestId:request.requestId,text:JSON.stringify({kind:"question",content:"What validation evidence is available?",evidenceIds:["m"],uncertainty:null,escalation:false}),tokens:5,cost:.01}},async recordUsage(){},async publishEvent(){}},runner=new MeetingAgentRunner(state.db,companies,bindings,{resolve(){return host}}),server=new ControlPlaneApi(state,intake,controller,{approvePlan(){},approveResult(){}},projects,companies,undefined,undefined,operations,bindings,runner).server();server.listen(0,"127.0.0.1");await once(server,"listening");t.after(()=>{server.close();state.close();});const address=server.address();assert.ok(address&&typeof address==="object");const base=`http://127.0.0.1:${address.port}`,post=(path:string,body:unknown)=>fetch(`${base}${path}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),initialized=await post("/api/companies/c/meetings/m/agent-turns",{actorId:"owner",limits:{maxTokens:100,maxCost:1,maxRounds:3,deadline:new Date(Date.now()+60_000).toISOString(),maxTokensPerTurn:10,maxCostPerTurn:.1,maxRetries:1,leaseMs:100,maxOutputBytes:1000}});assert.equal(initialized.status,201);const executed=await post("/api/companies/c/meetings/m/agent-turns/run-next",{actorId:"owner"});assert.equal(executed.status,200);assert.equal((await executed.json() as {status:string}).status,"completed");const detail=await (await fetch(`${base}/api/companies/c/meetings/m?actor=owner`)).json() as {messages:unknown[];agentTurns:Array<{status:string}>};assert.equal(detail.messages.length,1);assert.equal(detail.agentTurns[0]?.status,"completed");});
