import test from "node:test";
import assert from "node:assert/strict";
import {SQLiteStateStore} from "../packages/persistence/src/index.js";
import {ProjectOperations} from "../packages/project-ops/src/index.js";
import {CompanyOperations} from "../packages/company-ops/src/index.js";
import {MeetingSemanticSummaryService} from "../packages/meeting-semantics/src/index.js";
import {AgentReportInterpreter} from "../packages/agent-reporting/src/index.js";
import type {DeterministicReport} from "../packages/reporting/src/index.js";

function meetingFixture(){const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects);projects.createWorkspace("w","W");companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:10,mandatoryReviews:["review"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");companies.createMeeting({id:"m",companyId:"c",goalId:null,projectId:null,runId:null,title:"Release",purpose:"Readiness",hostId:"owner",participantIds:[],agenda:["ship"],scheduledAt:null},"owner");companies.transitionMeeting("c","m","live","owner");companies.addMeetingMessage("c","m",{id:"opinion",kind:"opinion",targetType:"agenda",targetId:"ship",content:"Risk remains in validation.",evidence:["validation:1"]},"owner");companies.addMeetingMessage("c","m",{id:"decision",kind:"decision",targetType:"agenda",targetId:"ship",content:"Ship",evidence:["approval:1"]},"owner");companies.transitionMeeting("c","m","ended","owner");return{state,companies};}
function host(text:string|Error){return{hostId:"fake",async capabilities(){return{auth:false,models:true,usage:false,events:false,streamingAbort:false}},async authenticate(){return{userId:"x",roles:[]}},async listModels(){return[]},async invokeModel(request:any){if(text instanceof Error)throw text;return{requestId:request.requestId,text,tokens:10,cost:.1}},async recordUsage(){},async publishEvent(){}};}

test("semantic summary preserves canonical facts and rejects uncited or invented decisions",async()=>{const{state,companies}=meetingFixture(),service=new MeetingSemanticSummaryService(state.db,companies),result=await service.generate("m",{host:host(JSON.stringify({agendaSummaries:[{agenda:"ship",summary:"Validation risk and ship decision were recorded.",evidenceIds:["opinion","decision"]}],positions:[{speakerId:"owner",stance:"Proceed with known risk.",evidenceIds:["opinion"]}],decisionCandidates:[{text:"Ship",evidenceIds:["decision"]},{text:"Invented approval",evidenceIds:["opinion"]}],risks:[{text:"Validation risk",evidenceIds:["opinion"]}],openQuestions:[{text:"No source",evidenceIds:["missing"]}],followUpCandidates:[{title:"Validate",ownerId:"owner",deadline:"2099-01-01",evidenceIds:["opinion"]}]})),backend:"standalone",model:"model",deadline:Date.now()+1000});assert.equal(result.status,"model");const summary=result.summary as any;assert.equal(summary.decisionCandidates.length,1);assert.equal(summary.decisionCandidates[0].text,"Ship");assert.equal(summary.decisionCandidates[0].authority,"candidate-only");assert.equal(summary.openQuestions.length,0);assert.equal(summary.followUpCandidates[0].authority,"candidate-only");assert.match(result.warnings.join(","),/not-canonical-decision/);assert.match(result.warnings.join(","),/invalid-evidence/);assert.equal((companies.meetingSummary("m") as any).decisions[0],"Ship");state.close();});

test("semantic model failure returns the deterministic canonical summary",async()=>{const{state,companies}=meetingFixture(),service=new MeetingSemanticSummaryService(state.db,companies),result=await service.generate("m",{host:host(new Error("offline")),backend:"remote",model:"m",deadline:Date.now()+1000});assert.equal(result.status,"canonical-fallback");assert.deepEqual((result.summary as any).decisions,["Ship"]);assert.match(result.warnings[0]!,/offline/);state.close();});

const report:DeterministicReport={id:"report",companyId:"c",sourceEventId:"event",sourceCursor:1,reportType:"decision",recipientId:"owner",status:"unread",currentState:"APPROVAL_WAITING",completed:[],blocked:[],decisionRequired:true,evidenceIds:["event","run"],nextAction:"Review",routing:{candidates:["owner"],selectedIndex:0,reason:"owner",sourcePrincipalId:null,sourceDepartmentId:null},contractVersion:"deterministic-report-v1",projectorVersion:"v1",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
test("Agent report adds only cited interpretation and falls back without changing deterministic facts",async()=>{const state=new SQLiteStateStore(":memory:"),service=new AgentReportInterpreter(state.db),good=await service.interpret(report,{host:host(JSON.stringify({interpretation:"Approval requires owner attention.",risks:[{text:"Delay",evidenceIds:["event"]},{text:"Invented",evidenceIds:["other"]}],suggestions:[{text:"Review run",evidenceIds:["run"]}],uncertainty:null})),backend:"standalone",model:"m",deadline:Date.now()+1000,rolePerspective:{role:"owner"}});assert.equal(good.status,"model");assert.equal((good.interpretation as any).risks.length,1);assert.equal((good.interpretation as any).deterministicFactsUnchanged,true);const fallback=await service.interpret({...report,id:"fallback"},{host:host(new Error("offline")),backend:"remote",model:"m",deadline:Date.now()+1000,rolePerspective:{role:"owner"}});assert.equal(fallback.status,"deterministic-fallback");assert.equal((fallback.interpretation as any).facts.currentState,report.currentState);state.close();});
