import test from "node:test";
import assert from "node:assert/strict";
import {mkdtempSync,readFileSync,rmSync,writeFileSync} from "node:fs";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {SQLiteStateStore} from "../packages/persistence/src/index.js";
import {ProjectOperations} from "../packages/project-ops/src/index.js";
import {CompanyOperations} from "../packages/company-ops/src/index.js";
import {PlatformOperations} from "../packages/platform-ops/src/index.js";
import {LocalAuth,OperationalStore} from "../packages/operations/src/index.js";
import {LegacyNvidiaHostAdapter} from "../apps/legacy-nvidia-host/src/index.js";

test("local auth hashes tokens and enforces scope, expiry and tenant",()=>{const state=new SQLiteStateStore(":memory:"),auth=new LocalAuth(state.db),issued=auth.issue({principalId:"owner",scopes:["api:read"],companyIds:["a"]},"secret");assert.equal(auth.authenticate("Bearer secret","api:read","a").id,"owner");assert.throws(()=>auth.authenticate("Bearer secret","api:write","a"),/Scope denied/);assert.throws(()=>auth.authenticate("Bearer secret","api:read","b"),/Tenant scope/);assert.throws(()=>auth.authenticate(undefined,"api:read"),/required/);auth.revoke(issued.id);assert.throws(()=>auth.authenticate("Bearer secret","api:read"),/Invalid/);assert.ok(auth.audits().length>=4);state.close();});

test("local username/password login issues a working token and rejects bad credentials",()=>{const state=new SQLiteStateStore(":memory:"),auth=new LocalAuth(state.db);auth.createUser({username:"admin",password:"textadmin",principalId:"admin",role:"admin",scopes:["*"],companyIds:["*"]});const result=auth.login("admin","textadmin");assert.equal(result.principalId,"admin");assert.equal(result.role,"admin");assert.equal(auth.authenticate(`Bearer ${result.token}`,"api:write").id,"admin");assert.throws(()=>auth.login("admin","wrong-password"),/Invalid username or password/);assert.throws(()=>auth.login("nobody","whatever12"),/Invalid username or password/);assert.throws(()=>auth.createUser({username:"short",password:"1234567",principalId:"x",role:"member",scopes:["api:read"],companyIds:["*"]}),/at least 8 characters/);state.close();});

test("durable outbox survives restart, retries and deduplicates delivery",async()=>{const root=mkdtempSync(join(tmpdir(),"ops-outbox-")),path=join(root,"state.sqlite");try{let state=new SQLiteStateStore(path),ops=new OperationalStore(state.db,path);ops.enqueue("usage","usage:q",{requestId:"q",tokens:1});ops.enqueue("usage","usage:q",{requestId:"q",tokens:99});assert.equal(ops.pending().length,1);assert.deepEqual(await ops.flush(async()=>{throw new Error("host down");}),{sent:0,failed:1});assert.equal(ops.outbox("usage:q")?.status,"failed");state.close();state=new SQLiteStateStore(path);ops=new OperationalStore(state.db,path);state.db.prepare("UPDATE outbox_v6 SET next_attempt_at=? WHERE idempotency_key=?").run(new Date(0).toISOString(),"usage:q");let deliveries=0;assert.deepEqual(await ops.flush(async()=>{deliveries++;}),{sent:1,failed:0});assert.equal(deliveries,1);assert.equal(ops.outbox("usage:q")?.status,"sent");assert.deepEqual(await ops.flush(async()=>{deliveries++;}),{sent:0,failed:0});assert.equal(deliveries,1);state.close();}finally{try{rmSync(root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}catch(error){if((error as NodeJS.ErrnoException).code!=="EPERM")throw error;}}});

test("tenant event envelopes are ordered and audit triggers do not leak across companies",()=>{const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),platform=new PlatformOperations(state.db,state,projects,companies),ops=new OperationalStore(state.db);projects.createWorkspace("w","W");companies.createCompany({id:"a",name:"A",workspaceId:"w",budgetLimit:2,mandatoryReviews:["r"],mandatoryApprovals:["result"],allowedTools:["test"]},"a-owner");companies.createCompany({id:"b",name:"B",workspaceId:"w",budgetLimit:2,mandatoryReviews:["r"],mandatoryApprovals:["result"],allowedTools:["test"]},"b-owner");companies.createDepartment({id:"a-d",companyId:"a",parentId:null,name:"A",budgetLimit:1},"a-owner");companies.createDepartment({id:"b-d",companyId:"b",parentId:null,name:"B",budgetLimit:1},"b-owner");const a=ops.events("a"),b=ops.events("b");assert.ok(a.length>0&&b.length>0);assert.ok(a.every(x=>x.version==="1.0"&&x.tenantId==="a"&&x.cursor>0));assert.ok(b.every(x=>x.tenantId==="b"));assert.deepEqual(ops.events("a",a.at(-1)!.cursor),[]);void platform;state.close();});

test("online backup restores verified SQLite and rejects tampered backup and occupied target",async()=>{const root=mkdtempSync(join(tmpdir(),"ops-backup-")),db=join(root,"state.sqlite"),bak=join(root,"backup","state.bak"),restored=join(root,"restored.sqlite");try{const state=new SQLiteStateStore(db),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),platform=new PlatformOperations(state.db,state,projects,companies),ops=new OperationalStore(state.db,db);projects.createWorkspace("w","W");companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:2,mandatoryReviews:["r"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");await ops.createBackup(bak);state.close();const result=OperationalStore.restore(bak,restored);assert.equal(result.schemaVersion>0,true);const restoredState=new SQLiteStateStore(restored);assert.equal((restoredState.db.prepare("SELECT name FROM companies_v4 WHERE id='c'").get() as {name:string}).name,"C");new PlatformOperations(restoredState.db,restoredState,new ProjectOperations(restoredState.db,restoredState),new CompanyOperations(restoredState.db,restoredState,new ProjectOperations(restoredState.db,restoredState)));restoredState.close();assert.throws(()=>OperationalStore.restore(bak,restored),/must not exist/);const bytes=readFileSync(bak);bytes[100]=bytes[100]!^1;writeFileSync(bak,bytes);assert.throws(()=>OperationalStore.restore(bak,join(root,"bad.sqlite")),/integrity mismatch/);void platform;}finally{rmSync(root,{recursive:true,force:true});}});

test("legacy Host events use the durable event outbox and health reports runtime dependencies",async()=>{const state=new SQLiteStateStore(":memory:"),ops=new OperationalStore(state.db),client={async listModels(){return[];},async agent(){return{text:"",tokens:0,cost:0};},async usage(){}},adapter=new LegacyNvidiaHostAdapter(client,ops);await adapter.publishEvent({id:"e1",type:"task.started",runId:"r",payload:{}});await adapter.publishEvent({id:"e1",type:"task.started",runId:"r",payload:{}});assert.equal(ops.pending().length,1);assert.equal(ops.pending()[0]?.kind,"event");ops.setRuntimeStatus({redis:"ready",adapters:[{status:"ready"}]});const health=ops.health();assert.equal(health.redis,"ready");assert.deepEqual(health.adapters,[{status:"ready"}]);state.close();});

test("backup preserves representative Phase 1 through 5 state and schema",async()=>{
 const root=mkdtempSync(join(tmpdir(),"ops-full-backup-")),db=join(root,"source.sqlite"),bak=join(root,"full.bak"),target=join(root,"target.sqlite");
 try{
  const state=new SQLiteStateStore(db),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),platform=new PlatformOperations(state.db,state,projects,companies),ops=new OperationalStore(state.db,db);
  projects.createWorkspace("w","W");projects.createProject({id:"p",workspaceId:"w",name:"P",repoPath:"r",defaultBranch:"main",runtimePath:".",organizationProfile:{},budgetLimit:5},"owner");projects.createTask({id:"t",projectId:"p",milestoneId:null,title:"T",status:"ready",priority:1,completionCriteria:["done"],budgetLimit:4},{id:"owner"});
  state.createRun({id:"r",requestId:"q",goal:"g",risk:"low",status:"CREATED",budgetLimit:4,spent:0,checkpoint:null});projects.linkRun("t","r",{id:"owner"});state.createArtifactVersion({logicalId:"code:x",parentVersionId:null,runId:"r",kind:"code",path:"x.ts",baseCommit:"base",contentHash:"a".repeat(64)});state.recordValidation("r","test",true,"ok");
  companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:6,mandatoryReviews:["security"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");companies.createDepartment({id:"d",companyId:"c",parentId:null,name:"D",budgetLimit:5},"owner");companies.linkProject("c","d","p",1,"owner");const role=companies.createRoleTemplate({logicalId:"dev",companyId:"c",departmentId:"d",name:"Dev",responsibility:"work",allowedTools:["test"],requiredReviews:["security"],requiredApprovals:["result"],completionCriteria:["done"]},"owner");const workflow=platform.createWorkflow({logicalId:"flow",companyId:"c",name:"Flow",steps:[{id:"work",roleTemplateId:role.id,dependsOn:[],completionCriteria:["done"],tools:["test"]}],requiredReviews:["security"],requiredApprovals:["result"],budgetLimit:4,provenance:{source:"backup-test"}},"owner");platform.validateWorkflow(workflow.id,"c","owner");platform.publishWorkflow(workflow.id,"c","owner");platform.bindWorkflow(workflow.id,"c","run","r","owner");
  const tables=["runs","artifact_versions_v2","validation_results","projects_v3","companies_v4","role_templates_v15","role_template_bindings_v15","run_execution_snapshots_v15","workflow_definitions_v5","workflow_bindings_v5","events_v6"],before=Object.fromEntries(tables.map(name=>[name,Number((state.db.prepare(`SELECT COUNT(*) n FROM ${name}`).get() as {n:number}).n)])),schema=ops.schemaVersion();await ops.createBackup(bak);state.close();OperationalStore.restore(bak,target);
  const restored=new SQLiteStateStore(target),restoredOps=new OperationalStore(restored.db,target),after=Object.fromEntries(tables.map(name=>[name,Number((restored.db.prepare(`SELECT COUNT(*) n FROM ${name}`).get() as {n:number}).n)]));assert.deepEqual(after,before);assert.equal(restoredOps.schemaVersion(),schema);assert.equal(restored.getRun("r")?.goal,"g");assert.equal((restored.db.prepare("SELECT status FROM workflow_definitions_v5 WHERE id=?").get(workflow.id) as {status:string}).status,"published");restored.close();
 }finally{rmSync(root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}
});
