import test from "node:test";
import assert from "node:assert/strict";
import { once } from "node:events";
import { mkdtempSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { SQLiteStateStore } from "../packages/persistence/src/index.js";
import { ProjectOperations } from "../packages/project-ops/src/index.js";
import { CompanyOperations } from "../packages/company-ops/src/index.js";
import { OperationalStore } from "../packages/operations/src/index.js";
import { RunController } from "../packages/runtime/src/index.js";
import { RunIntakeService } from "../packages/policy/src/index.js";
import { ControlPlaneApi } from "../apps/control-plane/src/index.js";

class Queue { async enqueue() {} async remove() { return false; } }
async function streamUntil(response:Response,pattern:RegExp){assert.ok(response.body);const reader=response.body.getReader(),decoder=new TextDecoder();let text="";try{while(!pattern.test(text)){const {done,value}=await reader.read();if(done)break;text+=decoder.decode(value,{stream:true});}}finally{await reader.cancel();}return text;}
async function fixture(path:string){const state=new SQLiteStateStore(path),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),operations=new OperationalStore(state.db,path),controller=new RunController(state,new Queue()),intake=new RunIntakeService(state,controller),server=new ControlPlaneApi(state,intake,controller,{approvePlan(){},approveResult(){}},projects,companies,undefined,undefined,operations).server();server.listen(0,"127.0.0.1");await once(server,"listening");const address=server.address();assert.ok(address&&typeof address==="object");return{state,base:`http://127.0.0.1:${address.port}`,async close(){server.closeAllConnections();await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));state.close();}};}

test("P0 goal-to-reward loop survives restart without duplicate events or rewards",async()=>{const root=mkdtempSync(join(tmpdir(),"p0-demo-")),path=join(root,"state.sqlite");try{let app=await fixture(path);const post=(base:string,url:string,body:unknown)=>fetch(base+url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),request={requestId:"p0-e2e-request",goal:"Add a visible connection status",auto:true};let response=await post(app.base,"/api/demo/scenarios",request);assert.equal(response.status,201);const created=await response.json() as {scenario:{id:string;status:string;step:number};events:unknown[]};assert.equal(created.scenario.status,"completed");assert.equal(created.scenario.step,12);assert.equal(created.events.length,12);const office=await(await fetch(`${app.base}/api/companies/demo-company/office-projection?actor=demo-owner`)).json() as {phase:string;stateHash:string;timeline:unknown[]},game=await(await fetch(`${app.base}/api/companies/demo-company/game-progression?actor=demo-owner`)).json() as {companyXp:number;stateHash:string;ledger:unknown[];achievements:string[]};assert.equal(office.phase,"completed");assert.equal(office.timeline.length>=12,true);assert.equal(game.companyXp,23);assert.equal(game.ledger.length,1);assert.deepEqual(game.achievements,["first-delivery"]);const sse=await streamUntil(await fetch(`${app.base}/api/events?companyId=demo-company&after=0`),/event: workflow\.completed/);assert.match(sse,/event: validation.failed/);await app.close();app=await fixture(path);response=await post(app.base,"/api/demo/scenarios",request);const replayed=await response.json() as {scenario:{id:string};events:unknown[]};assert.equal(replayed.scenario.id,created.scenario.id);assert.equal(replayed.events.length,12);const restoredOffice=await(await fetch(`${app.base}/api/companies/demo-company/office-projection?actor=demo-owner`)).json() as {stateHash:string},restoredGame=await(await fetch(`${app.base}/api/companies/demo-company/game-progression?actor=demo-owner`)).json() as {stateHash:string;ledger:unknown[]};assert.equal(restoredOffice.stateHash,office.stateHash);assert.equal(restoredGame.stateHash,game.stateHash);assert.equal(restoredGame.ledger.length,1);assert.equal((app.state.db.prepare("SELECT COUNT(*) n FROM events_v6 WHERE aggregate_type='demo-scenario'").get() as {n:number}).n,12);await app.close();}finally{rmSync(root,{recursive:true,force:true});}});
