import test from "node:test";
import assert from "node:assert/strict";
import { SQLiteStateStore } from "../packages/persistence/src/index.js";
import { ProjectOperations } from "../packages/project-ops/src/index.js";
import { CompanyOperations } from "../packages/company-ops/src/index.js";
import { OperationalStore } from "../packages/operations/src/index.js";
import { OfficeProjectionStore } from "../packages/office-projection/src/index.js";
import { RunController } from "../packages/runtime/src/index.js";

class Queue { async enqueue() {} async remove(){return false;} }
test("actual Run, Task, Validation and Approval events drive Office Projection without state mismatch",async()=>{const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),operations=new OperationalStore(state.db),controller=new RunController(state,new Queue());projects.createWorkspace("w","W");projects.createProject({id:"p",workspaceId:"w",name:"P",repoPath:".",defaultBranch:"main",runtimePath:".",organizationProfile:{},budgetLimit:5},"owner");projects.createTask({id:"t",projectId:"p",milestoneId:null,title:"T",status:"ready",priority:1,completionCriteria:["done"],budgetLimit:4},{id:"owner"});projects.assign("t",{id:"owner"},"worker-1","agent","executor");projects.assign("t",{id:"owner"},"reviewer-1","agent","reviewer");companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:6,mandatoryReviews:["security"],mandatoryApprovals:["result"],allowedTools:["build","test"]},"owner");companies.createDepartment({id:"d",companyId:"c",parentId:null,name:"Engineering",budgetLimit:5},"owner");companies.addMember("c","owner","worker-1","member","d");companies.addMember("c","owner","reviewer-1","member","d");companies.linkProject("c","d","p",1,"owner");await controller.create({id:"r",requestId:"q",goal:"change",risk:"high",status:"CREATED",budgetLimit:4,spent:0,checkpoint:null});projects.linkRun("t","r",{id:"owner"});projects.claim("t","worker-1",60_000,{id:"owner"});controller.move("r","PLANNING");controller.move("r","PLAN_APPROVAL_WAITING");let store=new OfficeProjectionStore(state.db,operations),projection=store.catchUp("c");assert.equal(projection.phase,"planning");assert.equal(projection.runId,"r");assert.equal(projection.taskId,"t");assert.deepEqual(store.links("c").map(x=>[x.agentId,x.responsibility]),[["worker-1","executor"],["reviewer-1","reviewer"]]);controller.move("r","READY");controller.move("r","RUNNING");projection=store.catchUp("c");assert.equal(projection.phase,"working");assert.equal(projection.activeAgentId,"worker-1");controller.move("r","VALIDATING");state.audit("r","VALIDATION_COMPLETED",{passed:false,checks:[{kind:"test",passed:false}]});state.audit("r","VALIDATION_COMPLETED",{passed:true,checks:[{kind:"test",passed:true}]});controller.move("r","RESULT_APPROVAL_WAITING");projection=store.catchUp("c");assert.equal(projection.phase,"approval");assert.ok(projection.alerts.some(x=>x.priority==="warning"));assert.ok(projection.alerts.some(x=>x.priority==="high"));state.audit("r","RESULT_APPROVED",{userId:"owner",patchHash:"a".repeat(64)});controller.move("r","COMPLETED");projection=store.catchUp("c");assert.equal(projection.phase,"completed");assert.equal(projection.runId,"r");assert.ok(projection.timeline.some(x=>x.type==="validation.completed"&&x.phase==="validating"));assert.deepEqual(store.consistency("c"),{companyId:"c",checked:1,mismatches:[],ok:true});assert.equal(store.rebuild("c").stateHash,projection.stateHash);state.close();});

test("multiple runs retain independent phases and replay to the same projection",async()=>{const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),operations=new OperationalStore(state.db),controller=new RunController(state,new Queue());projects.createWorkspace("w2","W2");projects.createProject({id:"p2",workspaceId:"w2",name:"P2",repoPath:".",defaultBranch:"main",runtimePath:".",organizationProfile:{},budgetLimit:10},"owner");for(const id of ["t1","t2"])projects.createTask({id,projectId:"p2",milestoneId:null,title:id,status:"ready",priority:1,completionCriteria:["done"],budgetLimit:4},{id:"owner"});companies.createCompany({id:"c2",name:"C2",workspaceId:"w2",budgetLimit:10,mandatoryReviews:["security"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");companies.createDepartment({id:"d2",companyId:"c2",parentId:null,name:"Engineering",budgetLimit:10},"owner");companies.linkProject("c2","d2","p2",1,"owner");for(const [taskId,runId] of [["t1","r1"],["t2","r2"]]){await controller.create({id:runId!,requestId:`q-${runId}`,goal:runId!,risk:"low",status:"CREATED",budgetLimit:4,spent:0,checkpoint:null});projects.linkRun(taskId!,runId!,{id:"owner"});}controller.move("r1","PLANNING");controller.move("r1","PLAN_APPROVAL_WAITING");controller.move("r1","READY");controller.move("r1","RUNNING");controller.move("r2","PLANNING");controller.move("r2","PLAN_APPROVAL_WAITING");controller.move("r2","READY");controller.move("r2","RUNNING");controller.move("r2","VALIDATING");const store=new OfficeProjectionStore(state.db,operations),projection=store.catchUp("c2");assert.equal(projection.workItems.find(x=>x.key==="r1")?.phase,"working");assert.equal(projection.workItems.find(x=>x.key==="r2")?.phase,"validating");assert.deepEqual(store.consistency("c2"),{companyId:"c2",checked:2,mismatches:[],ok:true});assert.equal(store.rebuild("c2").stateHash,projection.stateHash);state.close();});
