import test from "node:test";import assert from "node:assert/strict";
import {SQLiteStateStore,type RunStatus} from "../packages/persistence/src/index.js";import {RunController} from "../packages/runtime/src/index.js";import {ProjectOperations} from "../packages/project-ops/src/index.js";import {InterventionConflict,InterventionService} from "../packages/intervention/src/index.js";
class Queue{jobs:string[]=[];async enqueue(x:{runId:string}){this.jobs.push(x.runId)}async remove(){return false}}
test("P4 interventions enforce status, permission, idempotency and audit",async()=>{const state=new SQLiteStateStore(":memory:"),queue=new Queue(),controller=new RunController(state,queue),projects=new ProjectOperations(state.db,state),service=new InterventionService(state.db,state,controller,projects);projects.createWorkspace("w","W");projects.createProject({id:"p",workspaceId:"w",name:"P",repoPath:".",defaultBranch:"main",runtimePath:".",organizationProfile:{},budgetLimit:20},"owner");
 const create=async(id:string,status:RunStatus,checkpoint:Record<string,unknown>|null={seed:true})=>{await controller.create({id,requestId:`q-${id}`,goal:id,risk:"medium",status:"CREATED",budgetLimit:10,spent:0,checkpoint});projects.createTask({id:`t-${id}`,projectId:"p",milestoneId:null,title:id,status:"ready",priority:1,completionCriteria:["done"],budgetLimit:10},{id:"owner"});projects.linkRun(`t-${id}`,id,{id:"owner"});if(status!=="CREATED")state.transition(id,["CREATED"],status,checkpoint??undefined)};
 await create("pause","RUNNING");const paused=await service.execute("pause","pause",{requestId:"i1",actorId:"owner",reason:"inspect",expectedStatus:"RUNNING"});assert.equal(state.getRun("pause")?.status,"PAUSED");assert.deepEqual(await service.execute("pause","pause",{requestId:"i1",actorId:"owner",reason:"inspect",expectedStatus:"RUNNING"}),paused);
 await assert.rejects(service.execute("pause","pause",{requestId:"stale",actorId:"owner",reason:"again",expectedStatus:"RUNNING"}),InterventionConflict);
 await create("paths","PLAN_APPROVAL_WAITING");await service.execute("paths","restrict-path",{requestId:"i2",actorId:"owner",reason:"scope",expectedStatus:"PLAN_APPROVAL_WAITING",paths:["src"]});assert.deepEqual(state.getRun("paths")?.checkpoint?.restrictedPaths,["src"]);
 await create("tests","RESULT_APPROVAL_WAITING");await service.execute("tests","request-tests",{requestId:"i3",actorId:"owner",reason:"coverage",expectedStatus:"RESULT_APPROVAL_WAITING",tests:["npm test"]});assert.equal(state.getRun("tests")?.status,"REVISION_REQUIRED");
 await create("people","RUNNING");await service.execute("people","add-reviewer",{requestId:"i4",actorId:"owner",reason:"risk",expectedStatus:"RUNNING",principalId:"qa"});await service.execute("people","assign-human",{requestId:"i5",actorId:"owner",reason:"human gate",expectedStatus:"RUNNING",principalId:"human",responsibility:"reviewer"});assert.equal(projects.assignments("t-people").length,2);assert.equal(state.getRun("people")?.checkpoint?.humanReview,true);
 await create("retry","BLOCKED");await service.execute("retry","retry-from-checkpoint",{requestId:"i6",actorId:"owner",reason:"resume",expectedStatus:"BLOCKED"});assert.equal(state.getRun("retry")?.status,"READY");
 await create("budget","RUNNING");await service.execute("budget","set-budget",{requestId:"i7",actorId:"owner",reason:"cap",expectedStatus:"RUNNING",limit:4});assert.equal(state.getRun("budget")?.budgetLimit,4);await service.execute("budget","stop-budget",{requestId:"i8",actorId:"owner",reason:"stop",expectedStatus:"RUNNING"});assert.equal(state.getRun("budget")?.status,"BLOCKED");
 await create("explain","FAILED");const explanation=await service.execute("explain","request-explanation",{requestId:"i9",actorId:"owner",reason:"why",expectedStatus:"FAILED"}) as {detail:{status:string}};assert.equal(explanation.detail.status,"FAILED");assert.equal(service.list("explain").length,1);for(const id of ["pause","paths","tests","people","retry","budget","explain"])assert.ok(state.auditEvents(id).some(x=>x.type==="RUN_INTERVENTION_APPLIED"));state.close();});
