import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync,rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { SQLiteStateStore } from "../packages/persistence/src/index.js";
import { ProjectOperations } from "../packages/project-ops/src/index.js";
import { CompanyOperations } from "../packages/company-ops/src/index.js";
import { PlatformOperations,PlatformRunGovernance,MockExternalAgentAdapter,contentHash } from "../packages/platform-ops/src/index.js";

function fixture(path=":memory:"){
 const state=new SQLiteStateStore(path),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),platform=new PlatformOperations(state.db,state,projects,companies);
 projects.createWorkspace("w","Workspace");projects.createProject({id:"p",workspaceId:"w",name:"Project",repoPath:"repo",defaultBranch:"main",runtimePath:".",organizationProfile:{},budgetLimit:8},"owner");projects.createTask({id:"t",projectId:"p",milestoneId:null,title:"Task",status:"ready",priority:1,completionCriteria:["done"],budgetLimit:5},{id:"owner"});
 companies.createCompany({id:"c",name:"Company",workspaceId:"w",budgetLimit:10,mandatoryReviews:["security"],mandatoryApprovals:["result"],allowedTools:["build","test"]},"owner");companies.createDepartment({id:"d",companyId:"c",parentId:null,name:"Engineering",budgetLimit:8},"owner");companies.linkProject("c","d","p",1,"owner");
 const role=companies.createRoleTemplate({logicalId:"developer",companyId:"c",departmentId:"d",name:"Developer",responsibility:"build",allowedTools:["build","test"],requiredReviews:["security"],requiredApprovals:["result"],completionCriteria:["done"]},"owner");
 return{state,projects,companies,platform,role};
}
const workflow=(roleTemplateId:string,logicalId="delivery")=>({logicalId,companyId:"c",name:"Delivery",steps:[{id:"build",roleTemplateId,dependsOn:[],completionCriteria:["built"],tools:["build"]},{id:"test",roleTemplateId,dependsOn:["build"],completionCriteria:["passed"],tools:["test"]}],requiredReviews:["security"],requiredApprovals:["result"],budgetLimit:5,provenance:{source:"test"}});

test("versioned workflow validates, publishes, binds to an actual Run and survives restart",()=>{const root=mkdtempSync(join(tmpdir(),"platform-v5-")),path=join(root,"state.sqlite");try{const f=fixture(path);const w=f.platform.createWorkflow(workflow(f.role.id),"owner");assert.equal(w.version,1);assert.equal(f.platform.validateWorkflow(w.id,"c","owner").status,"validated");assert.equal(f.platform.publishWorkflow(w.id,"c","owner").status,"published");f.state.createRun({id:"r",requestId:"q",goal:"g",risk:"low",status:"CREATED",budgetLimit:5,spent:0,checkpoint:null});f.projects.linkRun("t","r",{id:"owner"});f.platform.bindWorkflow(w.id,"c","run","r","owner");assert.deepEqual(f.platform.governanceForRun("r")?.allowedTools,["build","test"]);f.state.close();const restored=fixtureExisting(path);assert.equal(restored.platform.workflows("c","owner")[0]?.status,"published");assert.equal(restored.platform.governanceForRun("r")?.workflowId,w.id);restored.state.close();}finally{rmSync(root,{recursive:true,force:true});}});

function fixtureExisting(path:string){const state=new SQLiteStateStore(path),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),platform=new PlatformOperations(state.db,state,projects,companies);return{state,projects,companies,platform};}

test("workflow blocks cycles, orphan dependencies, missing criteria, governance weakening and tool escalation",()=>{const f=fixture();const bad=[
 {...workflow(f.role.id,"cycle"),steps:[{id:"a",roleTemplateId:f.role.id,dependsOn:["b"],completionCriteria:["x"],tools:["build"]},{id:"b",roleTemplateId:f.role.id,dependsOn:["a"],completionCriteria:["x"],tools:["test"]}]},
 {...workflow(f.role.id,"orphan"),steps:[{id:"a",roleTemplateId:f.role.id,dependsOn:["missing"],completionCriteria:["x"],tools:["build"]}]},
 {...workflow(f.role.id,"criteria"),steps:[{id:"a",roleTemplateId:f.role.id,dependsOn:[],completionCriteria:[],tools:["build"]}]},
 {...workflow(f.role.id,"governance"),requiredReviews:[]},
 {...workflow(f.role.id,"tools"),steps:[{id:"a",roleTemplateId:f.role.id,dependsOn:[],completionCriteria:["x"],tools:["deploy"]}]}
 ];for(const x of bad){const w=f.platform.createWorkflow(x,"owner");assert.throws(()=>f.platform.validateWorkflow(w.id,"c","owner"));}assert.ok(f.platform.auditEvents("c","owner").length>=10);f.state.close();});

test("published workflow governance is composed with company policy and enforced on a Run",()=>{const f=fixture(),w=f.platform.createWorkflow({...workflow(f.role.id),steps:[{id:"test",roleTemplateId:f.role.id,dependsOn:[],completionCriteria:["passed"],tools:["test"]}]},"owner");f.platform.validateWorkflow(w.id,"c","owner");f.platform.publishWorkflow(w.id,"c","owner");f.state.createRun({id:"r",requestId:"governed",goal:"g",risk:"low",status:"CREATED",budgetLimit:5,spent:0,checkpoint:null});f.projects.linkRun("t","r",{id:"owner"});f.platform.bindWorkflow(w.id,"c","run","r","owner");const governance=new PlatformRunGovernance(f.companies,f.platform);assert.equal(governance.requiresReviewer("r"),true);assert.deepEqual((governance.context("r") as {allowedTools:string[]}).allowedTools,["test"]);governance.assertTools("r",["test"]);assert.throws(()=>governance.assertTools("r",["build"]),/workflow blocks/);assert.ok(JSON.stringify(f.platform.auditEvents("c","owner")).includes("WORKFLOW_RUN_POLICY_DENIED"));f.state.close();});

test("plugin registry verifies hash, signature, policy, adapter and tenant isolation",()=>{const f=fixture();f.platform.registerAdapter({id:"local",companyId:"c",contractVersion:"v1",status:"ready",failures:0,openedUntil:null,metadata:{local:true}},"owner");const roleManifest={responsibility:"implement",inputSchema:{type:"object"},outputSchema:{type:"object"},requiredReviews:["security"],requiredApprovals:["result"],allowedTools:["build"]};assert.throws(()=>f.platform.registerPlugin({logicalId:"bad",type:"role",companyId:"c",manifest:roleManifest,manifestHash:"bad",signature:{trust:true,signer:"local"}},"owner"),/hash/);const p=f.platform.registerPlugin({logicalId:"role-plugin",type:"role",companyId:"c",manifest:roleManifest,manifestHash:contentHash(roleManifest),signature:{trust:"local",signer:"owner"}},"owner");assert.equal(p.version,1);const tool={inputSchema:{type:"object"},outputSchema:{type:"object"},capability:"test",risk:"medium",timeoutMs:5000,maxOutputBytes:1000,adapterId:"local"},tp=f.platform.registerPlugin({logicalId:"test-tool",type:"tool",companyId:"c",manifest:tool,manifestHash:contentHash(tool),signature:{trust:"local",signer:"owner"}},"owner");assert.equal(tp.type,"tool");assert.equal(f.platform.authorizeTool({companyId:"c",actorId:"owner",toolPluginId:tp.id}).allowed,true);assert.throws(()=>f.platform.authorizeTool({companyId:"c",actorId:"owner",toolPluginId:tp.id,rolePluginId:p.id}),/Role plugin/);assert.throws(()=>f.platform.registerPlugin({logicalId:"oversize",type:"tool",companyId:"c",manifest:{...tool,maxOutputBytes:2_000_000},manifestHash:contentHash({...tool,maxOutputBytes:2_000_000}),signature:{trust:"local",signer:"owner"}},"owner"),/limits/);assert.throws(()=>f.platform.plugins("c","outsider"),/permission denied/);f.state.close();});

test("industry templates require exact approval hash; metrics, recommendations and game are read-only and deterministic",()=>{const f=fixture();const preview=f.platform.industryPreview("c","software","owner");assert.equal(preview.requiresApproval,true);assert.throws(()=>f.platform.installIndustry("c","software","wrong","owner"),/hash/);f.platform.installIndustry("c","software",preview.hash,"owner");f.state.createRun({id:"r",requestId:"metrics",goal:"g",risk:"low",status:"BLOCKED",budgetLimit:5,spent:1,checkpoint:null});f.projects.linkRun("t","r",{id:"owner"});f.state.recordValidation("r","test",true,"ok");const before=f.companies.company("c"),metrics=f.platform.metrics("c","owner"),recommendations=f.platform.expansionRecommendations("c","owner"),g1=f.platform.gameState("c","owner"),g2=f.platform.gameState("c","owner");assert.equal(metrics.sampleCount,1);assert.deepEqual(metrics.provenance.runIds,["r"]);assert.equal(recommendations.readOnly,true);assert.ok(recommendations.items.length>0);assert.deepEqual(f.companies.company("c"),before);assert.equal(g1.stateHash,g2.stateHash);assert.equal(g1.readOnly,true);f.state.close();});

test("mock external adapter enforces contract, auth, deadline, idempotency and circuit breaker while recording lineage",async()=>{const f=fixture();f.state.createRun({id:"r",requestId:"adapter-run",goal:"g",risk:"low",status:"CREATED",budgetLimit:1,spent:0,checkpoint:null});const adapter=new MockExternalAgentAdapter(f.state,"mock","v1","agent:invoke",2,10000),base={runId:"r",contractVersion:"v1",scope:"agent:invoke",deadline:new Date(Date.now()+10000).toISOString(),payload:{work:true}};await assert.rejects(adapter.invoke({...base,requestId:"bad-version",contractVersion:"v2"}),/contract/);await assert.rejects(adapter.invoke({...base,requestId:"bad-auth",scope:"admin"}),/auth/);await assert.rejects(adapter.invoke({...base,requestId:"late",deadline:new Date(0).toISOString()}),/deadline/);const one=await adapter.invoke({...base,requestId:"same"}),two=await adapter.invoke({...base,requestId:"same"});assert.deepEqual(one,two);assert.equal(f.state.lineage("r").toolCalls.length,1);await assert.rejects(adapter.invoke({...base,requestId:"fail-1",simulateFailure:true}),/failure/);await assert.rejects(adapter.invoke({...base,requestId:"fail-2",simulateFailure:true}),/failure/);await assert.rejects(adapter.invoke({...base,requestId:"open"}),/circuit/);assert.equal(adapter.status().status,"open");f.state.close();});
