import test from "node:test";
import assert from "node:assert/strict";
import { once } from "node:events";
import { SQLiteStateStore } from "../packages/persistence/src/index.js";
import { ProjectOperations } from "../packages/project-ops/src/index.js";
import { CompanyOperations } from "../packages/company-ops/src/index.js";
import { PlatformOperations } from "../packages/platform-ops/src/index.js";
import { RunController } from "../packages/runtime/src/index.js";
import { RunIntakeService } from "../packages/policy/src/index.js";
import { ControlPlaneApi } from "../apps/control-plane/src/index.js";

test("Platform Console API performs draft, validation, publish, binding and tenant snapshot",async t=>{class Queue{async enqueue(){}async remove(){return false;}}const store=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(store.db,store),companies=new CompanyOperations(store.db,store,projects),platform=new PlatformOperations(store.db,store,projects,companies),controller=new RunController(store,new Queue()),intake=new RunIntakeService(store,controller);projects.createWorkspace("w","W");projects.createProject({id:"p",workspaceId:"w",name:"P",repoPath:"r",defaultBranch:"main",runtimePath:".",organizationProfile:{},budgetLimit:5},"owner");companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:6,mandatoryReviews:["security"],mandatoryApprovals:["result"],allowedTools:["build","test"]},"owner");companies.createDepartment({id:"d",companyId:"c",parentId:null,name:"D",budgetLimit:5},"owner");companies.linkProject("c","d","p",1,"owner");const role=companies.createRoleTemplate({logicalId:"dev",companyId:"c",departmentId:"d",name:"Dev",responsibility:"work",allowedTools:["build","test"],requiredReviews:["security"],requiredApprovals:["result"],completionCriteria:["done"]},"owner");const server=new ControlPlaneApi(store,intake,controller,{approvePlan(){},approveResult(){}},projects,companies,platform).server();server.listen(0,"127.0.0.1");await once(server,"listening");t.after(()=>{server.close();store.close();});const address=server.address();assert.ok(address&&typeof address==="object");const base=`http://127.0.0.1:${address.port}`,post=async(path:string,body:unknown)=>{const r=await fetch(base+path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const x=await r.json() as any;assert.equal(r.ok,true,x.error);return x;};const html=await(await fetch(base)).text();assert.match(html,/Platform Console/);assert.match(html,/산업 템플릿/);const w=await post("/api/companies/c/workflows",{actorId:"owner",logicalId:"delivery",name:"Delivery",steps:[{id:"work",roleTemplateId:role.id,dependsOn:[],completionCriteria:["done"],tools:["build"]}],requiredReviews:["security"],requiredApprovals:["result"],budgetLimit:3,provenance:{source:"api-test"}});await post(`/api/companies/c/workflows/${w.id}/validate`,{actorId:"owner"});await post(`/api/companies/c/workflows/${w.id}/publish`,{actorId:"owner"});await post(`/api/companies/c/workflows/${w.id}/bind`,{actorId:"owner",targetType:"project",targetId:"p"});const snapshot=await(await fetch(base+"/api/companies/c/platform?actor=owner")).json() as any;assert.equal(snapshot.workflows[0].status,"published");assert.equal(snapshot.recommendations.readOnly,true);const denied=await fetch(base+"/api/companies/c/platform?actor=outsider");assert.equal(denied.status,400);});
