import test from "node:test";
import assert from "node:assert/strict";
import {SQLiteStateStore} from "../packages/persistence/src/index.js";
import {ProjectOperations} from "../packages/project-ops/src/index.js";
import {CompanyOperations} from "../packages/company-ops/src/index.js";
import {OperationalStore} from "../packages/operations/src/index.js";
import {ReportingProjector,REPORT_PROJECTOR_VERSION} from "../packages/reporting/src/index.js";

function fixture(){const state=new SQLiteStateStore(":memory:"),projects=new ProjectOperations(state.db,state),companies=new CompanyOperations(state.db,state,projects),operations=new OperationalStore(state.db);projects.createWorkspace("w","W");projects.createProject({id:"p",workspaceId:"w",name:"P",repoPath:".",defaultBranch:"main",runtimePath:".",organizationProfile:{},budgetLimit:10},"owner");projects.createTask({id:"t",projectId:"p",milestoneId:null,title:"T",status:"ready",priority:1,completionCriteria:["done"],budgetLimit:5},{id:"owner"});companies.createCompany({id:"c",name:"C",workspaceId:"w",budgetLimit:20,mandatoryReviews:["review"],mandatoryApprovals:["result"],allowedTools:["test"]},"owner");companies.createDepartment({id:"parent",companyId:"c",parentId:null,name:"Parent",budgetLimit:20},"owner");companies.createDepartment({id:"child",companyId:"c",parentId:"parent",name:"Child",budgetLimit:10},"owner");companies.addMember("c","owner","worker","member","child");companies.addMember("c","owner","manager-z","department-manager","parent");companies.addMember("c","owner","manager-a","department-manager","parent");companies.addMember("c","owner","executive","executive",null);companies.linkProject("c","child","p",1,"owner");projects.assign("t",{id:"owner"},"worker","agent","executor");state.createRun({id:"r",requestId:"q",goal:"g",risk:"high",status:"RUNNING",budgetLimit:5,spent:0,checkpoint:null});projects.linkRun("t","r",{id:"owner"});return{state,projects,companies,operations,reports:new ReportingProjector(state.db,companies)};}

test("event projector routes deterministically through parent manager and deduplicates replay",()=>{const{state,operations,reports}=fixture();operations.emit({tenantId:"c",aggregateType:"run",aggregateId:"r",type:"VALIDATION_FAILED",eventId:"failure",payload:{runId:"r",taskId:"t",agentId:"worker",reason:"tests"}});const first=reports.catchUp("c"),items=reports.reportsForActor("c","manager-a");assert.equal(first.created,1);assert.equal(items.length,1);assert.equal(items[0]?.reportType,"blocker");assert.equal(items[0]?.recipientId,"manager-a");assert.deepEqual(items[0]?.routing.candidates,["manager-a","manager-z","executive","owner"]);assert.ok(items[0]?.evidenceIds.includes("failure"));assert.equal(reports.catchUp("c").created,0);assert.equal(state.db.prepare("SELECT COUNT(*) n FROM deterministic_reports_v17 WHERE source_event_id='failure'").get()?.n,1);state.close();});

test("report read, acknowledge and escalation are authorized and audited",()=>{const{state,operations,reports}=fixture();operations.emit({tenantId:"c",aggregateType:"run",aggregateId:"r",type:"PATCH_HASH_BLOCKED",eventId:"decision",payload:{runId:"r",taskId:"t",agentId:"worker"}});reports.catchUp("c");const report=reports.reportsForActor("c","manager-a")[0]!;assert.equal(report.decisionRequired,true);assert.equal(reports.read("c",report.id,"manager-a").status,"read");assert.equal(reports.acknowledge("c",report.id,"manager-a").status,"acknowledged");assert.throws(()=>reports.read("c",report.id,"manager-z"),/access denied/);const escalated=reports.escalate("c",report.id,"manager-a");assert.equal(escalated.recipientId,"manager-z");assert.equal(escalated.status,"escalated");assert.equal(reports.read("c",report.id,"manager-z").status,"read");assert.match(JSON.stringify(state.db.prepare("SELECT type FROM company_audit_v4 WHERE company_id='c'").all()),/REPORT_ESCALATED/);state.close();});

test("department cycle and missing fallback fail closed as unroutable",()=>{const{state,companies,operations,reports}=fixture();state.db.prepare("UPDATE departments_v4 SET parent_id='child' WHERE id='parent'").run();operations.emit({tenantId:"c",aggregateType:"run",aggregateId:"r",type:"BUDGET_BLOCKED",eventId:"cycle",payload:{runId:"r",taskId:"t",agentId:"worker"}});reports.catchUp("c");const owner=reports.reportsForActor("c","owner"),report=owner.find(x=>x.sourceEventId==="cycle")!;assert.equal(report.status,"unroutable");assert.equal(report.recipientId,null);assert.equal(report.routing.reason,"department-cycle");assert.throws(()=>reports.acknowledge("c",report.id,"owner"),/cannot be acknowledged/);assert.match(JSON.stringify(companies.auditEvents("c")),/REPORT_UNROUTABLE/);state.close();});

test("projector version replay preserves deterministic report identities",()=>{const{state,operations,reports}=fixture();operations.emit({tenantId:"c",aggregateType:"run",aggregateId:"r",type:"WORKFLOW_COMPLETED",eventId:"complete",payload:{runId:"r",taskId:"t",agentId:"worker",goal:"done"}});reports.catchUp("c");const before=reports.reportsForActor("c","manager-a")[0]!;state.db.prepare("UPDATE report_projector_state_v17 SET projector_version='old'").run();const rebuilt=reports.catchUp("c"),after=reports.reportsForActor("c","manager-a")[0]!;assert.equal(rebuilt.created,1);assert.equal(after.id,before.id);assert.equal(after.projectorVersion,REPORT_PROJECTOR_VERSION);assert.deepEqual(after.completed,["done"]);state.close();});
