import test from "node:test";
import assert from "node:assert/strict";
import { SQLiteStateStore, type StoredRun } from "../packages/persistence/src/index.js";
import { RunController } from "../packages/runtime/src/index.js";
import { RolePipeline } from "../packages/role-pipeline/src/index.js";
import { StandaloneHostAdapter } from "../apps/standalone-host/src/index.js";

class FakeQueue { jobs = new Map<string, unknown>(); async enqueue(x: { runId: string }) { this.jobs.set(x.runId, x); } async remove(id: string) { return this.jobs.delete(id); } }
const makeRun = (id: string, risk: string, budgetLimit = 10): StoredRun => ({ id, requestId: `req-${id}`, goal: "secure change", risk, status: "CREATED", budgetLimit, spent: 0, checkpoint: null });

for (const [risk, expected] of [["low", ["worker"]], ["medium", ["planner", "worker"]], ["high", ["planner", "worker", "reviewer"]], ["critical", ["planner", "worker", "reviewer"]]] as const) test(`role policy calls ${risk} roles and passes artifacts`, async () => {
  const store = new SQLiteStateStore(":memory:"); const queue = new FakeQueue(); const controller = new RunController(store, queue); const host = new StandaloneHostAdapter(); const pipeline = new RolePipeline(store, controller, host);
  await controller.create(makeRun(risk, risk)); await pipeline.process(risk);
  assert.equal(store.getRun(risk)?.status, "PLAN_APPROVAL_WAITING"); pipeline.approvePlan(risk, "owner"); await pipeline.process(risk);
  assert.equal(store.getRun(risk)?.status, "VALIDATING");await pipeline.review(risk,[{kind:"test",passed:true}]);assert.deepEqual(store.tasks(risk).map(x => x.role), expected);
  assert.ok(store.tasks(risk).every(task => task.completionCriteria.length > 0)); if (risk !== "low") assert.equal((JSON.parse((store.tasks(risk)[0]!.output as { text: string }).text) as { tasks: unknown[] }).tasks.length, 1);
  const workerInput = store.tasks(risk).find(x => x.role === "worker")?.input as { prior: unknown[] }; assert.equal(workerInput.prior.length, risk === "low" ? 0 : 1);
  if(risk==="high"||risk==="critical")assert.deepEqual((store.tasks(risk).find(x=>x.role==="reviewer")?.input as {evidence:{validation:unknown}}).evidence.validation,[{kind:"test",passed:true}]);
  assert.equal(host.usage.length, expected.length); store.close();
});

test("role pipeline resumes completed planner without another model call", async () => {
  const store = new SQLiteStateStore(":memory:"); const queue = new FakeQueue(); const controller = new RunController(store, queue); const host = new StandaloneHostAdapter(); const pipeline = new RolePipeline(store, controller, host);
  await controller.create(makeRun("resume", "high")); await pipeline.process("resume"); assert.equal(host.usage.length, 1);
  pipeline.approvePlan("resume", "owner"); await pipeline.process("resume");await pipeline.review("resume",[{kind:"test",passed:true}]); assert.equal(host.usage.length, 3); assert.equal(store.tasks("resume").filter(x => x.role === "planner").length, 1); store.close();
});

test("role pipeline repairs a prose response into the required JSON contract",async()=>{class RepairHost extends StandaloneHostAdapter{prompts:string[]=[];override async invokeModel(request:Parameters<StandaloneHostAdapter["invokeModel"]>[0]){this.prompts.push(request.prompt);const body=JSON.parse(request.prompt) as {candidateOutput?:string};return{requestId:request.requestId,text:body.candidateOutput?JSON.stringify({summary:"repaired",tasks:[{id:"task-1",role:"worker",completionCriteria:["done"],validationCommands:["test"]}]}):"The user wants a plan, but here is commentary instead.",tokens:2,cost:0,estimated:false};}}const store=new SQLiteStateStore(":memory:"),controller=new RunController(store,new FakeQueue()),host=new RepairHost(),pipeline=new RolePipeline(store,controller,host);await controller.create(makeRun("repair-plan","medium"));await pipeline.process("repair-plan");assert.equal(store.getRun("repair-plan")?.status,"PLAN_APPROVAL_WAITING");assert.equal(host.prompts.length,2);assert.equal(JSON.parse((store.tasks("repair-plan")[0]!.output as {text:string}).text).summary,"repaired");assert.match(JSON.stringify(store.auditEvents("repair-plan")),/ROLE_OUTPUT_REPAIRED/);store.close();});

test("role pipeline safely closes a truncated contract-repair JSON object",async()=>{class TruncatedRepairHost extends StandaloneHostAdapter{override async invokeModel(request:Parameters<StandaloneHostAdapter["invokeModel"]>[0]){const body=JSON.parse(request.prompt) as {candidateOutput?:string};return{requestId:request.requestId,text:body.candidateOutput?'{"summary":"repaired","tasks":[{"id":"task-1","role":"worker","completionCriteria":["done"],"validationCommands":["test"]}':'not-json',tokens:2,cost:0,estimated:false};}}const store=new SQLiteStateStore(":memory:"),controller=new RunController(store,new FakeQueue()),pipeline=new RolePipeline(store,controller,new TruncatedRepairHost());await controller.create(makeRun("truncated-repair","medium"));await pipeline.process("truncated-repair");assert.equal(store.getRun("truncated-repair")?.status,"PLAN_APPROVAL_WAITING");assert.match(JSON.stringify(store.auditEvents("truncated-repair")),/ROLE_OUTPUT_TRUNCATION_RECOVERED/);store.close();});

test("a single approved documentation path can safely wrap a prose Worker response",async()=>{class ProseWorker extends StandaloneHostAdapter{override async invokeModel(request:Parameters<StandaloneHostAdapter["invokeModel"]>[0]){const body=JSON.parse(request.prompt) as {role?:string;candidateOutput?:string};if(body.role==="planner")return{requestId:request.requestId,text:JSON.stringify({summary:"plan",tasks:[{id:"task-1",role:"worker",completionCriteria:["done"],validationCommands:["test"]}]}),tokens:1,cost:0,estimated:false};return{requestId:request.requestId,text:"Release readiness notes with rollback guidance.",tokens:1,cost:0,estimated:false};}}const store=new SQLiteStateStore(":memory:"),controller=new RunController(store,new FakeQueue()),pipeline=new RolePipeline(store,controller,new ProseWorker()),run={...makeRun("document-worker","medium"),checkpoint:{requestedPaths:["docs/release.md"]}};await controller.create(run);await pipeline.process(run.id);pipeline.approvePlan(run.id,"owner");await pipeline.process(run.id);const output=JSON.parse((store.tasks(run.id).find(x=>x.role==="worker")!.output as {text:string}).text) as {changes:Array<{path:string;content:string}>};assert.equal(output.changes[0]?.path,"docs/release.md");assert.match(output.changes[0]?.content??"",/rollback guidance/);assert.match(JSON.stringify(store.auditEvents(run.id)),/ROLE_OUTPUT_DOCUMENT_FALLBACK/);store.close();});

test("an approved directory contains child files but not traversal paths",async()=>{class DirectoryWorker extends StandaloneHostAdapter{override async invokeModel(request:Parameters<StandaloneHostAdapter["invokeModel"]>[0]){const body=JSON.parse(request.prompt) as {role?:string};return{requestId:request.requestId,text:body.role==="planner"?JSON.stringify({summary:"plan",tasks:[{id:"task-1",role:"worker",completionCriteria:["done"],validationCommands:["test"]}]}):JSON.stringify({changes:[{path:"docs/state-snapshot.md",content:"# State"}]}),tokens:1,cost:0,estimated:false};}}const store=new SQLiteStateStore(":memory:"),controller=new RunController(store,new FakeQueue()),pipeline=new RolePipeline(store,controller,new DirectoryWorker()),run={...makeRun("directory-worker","medium"),checkpoint:{requestedPaths:["docs"]}};await controller.create(run);await pipeline.process(run.id);pipeline.approvePlan(run.id,"owner");await pipeline.process(run.id);assert.equal(store.getRun(run.id)?.status,"VALIDATING");store.close();});

test("plan approval cannot be bypassed and role cost cannot exceed durable budget", async () => {
  const store = new SQLiteStateStore(":memory:"); const queue = new FakeQueue(); const controller = new RunController(store, queue); const host = new StandaloneHostAdapter(); const pipeline = new RolePipeline(store, controller, host);
  await controller.create(makeRun("guarded", "high")); await pipeline.process("guarded"); await pipeline.process("guarded"); assert.deepEqual(store.tasks("guarded").map(x => x.role), ["planner"]);
  pipeline.approvePlan("guarded", "owner"); store.db.prepare("UPDATE runs SET budget_limit=spent WHERE id='guarded'").run(); await assert.rejects(pipeline.process("guarded"), /Budget exceeded/); assert.equal(store.getRun("guarded")?.status, "BLOCKED"); assert.equal(store.db.prepare("SELECT count(*) AS n FROM audit_events WHERE type='BUDGET_BLOCKED'").get()?.n, 1); store.close();
});

test("expired plan approval blocks the run before worker execution",async()=>{const store=new SQLiteStateStore(":memory:"),controller=new RunController(store,new FakeQueue()),pipeline=new RolePipeline(store,controller,new StandaloneHostAdapter());await controller.create(makeRun("expired-plan","high"));await pipeline.process("expired-plan");store.db.prepare("UPDATE approvals SET expires_at='2000-01-01T00:00:00.000Z' WHERE id='expired-plan:plan'").run();assert.throws(()=>pipeline.approvePlan("expired-plan","owner"),/expired/);assert.equal(store.getRun("expired-plan")?.status,"BLOCKED");assert.deepEqual(store.tasks("expired-plan").map(x=>x.role),["planner"]);store.close();});

test("Reviewer prompt receives the actual diff, validation, and requirements as untrusted evidence",async()=>{class CaptureHost extends StandaloneHostAdapter{prompts:string[]=[];override async invokeModel(request:Parameters<StandaloneHostAdapter["invokeModel"]>[0]){this.prompts.push(request.prompt);return super.invokeModel(request);}}const store=new SQLiteStateStore(":memory:"),controller=new RunController(store,new FakeQueue()),host=new CaptureHost(),pipeline=new RolePipeline(store,controller,host);await controller.create(makeRun("review-evidence","high"));await pipeline.process("review-evidence");pipeline.approvePlan("review-evidence","owner");await pipeline.process("review-evidence");await pipeline.review("review-evidence",{validation:[{kind:"test",passed:true}],diff:{patch:"diff --git a/a b/a\n+x",patchHash:"hash",files:["a"]},requirements:{goal:"secure change",allowedPaths:["a"]}});const prompt=JSON.parse(host.prompts.at(-1)!) as {role:string;diff?:unknown;untrustedEvidence:{runtimeEvidence:{validation:unknown;diff:{patch:string};requirements:unknown};priorModelOutputs:unknown[]}};assert.equal(prompt.role,"reviewer");assert.equal(prompt.diff,undefined);assert.match(prompt.untrustedEvidence.runtimeEvidence.diff.patch,/diff --git/);assert.deepEqual(prompt.untrustedEvidence.runtimeEvidence.validation,[{kind:"test",passed:true}]);assert.ok(prompt.untrustedEvidence.runtimeEvidence.requirements);assert.equal(prompt.untrustedEvidence.priorModelOutputs.length,2);store.close();});

test("deterministic role gate rejects a Reviewer production patch",async()=>{class BadReviewer extends StandaloneHostAdapter{override async invokeModel(request:Parameters<StandaloneHostAdapter["invokeModel"]>[0]){const prompt=JSON.parse(request.prompt) as {role:string};if(prompt.role==="reviewer")return{requestId:request.requestId,text:JSON.stringify({summary:"review",risks:[],changes:[{path:"src/a.ts",content:"bad"}]}),tokens:1,cost:0,estimated:false};return super.invokeModel(request);}}const store=new SQLiteStateStore(":memory:"),controller=new RunController(store,new FakeQueue()),pipeline=new RolePipeline(store,controller,new BadReviewer());await controller.create(makeRun("qa-no-code","high"));await pipeline.process("qa-no-code");pipeline.approvePlan("qa-no-code","owner");await pipeline.process("qa-no-code");await assert.rejects(pipeline.review("qa-no-code",{validation:[],diff:{files:[]}}),/cannot modify production code/);assert.equal(store.tasks("qa-no-code").find(x=>x.role==="reviewer")?.status,"PENDING");assert.match(JSON.stringify(store.auditEvents("qa-no-code")),/reviewer-production-change/);store.close();});
