import {createHash} from "node:crypto";
import {execFileSync} from "node:child_process";
import {existsSync,lstatSync,readdirSync,readFileSync,realpathSync,statSync} from "node:fs";
import {basename,dirname,relative,resolve,sep} from "node:path";
import type {SQLiteStateStore,StoredTask} from "../../persistence/src/index.js";
import type {ProjectOperations} from "../../project-ops/src/index.js";
import {contextHash,type ContextCandidate} from "../../context-builder/src/index.js";
import type {Role,RoleContextProvider} from "../../role-pipeline/src/index.js";

export const REPOSITORY_OVERVIEW_SCANNER_VERSION="repository-overview-v1";
const LIMITS={maxFiles:500,maxDepth:4,maxFileBytes:128*1024,maxTotalBytes:512*1024,maxEvidenceFiles:40};
const sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex"),slash=(value:string)=>value.split(sep).join("/");
const ignored=new Set([".git","node_modules","dist","build","coverage",".next",".cache",".tools"]);
const evidenceName=(path:string)=>/(^|\/)(readme|claude|agents)(\.|$)|(^|\/)(package(-lock)?\.json|pnpm-lock\.yaml|yarn\.lock|pyproject\.toml|requirements[^/]*\.txt|cargo\.toml|go\.mod|pom\.xml|build\.gradle[^/]*)$/i.test(path);

export interface RepositoryOverview{cacheKey:string;overviewHash:string;trustedMetadata:{repositoryId:string;projectId:string;commitHash:string|null;dirtyFingerprint:string;scannerVersion:string;fileCount:number;totalBytes:number;generatedAt:string;overviewHash:string;source:"git"|"content-fingerprint"};untrustedEvidence:{tree:string[];evidenceFiles:Array<{path:string;content:string;truncated:boolean}>;nearbyModules:string[];excluded:Array<{path:string;reason:string}>;truncated:boolean}}

export class RepositoryOverviewScanner{
 constructor(private readonly store:SQLiteStateStore,private readonly projects:ProjectOperations){this.store.db.exec("CREATE TABLE IF NOT EXISTS repository_overviews_v16(cache_key TEXT PRIMARY KEY,project_id TEXT NOT NULL,overview_hash TEXT NOT NULL,trusted_metadata TEXT NOT NULL,untrusted_evidence TEXT NOT NULL,generated_at TEXT NOT NULL)");}
 scan(runId:string,requestedPaths:string[]=[]):RepositoryOverview|null{const projectId=this.projects.projectForRun(runId),project=projectId?this.projects.project(projectId):null;if(!projectId||!project)return null;const root=realpathSync(project.repoPath),git=this.gitIdentity(root),scan=this.walk(root,requestedPaths),contentFingerprint=sha(scan.files.map(x=>`${x.path}\0${x.hash}`).join("\0")),dirtyFingerprint=git?sha(`${git.dirtyFingerprint}\0${contentFingerprint}`):contentFingerprint,repositoryId=`project:${projectId}`,cacheKey=sha(JSON.stringify({projectId,scannerVersion:REPOSITORY_OVERVIEW_SCANNER_VERSION,commitHash:git?.commitHash??null,dirtyFingerprint})),cached=this.store.db.prepare("SELECT trusted_metadata,untrusted_evidence,overview_hash FROM repository_overviews_v16 WHERE cache_key=?").get(cacheKey) as {trusted_metadata:string;untrusted_evidence:string;overview_hash:string}|undefined;if(cached){const result={cacheKey,overviewHash:cached.overview_hash,trustedMetadata:JSON.parse(cached.trusted_metadata),untrustedEvidence:JSON.parse(cached.untrusted_evidence)} as RepositoryOverview;this.store.audit(runId,"REPOSITORY_OVERVIEW_CACHE_HIT",{cacheKey,overviewHash:result.overviewHash,scannerVersion:REPOSITORY_OVERVIEW_SCANNER_VERSION});return result;}const generatedAt=new Date().toISOString(),hashBody={repositoryId,projectId,commitHash:git?.commitHash??null,dirtyFingerprint,scannerVersion:REPOSITORY_OVERVIEW_SCANNER_VERSION,fileCount:scan.files.length,totalBytes:scan.totalBytes,source:git?"git":"content-fingerprint",untrustedEvidence:scan.evidence},overviewHash=sha(JSON.stringify(hashBody)),trustedMetadata={repositoryId,projectId,commitHash:git?.commitHash??null,dirtyFingerprint,scannerVersion:REPOSITORY_OVERVIEW_SCANNER_VERSION,fileCount:scan.files.length,totalBytes:scan.totalBytes,generatedAt,overviewHash,source:(git?"git":"content-fingerprint") as "git"|"content-fingerprint"},result={cacheKey,overviewHash,trustedMetadata,untrustedEvidence:scan.evidence};this.store.db.prepare("INSERT INTO repository_overviews_v16 VALUES(?,?,?,?,?,?)").run(cacheKey,projectId,overviewHash,JSON.stringify(trustedMetadata),JSON.stringify(scan.evidence),generatedAt);this.store.audit(runId,"REPOSITORY_OVERVIEW_BUILT",{cacheKey,overviewHash,scannerVersion:REPOSITORY_OVERVIEW_SCANNER_VERSION,source:trustedMetadata.source,fileCount:scan.files.length,totalBytes:scan.totalBytes,excluded:scan.evidence.excluded,truncated:scan.evidence.truncated});return result;}
 private gitIdentity(root:string):{commitHash:string;dirtyFingerprint:string}|null{try{const commitHash=execFileSync("git",["rev-parse","--verify","HEAD"],{cwd:root,encoding:"utf8",stdio:["ignore","pipe","ignore"],timeout:3000}).trim();if(!/^[a-f0-9]{40,64}$/i.test(commitHash))return null;const status=execFileSync("git",["status","--porcelain=v1","-z","--untracked-files=all"],{cwd:root,encoding:"utf8",stdio:["ignore","pipe","ignore"],timeout:5000});return{commitHash:commitHash.toLowerCase(),dirtyFingerprint:sha(status)};}catch{return null;}}
 private walk(root:string,requestedPaths:string[]){const files:Array<{path:string;hash:string}>=[],tree:string[]=[],excluded:Array<{path:string;reason:string}>=[],evidenceFiles:Array<{path:string;content:string;truncated:boolean}>=[];let totalBytes=0,evidenceBytes=0,truncated=false;const safeRequested=new Set(requestedPaths.map(x=>slash(x).replace(/^\.\//,"")).filter(x=>x&&!x.startsWith("../")&&!x.includes("/../"))),nearbyDirs=new Set([...safeRequested].map(x=>dirname(x)==="."?"":slash(dirname(x))));const visit=(dir:string,depth:number)=>{if(depth>LIMITS.maxDepth){excluded.push({path:slash(relative(root,dir)),reason:"depth"});truncated=true;return;}let entries;try{entries=readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name));}catch{excluded.push({path:slash(relative(root,dir)),reason:"unreadable"});return;}for(const entry of entries){if(files.length>=LIMITS.maxFiles){truncated=true;return;}const absolute=resolve(dir,entry.name),path=slash(relative(root,absolute));if(entry.isSymbolicLink()){excluded.push({path,reason:"symlink"});continue;}if(entry.isDirectory()){if(ignored.has(entry.name)){excluded.push({path,reason:"ignored"});continue;}if(depth>0&&existsSync(resolve(absolute,".git"))){excluded.push({path,reason:"nested-repository"});continue;}visit(absolute,depth+1);continue;}if(!entry.isFile())continue;let size=0;try{size=lstatSync(absolute).size;}catch{continue;}if(size>LIMITS.maxFileBytes){excluded.push({path,reason:"file-size"});continue;}let buffer:Buffer;try{buffer=readFileSync(absolute);}catch{excluded.push({path,reason:"unreadable"});continue;}if(buffer.includes(0)){excluded.push({path,reason:"binary"});continue;}files.push({path,hash:sha(buffer)});tree.push(path);totalBytes+=size;const selected=evidenceName(path)||safeRequested.has(path)||nearbyDirs.has(slash(dirname(path)));if(selected&&evidenceFiles.length<LIMITS.maxEvidenceFiles&&evidenceBytes<LIMITS.maxTotalBytes){const remaining=LIMITS.maxTotalBytes-evidenceBytes,content=buffer.subarray(0,remaining).toString("utf8");evidenceFiles.push({path,content,truncated:content.length<buffer.toString("utf8").length});evidenceBytes+=Buffer.byteLength(content);if(content.length<buffer.toString("utf8").length)truncated=true;}}};visit(root,0);const nearbyModules=tree.filter(path=>nearbyDirs.has(slash(dirname(path)))).slice(0,100);return{files,totalBytes,evidence:{tree,evidenceFiles,nearbyModules,excluded,truncated}};}
}

export class RepositoryRoleContext implements RoleContextProvider{
 private readonly scanner:RepositoryOverviewScanner;
 constructor(private readonly store:SQLiteStateStore,private readonly projects:ProjectOperations){this.scanner=new RepositoryOverviewScanner(store,projects);}
 candidates(runId:string,_role:Role,_task:StoredTask):ContextCandidate[]{const run=this.store.getRun(runId),paths=Array.isArray(run?.checkpoint?.requestedPaths)?run!.checkpoint!.requestedPaths.filter((x):x is string=>typeof x==="string"):[],overview=this.scanner.scan(runId,paths);if(!overview)return[];const trusted=JSON.stringify(overview.trustedMetadata),untrusted=JSON.stringify(overview.untrustedEvidence);return[{id:`repo-overview-meta:${overview.cacheKey}`,kind:"requirement",content:trusted,source:`system:${REPOSITORY_OVERVIEW_SCANNER_VERSION}`,contentHash:contextHash(trusted),trust:"trusted"},{id:`repo-overview-evidence:${overview.cacheKey}`,kind:"tool-output",content:untrusted,source:"repository-overview",contentHash:contextHash(untrusted),trust:"untrusted"}];}
}
