import type { RiskLevel } from "../../contracts/src/index.js";
import type { StateStore, StoredRun } from "../../persistence/src/index.js";
import type { RunController } from "../../runtime/src/index.js";
export interface OrganizationProfile{id:string;name:string;responsibilities:{planner:string;worker:string;reviewer:string};mediumFileThreshold:number}
export interface PolicyInput{goal:string;requestedPaths:string[];requestedRisk?:RiskLevel}
export interface PolicyDecision{risk:RiskLevel;inferredRisk:RiskLevel;managementDepth:"minimal"|"managed"|"executive";requiredRoles:Array<"planner"|"worker"|"reviewer">;approvals:Array<"plan"|"result">;reasons:string[];profileId:string}
export const DEFAULT_ORGANIZATION:OrganizationProfile={id:"default",name:"Default Engineering Organization",responsibilities:{planner:"delivery-planning",worker:"implementation",reviewer:"independent-risk-review"},mediumFileThreshold:3};
const rank:Record<RiskLevel,number>={low:0,medium:1,high:2,critical:3},byRank=(n:number):RiskLevel=>n>=3?"critical":n===2?"high":n===1?"medium":"low";
export class PolicyEngine{constructor(private readonly profile:OrganizationProfile=DEFAULT_ORGANIZATION){}decide(input:PolicyInput):PolicyDecision{const text=`${input.goal} ${input.requestedPaths.join(" ")}`.toLowerCase(),reasons:string[]=[];let inferred:RiskLevel="low";if(/credential|secret|payment|deploy|production|\.env|private.?key|비밀|결제|배포|운영/i.test(text)){inferred="critical";reasons.push("critical-production-or-secret-domain");}else if(/auth|permission|security|database|schema|migration|인증|권한|보안|데이터베이스|스키마/i.test(text)){inferred="high";reasons.push("sensitive-domain-or-path");}else if(input.requestedPaths.length>=this.profile.mediumFileThreshold||/refactor|dependency|config|api|리팩터|의존성|설정|공통/i.test(text)){inferred="medium";reasons.push("cross-cutting-or-multi-file");}else reasons.push("small-contained-change");const risk=byRank(Math.max(rank[inferred],rank[input.requestedRisk??"low"]));if(input.requestedRisk&&rank[input.requestedRisk]<rank[inferred])reasons.push("risk-downgrade-rejected");return{risk,inferredRisk:inferred,managementDepth:risk==="high"||risk==="critical"?"executive":risk==="medium"?"managed":"minimal",requiredRoles:risk==="high"||risk==="critical"?["planner","worker","reviewer"]:risk==="medium"?["planner","worker"]:["worker"],approvals:["plan","result"],reasons,profileId:this.profile.id};}}
export interface IntakeRequest extends PolicyInput{id:string;requestId:string;budgetLimit:number}
export class RunIntakeService{constructor(private readonly store:StateStore,private readonly controller:RunController,private readonly policy:PolicyEngine=new PolicyEngine()){}async create(input:IntakeRequest,options:{deferEnqueue?:boolean}={}):Promise<PolicyDecision>{const decision=this.policy.decide(input),run:StoredRun={id:input.id,requestId:input.requestId,goal:input.goal,risk:decision.risk,status:"CREATED",budgetLimit:input.budgetLimit,spent:0,checkpoint:{requestedPaths:input.requestedPaths,policy:decision}};await this.controller.create(run,options);this.store.audit(input.id,"POLICY_DECIDED",{requestedRisk:input.requestedRisk??null,...decision});return decision;}}
