import {useEffect,useMemo,useState} from "react";
import {apiGet,apiPost} from "../api.ts";
import {incidentLabel} from "../eventLabels.ts";
import {uuid} from "../format.ts";
import VirtualEventTimeline from "./VirtualEventTimeline.tsx";

type Staff={principalId:string;role:string;specialty:string|null;characterStyle:string;placement:{floor:number;zone:string;desk:number}};
type Floor={floor:number;name:string;unlockLevel:number;zones:string[]};
type Decoration={id:string;floor:number;zone:string;kind:string;x:number;y:number};
type Snapshot={floors:Floor[];staff:Staff[];decorations:Decoration[];projects:Array<{projectId:string;priority:number}>;capacity:{staff:number;target:number};theme:string;availableThemes:string[]};
type Phase="idle"|"planning"|"working"|"validating"|"reviewing"|"approval"|"blocked"|"completed";
type Projection={phase:Phase;activeAgentId:string|null};
type Incident={sourceEventId:string;runId:string|null;severity:"warning"|"critical";reason:string;resolvedAt:string|null;resolution:string|null};
type Game={incidents:Incident[]};
type RunDetail={run:{status:string}};

export default function AdvancedOfficePanel({companyId,actorId}:{companyId:string;actorId:string}){
 const[data,setData]=useState<Snapshot|null>(null),[projection,setProjection]=useState<Projection|null>(null),[incidents,setIncidents]=useState<Incident[]>([]),[floor,setFloor]=useState(1),[zone,setZone]=useState("all"),[pan,setPan]=useState({x:0,y:0}),[selectedDecoration,setSelectedDecoration]=useState<string|null>(null),[message,setMessage]=useState("");
 const load=async()=>{try{const[office,state,game]=await Promise.all([apiGet<Snapshot>(`/api/companies/${encodeURIComponent(companyId)}/office?actor=${encodeURIComponent(actorId)}`),apiGet<Projection>(`/api/companies/${encodeURIComponent(companyId)}/office-projection?actor=${encodeURIComponent(actorId)}`),apiGet<Game>(`/api/companies/${encodeURIComponent(companyId)}/game-progression?actor=${encodeURIComponent(actorId)}`)]);setData(office);setProjection(state);setIncidents(game.incidents);setMessage("");}catch(e){setMessage(e instanceof Error?e.message:String(e));}};
 useEffect(()=>{void load()},[companyId,actorId]);
 const selected=data?.floors.find(x=>x.floor===floor),visible=useMemo(()=>data?.staff.filter(x=>x.placement.floor===floor&&(zone==="all"||x.placement.zone===zone))??[],[data,floor,zone]);
 async function setTheme(theme:string){await apiPost(`/api/companies/${encodeURIComponent(companyId)}/office/theme`,{actorId,theme});await load()}
 async function hire(){const principalId=prompt("새 직원 ID");if(!principalId)return;await apiPost(`/api/companies/${encodeURIComponent(companyId)}/office/hire`,{actorId,principalId,departmentId:null,role:"member",specialty:null});await load()}
 async function decorate(){const kind=prompt("장식 종류","plant");if(!kind||!selected)return;await apiPost(`/api/companies/${encodeURIComponent(companyId)}/office/decorate`,{actorId,floor,zone:zone==="all"?selected.zones[0]:zone,kind,x:Math.round(-pan.x+40),y:Math.round(-pan.y+40)});await load()}
 async function moveDecoration(item:Decoration,dx:number,dy:number){await apiPost(`/api/companies/${encodeURIComponent(companyId)}/office/move-decoration`,{actorId,id:item.id,floor:item.floor,zone:item.zone,x:item.x+dx,y:item.y+dy});await load()}
 async function removeDecoration(id:string){await apiPost(`/api/companies/${encodeURIComponent(companyId)}/office/remove-decoration`,{actorId,id});setSelectedDecoration(null);await load()}
 async function resolveIncident(item:Incident){if(!item.runId)return;const resolution=prompt("Incident 해결 내용");if(!resolution)return;const detail=await apiGet<RunDetail>(`/api/runs/${encodeURIComponent(item.runId)}`);await apiPost(`/api/runs/${encodeURIComponent(item.runId)}/interventions/resolve-incident`,{requestId:uuid(),actorId,reason:"incident response",expectedStatus:detail.run.status,incidentId:item.sourceEventId,resolution});await load()}
 const activity=(person:Staff)=>person.principalId===projection?.activeAgentId?projection.phase:"idle";
 return <section className={`card advanced-office theme-${data?.theme??"classic"}`} aria-labelledby="advanced-office-title">
  <header><div><h2 id="advanced-office-title">다층 오피스 운영</h2><p aria-live="polite">직원 {data?.capacity.staff??0}/{data?.capacity.target??30}명 · 프로젝트 {data?.projects.length??0}개 · {selected?.name??"로딩 중"}</p></div><div><label>테마<select value={data?.theme??"classic"} onChange={e=>void setTheme(e.target.value)}>{data?.availableThemes.map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>void hire()}>직원 채용</button><button className="secondary" onClick={()=>void decorate()}>장식 배치</button></div></header>
  <div className="office-floor-controls" role="toolbar" aria-label="층과 카메라 제어">{data?.floors.map(x=><button key={x.floor} aria-pressed={floor===x.floor} onClick={()=>{setFloor(x.floor);setZone("all")}}>{x.floor}F {x.name}</button>)}<label>구역<select value={zone} onChange={e=>setZone(e.target.value)}><option value="all">전체</option>{selected?.zones.map(x=><option key={x}>{x}</option>)}</select></label><button aria-label="카메라 왼쪽" onClick={()=>setPan(x=>({...x,x:x.x+80}))}>←</button><button aria-label="카메라 위" onClick={()=>setPan(x=>({...x,y:x.y+60}))}>↑</button><button aria-label="카메라 아래" onClick={()=>setPan(x=>({...x,y:x.y-60}))}>↓</button><button aria-label="카메라 오른쪽" onClick={()=>setPan(x=>({...x,x:x.x-80}))}>→</button><button onClick={()=>setPan({x:0,y:0})}>중앙</button></div>
  <div className="advanced-office-viewport" tabIndex={0} aria-label={`${selected?.name??"오피스"}, ${visible.length}명 표시`}><div style={{transform:`translate(${pan.x}px,${pan.y}px)`}}>{selected?.zones.map((item,index)=><section className="office-zone" key={item} aria-label={`${item} 구역`} style={{left:(index%3)*250,top:Math.floor(index/3)*190}}><h3>{item}</h3>{visible.filter(x=>x.placement.zone===item).map(person=><button key={person.principalId} className={`office-person style-${person.characterStyle} activity-${activity(person)}`} title={`${person.role}${person.specialty?` · ${person.specialty}`:""}`}><span className="person-sprite" aria-hidden="true">{person.characterStyle==="specialist"?"◆":"●"}</span>{person.principalId}<small>{person.specialty??person.role} · {activity(person)}</small></button>)}</section>)}{data?.decorations.filter(x=>x.floor===floor).map(item=><button className={`office-decoration ${selectedDecoration===item.id?"selected":""}`} key={item.id} style={{left:item.x,top:item.y}} aria-label={`${item.kind} 장식 편집`} onClick={()=>setSelectedDecoration(item.id)}>🌿</button>)}</div></div>
  {selectedDecoration&&(()=>{const item=data?.decorations.find(x=>x.id===selectedDecoration);return item?<div className="decoration-editor" role="toolbar" aria-label="선택 장식 편집"><button onClick={()=>void moveDecoration(item,-10,0)}>←</button><button onClick={()=>void moveDecoration(item,0,-10)}>↑</button><button onClick={()=>void moveDecoration(item,0,10)}>↓</button><button onClick={()=>void moveDecoration(item,10,0)}>→</button><button className="danger" onClick={()=>void removeDecoration(item.id)}>삭제</button></div>:null})()}
  <section className="incident-response" aria-label="Incident 대응"><h3>Incident 대응</h3>{incidents.length?incidents.slice(-5).reverse().map(item=><article key={item.sourceEventId} className={`incident incident-${item.severity}`}><strong>{item.severity}</strong><span title={item.reason}>{incidentLabel(item.reason)}</span>{item.resolvedAt?<small>해결: {item.resolution}</small>:<button disabled={!item.runId} onClick={()=>void resolveIncident(item)}>해결 기록</button>}</article>):<p>현재 Incident가 없습니다.</p>}</section>
  <VirtualEventTimeline companyId={companyId} actorId={actorId}/>
  <details><summary>화면 읽기 지원 오피스 요약</summary><ul>{visible.map(x=><li key={x.principalId}>{x.principalId}: {x.placement.zone}, {x.specialty??x.role}, {activity(x)}</li>)}</ul></details>{message&&<p role="alert" className="error">{message}</p>}
 </section>;
}
