import {createHash} from "node:crypto";
import type {DatabaseSync} from "node:sqlite";
import type {CompanyOperations} from "../../company-ops/src/index.js";

export const REPORT_CONTRACT_VERSION="deterministic-report-v1",REPORT_PROJECTOR_VERSION="report-projector-v1";
const json=(value:unknown)=>JSON.stringify(value??null),parse=<T>(value:unknown)=>JSON.parse(String(value)) as T,sha=(value:string)=>createHash("sha256").update(value).digest("hex"),now=()=>new Date().toISOString();
export type ReportStatus="unread"|"read"|"acknowledged"|"escalated"|"unroutable";
export interface DeterministicReport{id:string;companyId:string;sourceEventId:string;sourceCursor:number;reportType:"status"|"completion"|"blocker"|"decision";recipientId:string|null;status:ReportStatus;currentState:string;completed:string[];blocked:string[];decisionRequired:boolean;evidenceIds:string[];nextAction:string;routing:{candidates:string[];selectedIndex:number;reason:string;sourcePrincipalId:string|null;sourceDepartmentId:string|null};contractVersion:string;projectorVersion:string;createdAt:string;updatedAt:string}

export class ReportingProjector{
 constructor(private readonly db:DatabaseSync,private readonly companies:CompanyOperations){this.db.exec(`CREATE TABLE IF NOT EXISTS report_projector_state_v17(company_id TEXT PRIMARY KEY,projector_version TEXT NOT NULL,last_cursor INTEGER NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS deterministic_reports_v17(id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies_v4(id) ON DELETE CASCADE,source_event_id TEXT NOT NULL,source_cursor INTEGER NOT NULL,report_type TEXT NOT NULL,recipient_id TEXT,status TEXT NOT NULL,current_state TEXT NOT NULL,completed TEXT NOT NULL,blocked TEXT NOT NULL,decision_required INTEGER NOT NULL,evidence_ids TEXT NOT NULL,next_action TEXT NOT NULL,routing TEXT NOT NULL,contract_version TEXT NOT NULL,projector_version TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(source_event_id,report_type,recipient_id,contract_version));CREATE INDEX IF NOT EXISTS idx_reports_v17_recipient ON deterministic_reports_v17(company_id,recipient_id,status,source_cursor);`);}
 catchUp(companyId:string):{processed:number;created:number;lastCursor:number}{const state=this.db.prepare("SELECT projector_version,last_cursor FROM report_projector_state_v17 WHERE company_id=?").get(companyId) as {projector_version:string;last_cursor:number}|undefined;if(state&&state.projector_version!==REPORT_PROJECTOR_VERSION)return this.rebuild(companyId);let cursor=Number(state?.last_cursor??0),processed=0,created=0;for(;;){const rows=this.db.prepare("SELECT cursor,event_id,type,aggregate_type,aggregate_id,payload,created_at FROM events_v6 WHERE tenant_id=? AND cursor>? ORDER BY cursor LIMIT 500").all(companyId,cursor) as Array<{cursor:number;event_id:string;type:string;aggregate_type:string;aggregate_id:string;payload:string;created_at:string}>;if(!rows.length)break;this.db.exec("BEGIN IMMEDIATE");try{for(const row of rows){processed++;if(this.project(companyId,row))created++;cursor=Number(row.cursor);}this.db.prepare("INSERT INTO report_projector_state_v17 VALUES(?,?,?,?) ON CONFLICT(company_id) DO UPDATE SET projector_version=excluded.projector_version,last_cursor=excluded.last_cursor,updated_at=excluded.updated_at").run(companyId,REPORT_PROJECTOR_VERSION,cursor,now());this.db.exec("COMMIT");}catch(error){this.db.exec("ROLLBACK");throw error;}if(rows.length<500)break;}return{processed,created,lastCursor:cursor};}
 rebuild(companyId:string):{processed:number;created:number;lastCursor:number}{this.db.exec("BEGIN IMMEDIATE");try{this.db.prepare("DELETE FROM deterministic_reports_v17 WHERE company_id=?").run(companyId);this.db.prepare("DELETE FROM report_projector_state_v17 WHERE company_id=?").run(companyId);this.db.exec("COMMIT");}catch(error){this.db.exec("ROLLBACK");throw error;}return this.catchUp(companyId);}
 reportsForActor(companyId:string,actorId:string):DeterministicReport[]{this.companies.require(companyId,actorId,"view");this.catchUp(companyId);const owner=this.companies.role(companyId,actorId)==="owner",rows=this.db.prepare(`SELECT * FROM deterministic_reports_v17 WHERE company_id=? AND (recipient_id=?${owner?" OR recipient_id IS NULL":""}) ORDER BY source_cursor DESC,id`).all(companyId,actorId) as Record<string,unknown>[];return rows.map(row=>this.record(row));}
 reportForActor(companyId:string,reportId:string,actorId:string):DeterministicReport{return this.authorized(companyId,reportId,actorId);}
 read(companyId:string,reportId:string,actorId:string):DeterministicReport{const report=this.authorized(companyId,reportId,actorId);if(report.status==="unread"||report.status==="escalated")this.db.prepare("UPDATE deterministic_reports_v17 SET status='read',updated_at=? WHERE id=?").run(now(),reportId);this.audit(companyId,"REPORT_READ",{reportId,actorId});return this.byId(reportId)!;}
 acknowledge(companyId:string,reportId:string,actorId:string):DeterministicReport{const report=this.authorized(companyId,reportId,actorId);if(report.status==="unroutable")throw new Error("Unroutable report cannot be acknowledged");this.db.prepare("UPDATE deterministic_reports_v17 SET status='acknowledged',updated_at=? WHERE id=?").run(now(),reportId);this.audit(companyId,"REPORT_ACKNOWLEDGED",{reportId,actorId});return this.byId(reportId)!;}
 escalate(companyId:string,reportId:string,actorId:string):DeterministicReport{const report=this.authorized(companyId,reportId,actorId),nextIndex=report.routing.selectedIndex+1,next=report.routing.candidates[nextIndex];if(!next)throw new Error("Report escalation route exhausted");const routing={...report.routing,selectedIndex:nextIndex,reason:"manual-escalation"};this.db.prepare("UPDATE deterministic_reports_v17 SET recipient_id=?,status='escalated',routing=?,updated_at=? WHERE id=?").run(next,json(routing),now(),reportId);this.audit(companyId,"REPORT_ESCALATED",{reportId,actorId,from:report.recipientId,to:next});return this.byId(reportId)!;}
 private project(companyId:string,row:{cursor:number;event_id:string;type:string;aggregate_type:string;aggregate_id:string;payload:string;created_at:string}):boolean{const payload=parse<Record<string,unknown>>(row.payload),classification=this.classify(row.type,payload);if(!classification)return false;const context=this.sourceContext(companyId,row.aggregate_type,row.aggregate_id,payload),route=this.route(companyId,context.principalId,context.departmentId),recipientId=route.candidates[0]??null,status:ReportStatus=recipientId?"unread":"unroutable",id=sha(`${row.event_id}|${classification.reportType}|${recipientId??""}|${REPORT_CONTRACT_VERSION}`),evidenceIds=[row.event_id,...Object.entries(payload).filter(([key,value])=>/Id$/.test(key)&&typeof value==="string").map(([,value])=>String(value))].filter((value,index,all)=>all.indexOf(value)===index).sort(),routing={candidates:route.candidates,selectedIndex:recipientId?0:-1,reason:route.reason,sourcePrincipalId:context.principalId,sourceDepartmentId:context.departmentId};const result=this.db.prepare("INSERT OR IGNORE INTO deterministic_reports_v17 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,companyId,row.event_id,row.cursor,classification.reportType,recipientId,status,classification.currentState,json(classification.completed),json(classification.blocked),classification.decisionRequired?1:0,json(evidenceIds),classification.nextAction,json(routing),REPORT_CONTRACT_VERSION,REPORT_PROJECTOR_VERSION,row.created_at,row.created_at);if(!recipientId)this.audit(companyId,"REPORT_UNROUTABLE",{reportId:id,sourceEventId:row.event_id,reason:route.reason});else this.audit(companyId,"REPORT_DELIVERED",{reportId:id,sourceEventId:row.event_id,recipientId,candidates:route.candidates,reason:route.reason});return result.changes===1;}
 private classify(type:string,payload:Record<string,unknown>):Omit<DeterministicReport,"id"|"companyId"|"sourceEventId"|"sourceCursor"|"recipientId"|"status"|"evidenceIds"|"routing"|"contractVersion"|"projectorVersion"|"createdAt"|"updatedAt">|null{const canonical=type.toLowerCase().replaceAll("_","."),to=String(payload.to??payload.status??""),decision=/approval|decision|patch\.hash\.blocked|stale\.approval\.blocked|result\.hash\.bound/.test(canonical)||/APPROVAL_WAITING/.test(to),failure=/failed|blocked|denied|exceeded|incident/.test(canonical)||/FAILED|BLOCKED/.test(to),completion=canonical==="workflow.completed"||to==="COMPLETED";if(!failure&&!completion&&!decision&&!/run\.transitioned|task\.transitioned|validation\.completed|meeting\./.test(canonical))return null;return{reportType:decision?"decision":failure?"blocker":completion?"completion":"status",currentState:to||type,completed:completion?[String(payload.goal??payload.taskId??"workflow completed")]:[],blocked:failure?[String(payload.reason??type)]:[],decisionRequired:decision,nextAction:decision?"Review evidence and record a decision":failure?"Investigate evidence and assign recovery":completion?"Verify completion evidence and acknowledge":"Monitor the next state transition"};}
 private sourceContext(companyId:string,aggregateType:string,aggregateId:string,payload:Record<string,unknown>):{principalId:string|null;departmentId:string|null}{
  const runId=String(payload.runId??(aggregateType==="run"?aggregateId:""));
  const runTask=runId?this.db.prepare("SELECT id,project_id FROM board_tasks_v3 WHERE run_id=?").get(runId) as {id:string;project_id:string}|undefined:undefined;
  const taskId=String(payload.taskId??runTask?.id??"");
  const task=taskId?this.db.prepare("SELECT project_id FROM board_tasks_v3 WHERE id=?").get(taskId) as {project_id:string}|undefined:undefined;
  const projectId=String(payload.projectId??task?.project_id??runTask?.project_id??(aggregateType==="project"?aggregateId:""));
  const assigned=taskId?this.db.prepare("SELECT principal_id FROM assignments_v3 WHERE task_id=? AND responsibility='executor' ORDER BY principal_id LIMIT 1").get(taskId) as {principal_id:string}|undefined:undefined;
  const principalId=typeof payload.agentId==="string"?payload.agentId:typeof payload.principalId==="string"?payload.principalId:assigned?.principal_id??null;
  const member=principalId?this.db.prepare("SELECT department_id FROM company_members_v4 WHERE company_id=? AND principal_id=?").get(companyId,principalId) as {department_id:string|null}|undefined:undefined;
  const link=projectId?this.db.prepare("SELECT department_id FROM company_projects_v4 WHERE company_id=? AND project_id=?").get(companyId,projectId) as {department_id:string}|undefined:undefined;
  return{principalId,departmentId:member?.department_id??link?.department_id??null};
 }
 private route(companyId:string,sourcePrincipalId:string|null,departmentId:string|null):{candidates:string[];reason:string}{const candidates:string[]=[],seen=new Set<string>();let current=departmentId,cycle=false;while(current){if(seen.has(current)){cycle=true;break;}seen.add(current);const managers=this.db.prepare("SELECT principal_id FROM company_members_v4 WHERE company_id=? AND department_id=? AND role='department-manager' ORDER BY principal_id").all(companyId,current) as Array<{principal_id:string}>;for(const item of managers)if(item.principal_id!==sourcePrincipalId&&!candidates.includes(item.principal_id))candidates.push(item.principal_id);current=(this.db.prepare("SELECT parent_id FROM departments_v4 WHERE id=? AND company_id=?").get(current,companyId) as {parent_id:string|null}|undefined)?.parent_id??null;}if(cycle)return{candidates:[],reason:"department-cycle"};for(const role of ["executive","owner"]){const members=this.db.prepare("SELECT principal_id FROM company_members_v4 WHERE company_id=? AND role=? ORDER BY principal_id").all(companyId,role) as Array<{principal_id:string}>;for(const member of members)if(member.principal_id!==sourcePrincipalId&&!candidates.includes(member.principal_id))candidates.push(member.principal_id);}return{candidates,reason:candidates.length?(seen.size?"department-chain-fallback":"company-role-fallback"):"no-report-recipient"};}
 private authorized(companyId:string,reportId:string,actorId:string):DeterministicReport{this.companies.require(companyId,actorId,"view");const report=this.byId(reportId);if(!report||report.companyId!==companyId||(report.recipientId!==actorId&&!(report.recipientId===null&&this.companies.role(companyId,actorId)==="owner")))throw new Error("Report access denied");return report;}
 private byId(id:string):DeterministicReport|null{const row=this.db.prepare("SELECT * FROM deterministic_reports_v17 WHERE id=?").get(id) as Record<string,unknown>|undefined;return row?this.record(row):null;}
 private record(row:Record<string,unknown>):DeterministicReport{return{id:String(row.id),companyId:String(row.company_id),sourceEventId:String(row.source_event_id),sourceCursor:Number(row.source_cursor),reportType:String(row.report_type) as DeterministicReport["reportType"],recipientId:row.recipient_id===null?null:String(row.recipient_id),status:String(row.status) as ReportStatus,currentState:String(row.current_state),completed:parse(row.completed),blocked:parse(row.blocked),decisionRequired:Number(row.decision_required)===1,evidenceIds:parse(row.evidence_ids),nextAction:String(row.next_action),routing:parse(row.routing),contractVersion:String(row.contract_version),projectorVersion:String(row.projector_version),createdAt:String(row.created_at),updatedAt:String(row.updated_at)};}
 private audit(companyId:string,type:string,payload:unknown):void{this.db.prepare("INSERT INTO company_audit_v4(company_id,type,payload,created_at) VALUES(?,?,?,?)").run(companyId,type,json(payload),now());}
}
