import {createHash,randomUUID} from "node:crypto";
import type {DatabaseSync} from "node:sqlite";
import type {CompanyOperations} from "../../company-ops/src/index.js";

const now=()=>new Date().toISOString(),json=(value:unknown)=>JSON.stringify(value),parse=<T>(value:unknown)=>JSON.parse(String(value)) as T,sha=(value:string)=>createHash("sha256").update(value).digest("hex");
export const DELEGATION_CONTRACT_VERSION="delegation-handoff-v1";
export type DelegationStatus="pending-review"|"approved"|"rejected"|"reassigned"|"in-progress"|"partially-completed"|"completed"|"expired"|"handoff-failed";
export interface DelegationEvidence{id:string;provenance:string;trust:"untrusted-evidence";sha256:string}
export interface DelegationRecord{id:string;requestId:string;companyId:string;sourceDepartmentId:string;targetDepartmentId:string;ownerId:string;assigneeId:string|null;completionCriteria:string[];allowedScope:string[];evidence:DelegationEvidence[];deadline:string;status:DelegationStatus;reviewedBy:string|null;reviewReason:string|null;completionEvidenceIds:string[];failureReason:string|null;contractVersion:string;snapshotHash:string;createdAt:string;updatedAt:string}

export class DelegationService{
 constructor(private readonly db:DatabaseSync,private readonly companies:CompanyOperations){this.db.exec(`CREATE TABLE IF NOT EXISTS delegations_v17(id TEXT PRIMARY KEY,request_id TEXT NOT NULL UNIQUE,company_id TEXT NOT NULL REFERENCES companies_v4(id) ON DELETE CASCADE,source_department_id TEXT NOT NULL,target_department_id TEXT NOT NULL,owner_id TEXT NOT NULL,assignee_id TEXT,completion_criteria TEXT NOT NULL,allowed_scope TEXT NOT NULL,evidence TEXT NOT NULL,deadline TEXT NOT NULL,status TEXT NOT NULL,reviewed_by TEXT,review_reason TEXT,completion_evidence_ids TEXT NOT NULL,failure_reason TEXT,contract_version TEXT NOT NULL,snapshot_hash TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_delegations_v17_company_status ON delegations_v17(company_id,status,deadline);CREATE TABLE IF NOT EXISTS delegation_transitions_v17(seq INTEGER PRIMARY KEY AUTOINCREMENT,delegation_id TEXT NOT NULL REFERENCES delegations_v17(id) ON DELETE CASCADE,from_status TEXT,to_status TEXT NOT NULL,actor_id TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL);`);}
 create(input:{requestId:string;companyId:string;sourceDepartmentId:string;targetDepartmentId:string;ownerId:string;completionCriteria:string[];allowedScope:string[];evidence:Array<{id:string;provenance:string;contentHash?:string}>;deadline:string},actorId:string):DelegationRecord{const existing=this.byRequest(input.requestId);if(existing){if(existing.companyId!==input.companyId)throw new Error("Cross-company delegation request blocked");return existing;}this.companies.require(input.companyId,actorId,"view");if(input.sourceDepartmentId===input.targetDepartmentId)throw new Error("Cross-department delegation requires different departments");this.assertDepartment(input.companyId,input.sourceDepartmentId);this.assertDepartment(input.companyId,input.targetDepartmentId);const actor=this.member(input.companyId,actorId),owner=this.member(input.companyId,input.ownerId);if(!actor||!(actor.role==="owner"||actor.role==="executive"||actor.role==="department-manager"&&actor.departmentId===input.sourceDepartmentId))throw new Error("Delegation source authority denied");if(!owner)throw new Error("Delegation owner must be a company member");if(!input.completionCriteria.length||input.completionCriteria.some(x=>!x.trim()))throw new Error("Delegation completion criteria required");if(!input.allowedScope.length||input.allowedScope.some(x=>!x.trim()))throw new Error("Delegation allowed scope required");if(!Number.isFinite(Date.parse(input.deadline))||Date.parse(input.deadline)<=Date.now())throw new Error("Delegation deadline must be in the future");const evidence=input.evidence.map(item=>({id:item.id,provenance:item.provenance,trust:"untrusted-evidence" as const,sha256:item.contentHash??sha(`${item.id}|${item.provenance}`)}));if(evidence.some(x=>!x.id||!x.provenance))throw new Error("Delegation evidence provenance required");const timestamp=now(),snapshot={companyId:input.companyId,sourceDepartmentId:input.sourceDepartmentId,targetDepartmentId:input.targetDepartmentId,ownerId:input.ownerId,completionCriteria:[...input.completionCriteria],allowedScope:[...input.allowedScope],evidence,deadline:input.deadline,contractVersion:DELEGATION_CONTRACT_VERSION},record:DelegationRecord={id:randomUUID(),requestId:input.requestId,...snapshot,assigneeId:null,status:"pending-review",reviewedBy:null,reviewReason:null,completionEvidenceIds:[],failureReason:null,snapshotHash:sha(json(snapshot)),createdAt:timestamp,updatedAt:timestamp};this.db.prepare("INSERT INTO delegations_v17 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(record.id,record.requestId,record.companyId,record.sourceDepartmentId,record.targetDepartmentId,record.ownerId,null,json(record.completionCriteria),json(record.allowedScope),json(record.evidence),record.deadline,record.status,null,null,json([]),null,record.contractVersion,record.snapshotHash,timestamp,timestamp);this.transitionAudit(record,null,"pending-review",actorId,{requestId:input.requestId});return record;}
 list(companyId:string,actorId:string):DelegationRecord[]{this.companies.require(companyId,actorId,"view");this.expireDue(companyId);const member=this.member(companyId,actorId)!,where=member.role==="owner"||member.role==="executive"?"company_id=?":"company_id=? AND (owner_id=? OR assignee_id=? OR source_department_id=? OR target_department_id=?)",args=member.role==="owner"||member.role==="executive"?[companyId]:[companyId,actorId,actorId,member.departmentId,member.departmentId];return(this.db.prepare(`SELECT * FROM delegations_v17 WHERE ${where} ORDER BY created_at DESC,id`).all(...args) as Record<string,unknown>[]).map(x=>this.record(x));}
 review(companyId:string,id:string,actorId:string,input:{decision:"approve"|"reject";assigneeId?:string;reason:string}):DelegationRecord{const item=this.authorized(companyId,id,actorId),actor=this.member(companyId,actorId);if(!actor||actor.role!=="department-manager"||actor.departmentId!==item.targetDepartmentId)throw new Error("Target department manager review required");if(item.status!=="pending-review")throw new Error("Delegation is not pending review");if(!input.reason.trim())throw new Error("Delegation review reason required");if(input.decision==="reject")return this.update(item,actorId,"rejected",{reviewedBy:actorId,reviewReason:input.reason});if(!input.assigneeId)throw new Error("Delegation assignee required");this.assertTargetAssignee(item,input.assigneeId);return this.update(item,actorId,"approved",{assigneeId:input.assigneeId,reviewedBy:actorId,reviewReason:input.reason});}
 act(companyId:string,id:string,actorId:string,input:{action:"start"|"reassign"|"partial"|"complete"|"fail";assigneeId?:string;evidenceIds?:string[];completedCriteria?:string[];reason?:string}):DelegationRecord{const item=this.authorized(companyId,id,actorId),actor=this.member(companyId,actorId)!;if(Date.parse(item.deadline)<=Date.now())return this.update(item,"system","expired",{failureReason:"deadline-exceeded"});if(input.action==="reassign"){if(actor.role!=="department-manager"||actor.departmentId!==item.targetDepartmentId)throw new Error("Target department manager reassign required");if(!["approved","reassigned","in-progress","partially-completed"].includes(item.status)||!input.assigneeId)throw new Error("Delegation cannot be reassigned");this.assertTargetAssignee(item,input.assigneeId);return this.update(item,actorId,"reassigned",{assigneeId:input.assigneeId,reviewReason:input.reason?.trim()||"reassigned"});}if(actorId!==item.assigneeId)throw new Error("Delegation assignee action denied");if(input.action==="start"){if(!["approved","reassigned"].includes(item.status))throw new Error("Delegation cannot start");return this.update(item,actorId,"in-progress",{});}const evidenceIds=[...new Set(input.evidenceIds??[])].sort();if(!evidenceIds.length)throw new Error("Handoff evidence required");if(input.action==="partial"){if(!["in-progress","partially-completed"].includes(item.status))throw new Error("Delegation cannot record partial completion");return this.update(item,actorId,"partially-completed",{completionEvidenceIds:evidenceIds});}if(input.action==="complete"){if(!["in-progress","partially-completed"].includes(item.status))throw new Error("Delegation cannot complete");const completed=[...new Set(input.completedCriteria??[])].sort(),required=[...item.completionCriteria].sort();if(json(completed)!==json(required))throw new Error("Delegation completion criteria evidence is incomplete");return this.update(item,actorId,"completed",{completionEvidenceIds:evidenceIds});}if(!input.reason?.trim())throw new Error("Handoff failure reason required");return this.update(item,actorId,"handoff-failed",{completionEvidenceIds:evidenceIds,failureReason:input.reason.trim()});}
 expireDue(companyId:string,at=now()):number{const rows=this.db.prepare("SELECT id FROM delegations_v17 WHERE company_id=? AND deadline<=? AND status NOT IN ('rejected','completed','expired','handoff-failed') ORDER BY id").all(companyId,at) as Array<{id:string}>;for(const row of rows){const item=this.get(row.id)!;this.update(item,"system","expired",{failureReason:"deadline-exceeded"});}return rows.length;}
 get(id:string):DelegationRecord|null{const row=this.db.prepare("SELECT * FROM delegations_v17 WHERE id=?").get(id) as Record<string,unknown>|undefined;return row?this.record(row):null;}
 private update(item:DelegationRecord,actorId:string,status:DelegationStatus,fields:{assigneeId?:string;reviewedBy?:string;reviewReason?:string;completionEvidenceIds?:string[];failureReason?:string}):DelegationRecord{const timestamp=now();this.db.prepare("UPDATE delegations_v17 SET assignee_id=COALESCE(?,assignee_id),status=?,reviewed_by=COALESCE(?,reviewed_by),review_reason=COALESCE(?,review_reason),completion_evidence_ids=CASE WHEN ? IS NULL THEN completion_evidence_ids ELSE ? END,failure_reason=COALESCE(?,failure_reason),updated_at=? WHERE id=?").run(fields.assigneeId??null,status,fields.reviewedBy??null,fields.reviewReason??null,fields.completionEvidenceIds?json(fields.completionEvidenceIds):null,fields.completionEvidenceIds?json(fields.completionEvidenceIds):null,fields.failureReason??null,timestamp,item.id);this.transitionAudit(item,item.status,status,actorId,fields);return this.get(item.id)!;}
 private transitionAudit(item:DelegationRecord,from:DelegationStatus|null,to:DelegationStatus,actorId:string,payload:unknown):void{const timestamp=now();this.db.prepare("INSERT INTO delegation_transitions_v17(delegation_id,from_status,to_status,actor_id,payload,created_at) VALUES(?,?,?,?,?,?)").run(item.id,from,to,actorId,json(payload),timestamp);this.db.prepare("INSERT INTO company_audit_v4(company_id,type,payload,created_at) VALUES(?,?,?,?)").run(item.companyId,"DELEGATION_TRANSITIONED",json({delegationId:item.id,from,to,actorId,payload,snapshotHash:item.snapshotHash}),timestamp);}
 private authorized(companyId:string,id:string,actorId:string):DelegationRecord{this.companies.require(companyId,actorId,"view");const item=this.get(id);if(!item||item.companyId!==companyId)throw new Error("Delegation access denied");return item;}
 private byRequest(requestId:string):DelegationRecord|null{const row=this.db.prepare("SELECT * FROM delegations_v17 WHERE request_id=?").get(requestId) as Record<string,unknown>|undefined;return row?this.record(row):null;}
 private member(companyId:string,principalId:string):{role:string;departmentId:string|null}|null{const row=this.db.prepare("SELECT role,department_id FROM company_members_v4 WHERE company_id=? AND principal_id=?").get(companyId,principalId) as {role:string;department_id:string|null}|undefined;return row?{role:row.role,departmentId:row.department_id}:null;}
 private assertDepartment(companyId:string,departmentId:string):void{if(!this.db.prepare("SELECT 1 FROM departments_v4 WHERE company_id=? AND id=?").get(companyId,departmentId))throw new Error("Cross-company delegation department blocked");}
 private assertTargetAssignee(item:DelegationRecord,assigneeId:string):void{const member=this.member(item.companyId,assigneeId);if(!member||member.departmentId!==item.targetDepartmentId)throw new Error("Delegation assignee must belong to target department");}
 private record(row:Record<string,unknown>):DelegationRecord{return{id:String(row.id),requestId:String(row.request_id),companyId:String(row.company_id),sourceDepartmentId:String(row.source_department_id),targetDepartmentId:String(row.target_department_id),ownerId:String(row.owner_id),assigneeId:row.assignee_id===null?null:String(row.assignee_id),completionCriteria:parse(row.completion_criteria),allowedScope:parse(row.allowed_scope),evidence:parse(row.evidence),deadline:String(row.deadline),status:String(row.status) as DelegationStatus,reviewedBy:row.reviewed_by===null?null:String(row.reviewed_by),reviewReason:row.review_reason===null?null:String(row.review_reason),completionEvidenceIds:parse(row.completion_evidence_ids),failureReason:row.failure_reason===null?null:String(row.failure_reason),contractVersion:String(row.contract_version),snapshotHash:String(row.snapshot_hash),createdAt:String(row.created_at),updatedAt:String(row.updated_at)};}
}
