import { DatabaseSync } from "node:sqlite";
import { readFileSync,readdirSync,realpathSync,statSync } from "node:fs";
import { isAbsolute,relative,resolve } from "node:path";
import type { StateStore } from "../../persistence/src/index.js";

export type ProjectRole = "owner" | "manager" | "reviewer" | "worker" | "viewer";
export type BoardStatus = "backlog" | "ready" | "in-progress" | "review" | "blocked" | "done";
export type AssigneeKind = "human" | "agent";
export interface ProjectRecord { id: string; workspaceId: string; name: string; repoPath: string; defaultBranch: string; runtimePath: string; organizationProfile: unknown; budgetLimit: number; spent: number; status: "active" | "archived" }
export type ValidatorCheck="build"|"typecheck"|"test"|"lint"|"security";
export interface ValidatorProfile { checks:ValidatorCheck[] }
export interface MilestoneRecord { id: string; projectId: string; title: string; status: "planned" | "active" | "completed" | "cancelled"; completionCriteria: string[]; budgetLimit: number; spent: number; dueAt: string | null }
export interface BoardTaskRecord { id: string; projectId: string; milestoneId: string | null; title: string; status: BoardStatus; priority: number; completionCriteria: string[]; budgetLimit: number; spent: number; runId: string | null; leaseOwner: string | null; leaseExpiresAt: string | null }
export interface AssignmentRecord { taskId: string; principalId: string; kind: AssigneeKind; responsibility: "owner" | "executor" | "reviewer" }
export interface NotificationRecord { id: string; projectId: string; dedupeKey: string; type: string; payload: unknown; readAt: string | null; createdAt: string }
export interface Actor { id: string }

const parse = <T>(value: unknown): T => JSON.parse(String(value)) as T;
const json = (value: unknown): string => JSON.stringify(value ?? null);
const now = () => new Date().toISOString();
const allowedTransitions: Record<BoardStatus, BoardStatus[]> = { backlog: ["ready", "blocked"], ready: ["in-progress", "blocked"], "in-progress": ["review", "blocked"], review: ["done", "in-progress", "blocked"], blocked: ["backlog", "ready"], done: [] };
const grants: Record<ProjectRole, Set<string>> = {
  owner: new Set(["project:manage", "milestone:manage", "task:manage", "task:assign", "task:execute", "task:review", "approval:plan", "approval:result", "run:control", "budget:manage", "view"]),
  manager: new Set(["milestone:manage", "task:manage", "task:assign", "task:execute", "task:review", "approval:plan", "run:control", "view"]),
  reviewer: new Set(["task:review", "approval:result", "view"]), worker: new Set(["task:execute", "view"]), viewer: new Set(["view"])
};

export class ProjectOperations {
  constructor(private readonly db: DatabaseSync, private readonly state: StateStore) { this.migrate(); }
  private migrate(): void { this.db.exec(`
CREATE TABLE IF NOT EXISTS workspaces_v3(id TEXT PRIMARY KEY,name TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS projects_v3(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces_v3(id),name TEXT NOT NULL,repo_path TEXT NOT NULL,default_branch TEXT NOT NULL,runtime_path TEXT NOT NULL,organization_profile TEXT NOT NULL,budget_limit REAL NOT NULL CHECK(budget_limit>=0),spent REAL NOT NULL DEFAULT 0 CHECK(spent>=0),status TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS project_members_v3(project_id TEXT NOT NULL REFERENCES projects_v3(id) ON DELETE CASCADE,principal_id TEXT NOT NULL,role TEXT NOT NULL,PRIMARY KEY(project_id,principal_id));
CREATE TABLE IF NOT EXISTS milestones_v3(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects_v3(id) ON DELETE CASCADE,title TEXT NOT NULL,status TEXT NOT NULL,completion_criteria TEXT NOT NULL,budget_limit REAL NOT NULL CHECK(budget_limit>=0),spent REAL NOT NULL DEFAULT 0,due_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS board_tasks_v3(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects_v3(id) ON DELETE CASCADE,milestone_id TEXT REFERENCES milestones_v3(id),title TEXT NOT NULL,status TEXT NOT NULL,priority INTEGER NOT NULL,completion_criteria TEXT NOT NULL,budget_limit REAL NOT NULL CHECK(budget_limit>=0),spent REAL NOT NULL DEFAULT 0,run_id TEXT UNIQUE REFERENCES runs(id),lease_owner TEXT,lease_expires_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS board_dependencies_v3(task_id TEXT NOT NULL REFERENCES board_tasks_v3(id) ON DELETE CASCADE,depends_on_id TEXT NOT NULL REFERENCES board_tasks_v3(id),PRIMARY KEY(task_id,depends_on_id),CHECK(task_id<>depends_on_id));
CREATE TABLE IF NOT EXISTS assignments_v3(task_id TEXT NOT NULL REFERENCES board_tasks_v3(id) ON DELETE CASCADE,principal_id TEXT NOT NULL,kind TEXT NOT NULL,responsibility TEXT NOT NULL,PRIMARY KEY(task_id,principal_id,responsibility));
CREATE TABLE IF NOT EXISTS notifications_v3(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects_v3(id) ON DELETE CASCADE,dedupe_key TEXT NOT NULL,type TEXT NOT NULL,payload TEXT NOT NULL,read_at TEXT,created_at TEXT NOT NULL,UNIQUE(project_id,dedupe_key));
CREATE TABLE IF NOT EXISTS project_audit_v3(seq INTEGER PRIMARY KEY AUTOINCREMENT,project_id TEXT NOT NULL REFERENCES projects_v3(id) ON DELETE CASCADE,type TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS budget_reservations_v3(id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES board_tasks_v3(id) ON DELETE CASCADE,run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,amount REAL NOT NULL CHECK(amount>0),created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_board_project ON board_tasks_v3(project_id,status,priority);
CREATE INDEX IF NOT EXISTS idx_notifications_project ON notifications_v3(project_id,read_at,created_at);
`); }
  createWorkspace(id: string, name: string): void { if (!id || !name.trim()) throw new Error("Workspace id/name required"); this.db.prepare("INSERT INTO workspaces_v3 VALUES(?,?,?)").run(id, name.trim(), now()); }
  createProject(input: Omit<ProjectRecord, "spent" | "status">, ownerId: string): ProjectRecord { if (input.budgetLimit < 0 || !ownerId) throw new Error("Invalid project"); this.db.exec("BEGIN IMMEDIATE"); try { this.db.prepare("INSERT INTO projects_v3 VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(input.id,input.workspaceId,input.name,input.repoPath,input.defaultBranch,input.runtimePath,json(input.organizationProfile),input.budgetLimit,0,"active",now()); this.db.prepare("INSERT INTO project_members_v3 VALUES(?,?,?)").run(input.id,ownerId,"owner"); this.db.exec("COMMIT"); return this.project(input.id)!; } catch(e){this.db.exec("ROLLBACK");throw e;} }
  project(id: string): ProjectRecord | null { const x=this.db.prepare("SELECT * FROM projects_v3 WHERE id=?").get(id) as Record<string,unknown>|undefined; return x?{id:String(x.id),workspaceId:String(x.workspace_id),name:String(x.name),repoPath:String(x.repo_path),defaultBranch:String(x.default_branch),runtimePath:String(x.runtime_path),organizationProfile:parse(x.organization_profile),budgetLimit:Number(x.budget_limit),spent:Number(x.spent),status:String(x.status) as ProjectRecord["status"]}:null; }
  addMember(projectId:string, actor:Actor, principalId:string, role:ProjectRole):void { this.require(projectId,actor,"project:manage"); this.db.prepare("INSERT OR REPLACE INTO project_members_v3 VALUES(?,?,?)").run(projectId,principalId,role); this.audit(projectId,"MEMBER_SET",{actor:actor.id,principalId,role}); }
  role(projectId:string, actor:Actor):ProjectRole|null { const x=this.db.prepare("SELECT role FROM project_members_v3 WHERE project_id=? AND principal_id=?").get(projectId,actor.id) as {role:string}|undefined; return x?x.role as ProjectRole:null; }
  projectForRun(runId:string):string|null { const x=this.db.prepare("SELECT project_id FROM board_tasks_v3 WHERE run_id=?").get(runId) as {project_id:string}|undefined;return x?.project_id??null; }
  validatorProfile(projectId:string):ValidatorProfile{const project=this.project(projectId);if(!project)throw new Error("Project missing");const organization=project.organizationProfile&&typeof project.organizationProfile==="object"?project.organizationProfile as Record<string,unknown>:{},raw=(organization.validatorProfile as {checks?:unknown}|undefined)?.checks,checks=Array.isArray(raw)?raw.filter((x):x is ValidatorCheck=>["build","typecheck","test","lint","security"].includes(String(x))):[];return{checks:checks.length?[...new Set(checks)]:["build","test","lint","security"]};}
  validatorProfileForRun(runId:string):ValidatorProfile{const projectId=this.projectForRun(runId);return projectId?this.validatorProfile(projectId):{checks:["build","test","lint","security"]};}
  setValidatorProfile(projectId:string,profile:ValidatorProfile,actor:Actor):ProjectRecord{this.require(projectId,actor,"project:manage");if(!profile.checks.length||profile.checks.some(x=>!["build","typecheck","test","lint","security"].includes(x)))throw new Error("Invalid validator profile");const project=this.project(projectId)!,organization=project.organizationProfile&&typeof project.organizationProfile==="object"?project.organizationProfile as Record<string,unknown>:{};this.db.prepare("UPDATE projects_v3 SET organization_profile=? WHERE id=?").run(json({...organization,validatorProfile:{checks:[...new Set(profile.checks)]}}),projectId);this.audit(projectId,"VALIDATOR_PROFILE_CHANGED",{actor:actor.id,checks:[...new Set(profile.checks)]});return this.project(projectId)!;}
  repositoryRead(projectId:string,path:string,actor:Actor):{path:string;content:string;bytes:number}{this.require(projectId,actor,"view");const root=realpathSync(this.project(projectId)?.repoPath??""),target=this.safeRepositoryPath(root,path),stat=statSync(target);if(!stat.isFile()||stat.size>131072)throw new Error("Repository file must be <= 128 KiB");const content=readFileSync(target,"utf8"),normalized=relative(root,target).replaceAll("\\","/");this.audit(projectId,"REPOSITORY_READ",{actor:actor.id,path:normalized,bytes:Buffer.byteLength(content)});return{path:normalized,content,bytes:Buffer.byteLength(content)};}
  repositorySearch(projectId:string,query:string,actor:Actor):Array<{path:string;line:number;text:string}>{this.require(projectId,actor,"view");if(!query||query.length>200)throw new Error("Repository search query required");const root=realpathSync(this.project(projectId)?.repoPath??""),files:string[]=[],walk=(dir:string)=>{for(const entry of readdirSync(dir,{withFileTypes:true})){if(files.length>=500)break;if(entry.name===".git"||entry.name==="node_modules")continue;const candidate=resolve(dir,entry.name);if(entry.isSymbolicLink())continue;if(entry.isDirectory())walk(candidate);else if(entry.isFile()&&statSync(candidate).size<=262144)files.push(candidate);}};walk(root);const results:Array<{path:string;line:number;text:string}>=[];for(const file of files){let content:string;try{content=readFileSync(file,"utf8");}catch{continue;}for(const [index,line] of content.split(/\r?\n/).entries())if(line.toLowerCase().includes(query.toLowerCase())){results.push({path:relative(root,file).replaceAll("\\","/"),line:index+1,text:line.slice(0,500)});if(results.length>=50)break;}if(results.length>=50)break;}this.audit(projectId,"REPOSITORY_SEARCHED",{actor:actor.id,query,resultCount:results.length,filesScanned:files.length});return results;}
  private safeRepositoryPath(root:string,path:string):string{const target=resolve(root,path),rel=relative(root,target);if(!path||isAbsolute(path)||rel.startsWith("..")||isAbsolute(rel))throw new Error("Repository path outside project root");const real=realpathSync(target),realRel=relative(root,real);if(realRel.startsWith("..")||isAbsolute(realRel))throw new Error("Repository symlink escapes project root");return real;}
  authorizeRun(runId:string,actor:Actor,permission:"approval:plan"|"approval:result"|"run:control"):void {const projectId=this.projectForRun(runId);if(projectId)this.require(projectId,actor,permission);}
  require(projectId:string, actor:Actor, permission:string):void { const role=this.role(projectId,actor); if(!role||!grants[role].has(permission)){this.audit(projectId,"AUTHORIZATION_DENIED",{actor:actor.id,permission,role});throw new Error(`Permission denied: ${permission}`);} }
  createMilestone(input:Omit<MilestoneRecord,"spent">,actor:Actor):MilestoneRecord { this.require(input.projectId,actor,"milestone:manage"); if(!input.completionCriteria.length)throw new Error("Milestone completion criteria required"); const project=this.project(input.projectId)!; if(input.budgetLimit>project.budgetLimit)throw new Error("Milestone budget exceeds project"); this.db.prepare("INSERT INTO milestones_v3 VALUES(?,?,?,?,?,?,?,?,?)").run(input.id,input.projectId,input.title,input.status,json(input.completionCriteria),input.budgetLimit,0,input.dueAt,now());this.audit(input.projectId,"MILESTONE_CREATED",{id:input.id});return this.milestone(input.id)!; }
  milestone(id:string):MilestoneRecord|null { const x=this.db.prepare("SELECT * FROM milestones_v3 WHERE id=?").get(id) as Record<string,unknown>|undefined; return x?{id:String(x.id),projectId:String(x.project_id),title:String(x.title),status:String(x.status) as MilestoneRecord["status"],completionCriteria:parse<string[]>(x.completion_criteria),budgetLimit:Number(x.budget_limit),spent:Number(x.spent),dueAt:x.due_at===null?null:String(x.due_at)}:null; }
  transitionMilestone(id:string,to:MilestoneRecord["status"],actor:Actor):MilestoneRecord {const milestone=this.milestone(id);if(!milestone)throw new Error("Milestone missing");this.require(milestone.projectId,actor,"milestone:manage");const allowed:Record<MilestoneRecord["status"],MilestoneRecord["status"][]>={planned:["active","cancelled"],active:["completed","cancelled"],completed:[],cancelled:[]};if(!allowed[milestone.status].includes(to))throw new Error("Invalid milestone transition");if(to==="completed"&&this.db.prepare("SELECT 1 FROM board_tasks_v3 WHERE milestone_id=? AND status<>'done' LIMIT 1").get(id))throw new Error("Milestone tasks incomplete");this.db.prepare("UPDATE milestones_v3 SET status=? WHERE id=?").run(to,id);this.audit(milestone.projectId,"MILESTONE_TRANSITIONED",{id,from:milestone.status,to,actor:actor.id});return this.milestone(id)!;}
  setProjectBudget(projectId:string,limit:number,actor:Actor):ProjectRecord {this.require(projectId,actor,"budget:manage");const project=this.project(projectId);if(!project||limit<project.spent)throw new Error("Budget below spent amount");const child=Number((this.db.prepare("SELECT COALESCE(MAX(budget_limit),0) AS n FROM milestones_v3 WHERE project_id=?").get(projectId) as {n:number}).n);if(limit<child)throw new Error("Budget below child limit");this.db.prepare("UPDATE projects_v3 SET budget_limit=? WHERE id=?").run(limit,projectId);this.audit(projectId,"PROJECT_BUDGET_CHANGED",{from:project.budgetLimit,to:limit,actor:actor.id});return this.project(projectId)!;}
  createTask(input:Omit<BoardTaskRecord,"spent"|"runId"|"leaseOwner"|"leaseExpiresAt"> & {dependsOn?:string[]},actor:Actor):BoardTaskRecord { this.require(input.projectId,actor,"task:manage"); if(!input.completionCriteria.length)throw new Error("Task completion criteria required"); if(input.milestoneId&&this.milestone(input.milestoneId)?.projectId!==input.projectId)throw new Error("Cross-project milestone blocked"); const milestone=input.milestoneId?this.milestone(input.milestoneId):null;if(input.budgetLimit>(milestone?.budgetLimit??this.project(input.projectId)!.budgetLimit))throw new Error("Task budget exceeds parent"); this.db.exec("BEGIN IMMEDIATE");try{this.db.prepare("INSERT INTO board_tasks_v3 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(input.id,input.projectId,input.milestoneId,input.title,input.status,input.priority,json(input.completionCriteria),input.budgetLimit,0,null,null,null,now());for(const dep of input.dependsOn??[]){const d=this.task(dep);if(!d||d.projectId!==input.projectId)throw new Error("Cross-project dependency blocked");this.db.prepare("INSERT INTO board_dependencies_v3 VALUES(?,?)").run(input.id,dep);}this.db.exec("COMMIT");this.audit(input.projectId,"BOARD_TASK_CREATED",{id:input.id});return this.task(input.id)!;}catch(e){this.db.exec("ROLLBACK");throw e;} }
  task(id:string):BoardTaskRecord|null { const x=this.db.prepare("SELECT * FROM board_tasks_v3 WHERE id=?").get(id) as Record<string,unknown>|undefined; return x?{id:String(x.id),projectId:String(x.project_id),milestoneId:x.milestone_id===null?null:String(x.milestone_id),title:String(x.title),status:String(x.status) as BoardStatus,priority:Number(x.priority),completionCriteria:parse<string[]>(x.completion_criteria),budgetLimit:Number(x.budget_limit),spent:Number(x.spent),runId:x.run_id===null?null:String(x.run_id),leaseOwner:x.lease_owner===null?null:String(x.lease_owner),leaseExpiresAt:x.lease_expires_at===null?null:String(x.lease_expires_at)}:null; }
  tasks(projectId:string):BoardTaskRecord[]{return (this.db.prepare("SELECT id FROM board_tasks_v3 WHERE project_id=? ORDER BY priority DESC,created_at").all(projectId) as Array<{id:string}>).map(x=>this.task(x.id)!);}
  activeTasks(projectId:string):BoardTaskRecord[]{if(!this.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='goal_delivery_stage_instances_v19'").get())return this.tasks(projectId);return (this.db.prepare(`SELECT t.id FROM board_tasks_v3 t WHERE t.project_id=? AND NOT EXISTS (SELECT 1 FROM goal_delivery_stage_instances_v19 s WHERE s.run_id=t.run_id AND s.status='revision-requested') ORDER BY t.priority DESC,t.created_at`).all(projectId) as Array<{id:string}>).map(x=>this.task(x.id)!);}
  assign(taskId:string,actor:Actor,principalId:string,kind:AssigneeKind,responsibility:AssignmentRecord["responsibility"]):void { const task=this.task(taskId);if(!task)throw new Error("Task missing");this.require(task.projectId,actor,"task:assign");this.db.prepare("INSERT OR IGNORE INTO assignments_v3 VALUES(?,?,?,?)").run(taskId,principalId,kind,responsibility);this.audit(task.projectId,"TASK_ASSIGNED",{taskId,actor:actor.id,principalId,kind,responsibility}); }
  assignments(taskId:string):AssignmentRecord[]{return this.db.prepare("SELECT task_id AS taskId,principal_id AS principalId,kind,responsibility FROM assignments_v3 WHERE task_id=? ORDER BY responsibility,principal_id").all(taskId) as unknown as AssignmentRecord[];}
  transitionTask(taskId:string,to:BoardStatus,actor:Actor):BoardTaskRecord { const task=this.task(taskId);if(!task)throw new Error("Task missing");this.require(task.projectId,actor,to==="done"?"task:review":"task:execute");if(!allowedTransitions[task.status].includes(to)){this.audit(task.projectId,"TASK_TRANSITION_DENIED",{taskId,from:task.status,to,actor:actor.id,reason:"invalid-transition"});throw new Error(`Invalid task transition: ${task.status} -> ${to}`);}if(to==="in-progress"){const pending=this.db.prepare("SELECT 1 FROM board_dependencies_v3 d JOIN board_tasks_v3 t ON t.id=d.depends_on_id WHERE d.task_id=? AND t.status<>'done' LIMIT 1").get(taskId);if(pending){this.audit(task.projectId,"TASK_TRANSITION_DENIED",{taskId,from:task.status,to,actor:actor.id,reason:"dependency"});throw new Error("Task dependency incomplete");}}this.db.prepare("UPDATE board_tasks_v3 SET status=? WHERE id=?").run(to,taskId);this.audit(task.projectId,"TASK_TRANSITIONED",{taskId,from:task.status,to,actor:actor.id});if(to==="blocked")this.notify(task.projectId,`task-blocked:${taskId}:${task.status}`,"task-blocked",{taskId,from:task.status});return this.task(taskId)!; }
  linkRun(taskId:string,runId:string,actor:Actor):void { const task=this.task(taskId);if(!task)throw new Error("Task missing");this.require(task.projectId,actor,"task:execute");if(!this.state.getRun(runId))throw new Error("Run missing");const changed=this.db.prepare("UPDATE board_tasks_v3 SET run_id=? WHERE id=? AND run_id IS NULL").run(runId,taskId).changes;if(changed!==1){this.audit(task.projectId,"RUN_LINK_DENIED",{taskId,runId,actor:actor.id});throw new Error("Task already linked");}this.audit(task.projectId,"RUN_LINKED",{taskId,runId,actor:actor.id}); }
  claim(taskId:string,owner:string,ttlMs:number,actor:Actor):boolean { const task=this.task(taskId);if(!task)throw new Error("Task missing");this.require(task.projectId,actor,"task:execute");const expires=new Date(Date.now()+ttlMs).toISOString();const result=this.db.prepare("UPDATE board_tasks_v3 SET lease_owner=?,lease_expires_at=? WHERE id=? AND status IN ('ready','in-progress') AND (lease_owner IS NULL OR lease_expires_at<=?)").run(owner,expires,taskId,now());this.audit(task.projectId,result.changes?"TASK_CLAIMED":"TASK_CLAIM_DENIED",{taskId,owner,expires});return result.changes===1; }
  heartbeat(taskId:string,owner:string,ttlMs:number):boolean{const task=this.task(taskId);if(!task)return false;const changed=this.db.prepare("UPDATE board_tasks_v3 SET lease_expires_at=? WHERE id=? AND lease_owner=? AND lease_expires_at>?").run(new Date(Date.now()+ttlMs).toISOString(),taskId,owner,now()).changes===1;this.audit(task.projectId,changed?"TASK_HEARTBEAT":"TASK_HEARTBEAT_DENIED",{taskId,owner});return changed;}
  recoverExpired(projectId:string):string[]{const rows=this.db.prepare("SELECT id FROM board_tasks_v3 WHERE project_id=? AND lease_owner IS NOT NULL AND lease_expires_at<=? AND status='in-progress'").all(projectId,now()) as Array<{id:string}>;for(const row of rows)this.db.prepare("UPDATE board_tasks_v3 SET status='ready',lease_owner=NULL,lease_expires_at=NULL WHERE id=?").run(row.id);if(rows.length)this.audit(projectId,"EXPIRED_LEASES_RECOVERED",{tasks:rows.map(x=>x.id)});return rows.map(x=>x.id);}
  async recover(projectId:string,actor:Actor,requeue:(runId:string)=>Promise<void>):Promise<string[]>{this.require(projectId,actor,"run:control");const expired=this.recoverExpired(projectId),runs=expired.flatMap(id=>{const runId=this.task(id)?.runId;if(!runId)return[];const status=this.state.getRun(runId)?.status;return status&&["PLANNING","READY","RUNNING","VALIDATING"].includes(status)?[runId]:[];});for(const runId of [...new Set(runs)])await requeue(runId);this.audit(projectId,"PROJECT_RUNS_RECOVERED",{runs});return runs;}
  spend(taskId:string,amount:number):boolean { if(!Number.isFinite(amount)||amount<0)return false;const task=this.task(taskId);if(!task)return false;const milestone=task.milestoneId?this.milestone(task.milestoneId):null;this.db.exec("BEGIN IMMEDIATE");try{const p=this.db.prepare("UPDATE projects_v3 SET spent=spent+? WHERE id=? AND spent+?<=budget_limit").run(amount,task.projectId,amount);const m=milestone?this.db.prepare("UPDATE milestones_v3 SET spent=spent+? WHERE id=? AND spent+?<=budget_limit").run(amount,milestone.id,amount):{changes:1};const t=this.db.prepare("UPDATE board_tasks_v3 SET spent=spent+? WHERE id=? AND spent+?<=budget_limit").run(amount,taskId,amount);if(p.changes!==1||m.changes!==1||t.changes!==1){this.db.exec("ROLLBACK");this.notify(task.projectId,`budget:${taskId}`,"budget-blocked",{taskId,amount});this.audit(task.projectId,"PROJECT_BUDGET_BLOCKED",{taskId,amount});return false;}this.db.exec("COMMIT");return true;}catch(e){try{this.db.exec("ROLLBACK");}catch{}throw e;} }
  reserveRunBudget(runId:string,amount:number):string|null {const row=this.db.prepare("SELECT id FROM board_tasks_v3 WHERE run_id=?").get(runId) as {id:string}|undefined;if(!row)return null;const task=this.task(row.id)!,milestone=task.milestoneId?this.milestone(task.milestoneId):null,id=crypto.randomUUID();this.db.exec("BEGIN IMMEDIATE");try{const reserved=(scope:string,scopeId:string)=>Number((this.db.prepare(`SELECT COALESCE(SUM(r.amount),0) AS n FROM budget_reservations_v3 r JOIN board_tasks_v3 t ON t.id=r.task_id WHERE t.${scope}=?`).get(scopeId) as {n:number}).n);const project=this.project(task.projectId)!;if(amount<=0||project.spent+reserved("project_id",task.projectId)+amount>project.budgetLimit||task.spent+Number((this.db.prepare("SELECT COALESCE(SUM(amount),0) AS n FROM budget_reservations_v3 WHERE task_id=?").get(task.id) as {n:number}).n)+amount>task.budgetLimit||(milestone&&milestone.spent+reserved("milestone_id",milestone.id)+amount>milestone.budgetLimit)){this.db.exec("ROLLBACK");this.notify(task.projectId,`budget-reserve:${runId}`,"budget-blocked",{taskId:task.id,runId,amount});this.audit(task.projectId,"PROJECT_BUDGET_BLOCKED",{taskId:task.id,runId,amount,stage:"reserve"});const run=this.state.getRun(runId);if(run)this.state.transition(runId,[run.status],"BLOCKED",{reason:"project-budget"});return "";}this.db.prepare("INSERT INTO budget_reservations_v3 VALUES(?,?,?,?,?)").run(id,task.id,runId,amount,now());this.db.exec("COMMIT");this.audit(task.projectId,"PROJECT_BUDGET_RESERVED",{taskId:task.id,runId,amount,id});return id;}catch(e){try{this.db.exec("ROLLBACK");}catch{}throw e;}}
  settleRunBudget(reservationId:string,actual:number):boolean {const row=this.db.prepare("SELECT r.task_id,r.amount,t.project_id,t.milestone_id FROM budget_reservations_v3 r JOIN board_tasks_v3 t ON t.id=r.task_id WHERE r.id=?").get(reservationId) as {task_id:string;amount:number;project_id:string;milestone_id:string|null}|undefined;if(!row)return false;if(actual<0||actual>row.amount)return false;this.db.exec("BEGIN IMMEDIATE");try{this.db.prepare("UPDATE projects_v3 SET spent=spent+? WHERE id=?").run(actual,row.project_id);if(row.milestone_id)this.db.prepare("UPDATE milestones_v3 SET spent=spent+? WHERE id=?").run(actual,row.milestone_id);this.db.prepare("UPDATE board_tasks_v3 SET spent=spent+? WHERE id=?").run(actual,row.task_id);this.db.prepare("DELETE FROM budget_reservations_v3 WHERE id=?").run(reservationId);this.db.exec("COMMIT");this.audit(row.project_id,"PROJECT_BUDGET_SETTLED",{taskId:row.task_id,reservationId,actual});return true;}catch(e){this.db.exec("ROLLBACK");throw e;}}
  releaseRunBudget(reservationId:string):void {this.db.prepare("DELETE FROM budget_reservations_v3 WHERE id=?").run(reservationId);}
  notify(projectId:string,dedupeKey:string,type:string,payload:unknown):NotificationRecord { this.db.prepare("INSERT OR IGNORE INTO notifications_v3 VALUES(?,?,?,?,?,?,?)").run(crypto.randomUUID(),projectId,dedupeKey,type,json(payload),null,now());return this.db.prepare("SELECT * FROM notifications_v3 WHERE project_id=? AND dedupe_key=?").get(projectId,dedupeKey) ? this.notifications(projectId).find(x=>x.dedupeKey===dedupeKey)! : undefined!; }
  notifications(projectId:string):NotificationRecord[]{return (this.db.prepare("SELECT * FROM notifications_v3 WHERE project_id=? ORDER BY created_at").all(projectId) as Record<string,unknown>[]).map(x=>({id:String(x.id),projectId:String(x.project_id),dedupeKey:String(x.dedupe_key),type:String(x.type),payload:parse(x.payload),readAt:x.read_at===null?null:String(x.read_at),createdAt:String(x.created_at)}));}
  actionableNotifications(projectId:string):NotificationRecord[]{const hasDeliveryStages=Boolean(this.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='goal_delivery_stage_instances_v19'").get());return this.notifications(projectId).filter(notification=>{if(notification.type!=="approval-waiting"&&notification.type!=="run-problem")return true;const payload=notification.payload&&typeof notification.payload==="object"?notification.payload as Record<string,unknown>:null,runId=payload?.runId?String(payload.runId):null;if(!runId)return false;const superseded=hasDeliveryStages&&this.db.prepare("SELECT 1 FROM goal_delivery_stage_instances_v19 WHERE run_id=? AND status='revision-requested' LIMIT 1").get(runId);if(superseded)return false;const status=this.state.getRun(runId)?.status;return notification.type==="approval-waiting"?["PLAN_APPROVAL_WAITING","RESULT_APPROVAL_WAITING"].includes(status??""):["BLOCKED","FAILED"].includes(status??"");});}
  private completedDeliveryRun(runId:string|null):boolean{return Boolean(runId&&this.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='goal_delivery_stage_instances_v19'").get()&&this.db.prepare("SELECT 1 FROM goal_delivery_stage_instances_v19 s JOIN goal_delivery_processes_v19 p ON p.id=s.process_id WHERE s.run_id=? AND p.status='completed' LIMIT 1").get(runId));}
  syncRunNotifications(runId:string):void {const projectId=this.projectForRun(runId);if(!projectId)return;const run=this.state.getRun(runId);if(!run)return;if(run.status==="PLAN_APPROVAL_WAITING"||run.status==="RESULT_APPROVAL_WAITING")this.notify(projectId,`approval:${runId}:${run.status}`,"approval-waiting",{runId,status:run.status});if(run.status==="BLOCKED"||run.status==="FAILED")this.notify(projectId,`run:${runId}:${run.status}`,"run-problem",{runId,status:run.status,checkpoint:run.checkpoint});for(const assessment of this.state.mergeAssessments(runId))if(assessment.conflict)this.notify(projectId,`merge-conflict:${assessment.id}`,"merge-conflict",{runId,assessment});}
  readNotification(id:string,actor:Actor):void {const x=this.db.prepare("SELECT project_id FROM notifications_v3 WHERE id=?").get(id) as {project_id:string}|undefined;if(!x)throw new Error("Notification missing");this.require(x.project_id,actor,"view");this.db.prepare("UPDATE notifications_v3 SET read_at=COALESCE(read_at,?) WHERE id=?").run(now(),id);this.audit(x.project_id,"NOTIFICATION_READ",{id,actor:actor.id});}
  snapshot(projectId:string,actor:Actor):unknown {this.require(projectId,actor,"view");const project=this.project(projectId);if(!project)throw new Error("Project missing");const milestones=(this.db.prepare("SELECT id FROM milestones_v3 WHERE project_id=? ORDER BY created_at").all(projectId) as Array<{id:string}>).map(x=>this.milestone(x.id)!);const allTasks=this.tasks(projectId),tasks=this.activeTasks(projectId),supersededTasks=allTasks.filter(task=>!tasks.some(active=>active.id===task.id));for(const task of tasks)if(task.runId)this.syncRunNotifications(task.runId);const hydrate=(task:BoardTaskRecord)=>{const artifacts=task.runId?this.state.artifactVersionsForRun(task.runId):[],completedDelivery=this.completedDeliveryRun(task.runId);return{...task,assignments:this.assignments(task.id),run:task.runId?this.state.getRun(task.runId):null,artifacts,stale:completedDelivery?[]:artifacts.filter(x=>x.stale&&Number((this.db.prepare("SELECT MAX(version) version FROM artifact_versions_v2 WHERE logical_id=?").get(x.logicalId) as {version:number}).version)===x.version),approvals:task.runId?this.state.approvals(task.runId):[],mergeAssessments:task.runId?this.state.mergeAssessments(task.runId):[]};};return{project,milestones:milestones.map(m=>({...m,progress:{total:tasks.filter(t=>t.milestoneId===m.id).length,done:tasks.filter(t=>t.milestoneId===m.id&&t.status==="done").length}})),tasks:tasks.map(hydrate),supersededTasks:supersededTasks.map(hydrate),notifications:this.actionableNotifications(projectId),audit:this.auditEvents(projectId),progress:{total:tasks.length,done:tasks.filter(x=>x.status==="done").length}};}
  auditEvents(projectId:string):unknown[]{return this.db.prepare("SELECT seq,type,payload,created_at AS createdAt FROM project_audit_v3 WHERE project_id=? ORDER BY seq").all(projectId) as unknown[];}
  private audit(projectId:string,type:string,payload:unknown):void {this.db.prepare("INSERT INTO project_audit_v3(project_id,type,payload,created_at) VALUES(?,?,?,?)").run(projectId,type,json(payload),now());const run=this.db.prepare("SELECT run_id FROM board_tasks_v3 WHERE project_id=? AND run_id IS NOT NULL ORDER BY created_at LIMIT 1").get(projectId) as {run_id:string}|undefined;if(run)this.state.audit(run.run_id,type,{projectId,...payload as object}); }
}

export class ProjectRunBudgetGuard {
  constructor(private readonly projects:ProjectOperations,private readonly maxCallCost=1){}
  reserve(runId:string):string|null {const id=this.projects.reserveRunBudget(runId,this.maxCallCost);if(id==="")throw new Error("Project budget exceeded");return id;}
  settle(reservationId:string|null,actual:number):boolean{return reservationId===null||this.projects.settleRunBudget(reservationId,actual);}
  release(reservationId:string|null):void {if(reservationId)this.projects.releaseRunBudget(reservationId);}
}
