import type { DatabaseSync } from "node:sqlite";
import type { RunStatus,StateStore } from "../../persistence/src/index.js";
import type { RunController } from "../../runtime/src/index.js";
import type { ProjectOperations } from "../../project-ops/src/index.js";

export type InterventionCommand="pause"|"restrict-path"|"request-tests"|"add-reviewer"|"request-explanation"|"assign-human"|"retry-from-checkpoint"|"stop-budget"|"set-budget"|"set-priority"|"resolve-incident";
export interface InterventionRequest{requestId:string;actorId:string;reason:string;expectedStatus:RunStatus;paths?:string[];tests?:string[];principalId?:string;responsibility?:"executor"|"reviewer";limit?:number;priority?:number;incidentId?:string;resolution?:string}
export class InterventionConflict extends Error{readonly statusCode=409}

export class InterventionService{
 constructor(private readonly db:DatabaseSync,private readonly state:StateStore,private readonly controller:RunController,private readonly projects?:ProjectOperations){this.db.exec("CREATE TABLE IF NOT EXISTS interventions_v9(id TEXT PRIMARY KEY,request_id TEXT UNIQUE NOT NULL,run_id TEXT NOT NULL,actor_id TEXT NOT NULL,command TEXT NOT NULL,reason TEXT NOT NULL,payload TEXT NOT NULL,result TEXT NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS incident_resolutions_v9(incident_id TEXT PRIMARY KEY,run_id TEXT NOT NULL,resolution TEXT NOT NULL,actor_id TEXT NOT NULL,created_at TEXT NOT NULL)");}
 async execute(runId:string,command:InterventionCommand,input:InterventionRequest):Promise<unknown>{
  if(!input.requestId||!input.actorId||!input.reason||!input.expectedStatus)throw new Error("requestId, actorId, reason and expectedStatus are required");
  const prior=this.db.prepare("SELECT result FROM interventions_v9 WHERE request_id=?").get(input.requestId) as {result:string}|undefined;if(prior)return JSON.parse(prior.result);
  const run=this.state.getRun(runId);if(!run)throw new Error("Run missing");
  this.projects?.authorizeRun(runId,{id:input.actorId},"run:control");
  if(run.status!==input.expectedStatus){this.state.audit(runId,"INTERVENTION_CONFLICT",{command,actorId:input.actorId,expected:input.expectedStatus,actual:run.status});throw new InterventionConflict(`Stale Run status: expected ${input.expectedStatus}, actual ${run.status}`);}
  const checkpoint={...(run.checkpoint??{})};let detail:unknown={};
  if(command==="pause"){if(run.status!=="RUNNING")throw new InterventionConflict("Pause requires RUNNING");await this.controller.pause(runId);}
  else if(command==="restrict-path"){if(!["PLAN_APPROVAL_WAITING","REVISION_REQUIRED"].includes(run.status))throw new InterventionConflict("Path restriction is no longer editable");if(!input.paths?.length)throw new Error("paths are required");detail={paths:[...new Set(input.paths)]};if(!this.state.updateRun(runId,run.status,{...checkpoint,restrictedPaths:(detail as {paths:string[]}).paths}))throw new InterventionConflict("Run changed during intervention");}
  else if(command==="request-tests"){if(!["VALIDATING","RESULT_APPROVAL_WAITING"].includes(run.status))throw new InterventionConflict("Tests can only be requested before result approval");if(!input.tests?.length)throw new Error("tests are required");const tests=[...new Set(input.tests.map(x=>x.toLowerCase().includes("type")?"typecheck":x.toLowerCase().includes("security")?"security":x.toLowerCase().includes("lint")?"lint":x.toLowerCase().includes("build")?"build":x.toLowerCase().includes("test")?"test":""))].filter(Boolean);if(!tests.length)throw new Error("tests must map to validator checks");detail={tests};if(!this.state.updateRun(runId,run.status,{...checkpoint,requestedTests:tests,forceRevision:true}))throw new InterventionConflict("Run changed during intervention");this.state.transition(runId,[run.status],"REVISION_REQUIRED",{...checkpoint,requestedTests:tests,forceRevision:true});for(const task of this.state.tasks(runId).filter(x=>x.role==="worker"||x.role==="reviewer"))this.state.resetTask(task.id,{...(task.input as object),requestedTests:tests});}
  else if(command==="add-reviewer"||command==="assign-human"){if(!input.principalId)throw new Error("principalId is required");const task=this.db.prepare("SELECT id FROM board_tasks_v3 WHERE run_id=?").get(runId) as {id:string}|undefined;if(!task)throw new Error("Linked task missing");const responsibility=command==="add-reviewer"?"reviewer":input.responsibility??"reviewer";this.projects!.assign(task.id,{id:input.actorId},input.principalId,command==="assign-human"?"human":"agent",responsibility);detail={principalId:input.principalId,responsibility};if(!this.state.updateRun(runId,run.status,{...checkpoint,forceReviewer:true,humanReview:command==="assign-human"||checkpoint.humanReview,...(command==="assign-human"?{humanReviewerId:input.principalId}:{})}))throw new InterventionConflict("Run changed during intervention");}
  else if(command==="request-explanation"){detail={status:run.status,checkpoint:run.checkpoint,lastAudit:this.state.auditEvents(runId).at(-1)??null};}
  else if(command==="retry-from-checkpoint"){if(!run.checkpoint)throw new InterventionConflict("Checkpoint missing");if(!["FAILED","BLOCKED","PAUSED","REVISION_REQUIRED"].includes(run.status))throw new InterventionConflict("Run is not retryable");if(run.status==="REVISION_REQUIRED")this.controller.move(runId,"READY",checkpoint);else await this.controller.retry(runId);detail={checkpoint};}
  else if(command==="stop-budget"){if(run.status!=="RUNNING")throw new InterventionConflict("Budget stop requires RUNNING");this.controller.move(runId,"BLOCKED",{...checkpoint,reason:"budget-stopped",budgetStoppedBy:input.actorId});detail={limit:run.spent};}
  else if(command==="set-budget"){if(input.limit===undefined||!Number.isFinite(input.limit)||input.limit<run.spent)throw new Error("limit must be at least current spend");if(!this.state.updateRun(runId,run.status,checkpoint,input.limit))throw new InterventionConflict("Run changed during intervention");detail={limit:input.limit};}
  else if(command==="set-priority"){if(!["READY","PLAN_APPROVAL_WAITING"].includes(run.status))throw new InterventionConflict("Priority can only change while waiting");if(input.priority===undefined||!Number.isInteger(input.priority))throw new Error("integer priority is required");const task=this.db.prepare("SELECT id FROM board_tasks_v3 WHERE run_id=?").get(runId) as {id:string}|undefined;if(!task)throw new Error("Linked task missing");this.db.prepare("UPDATE board_tasks_v3 SET priority=? WHERE id=?").run(input.priority,task.id);detail={priority:input.priority,taskId:task.id};}
  else {if(!input.incidentId||!input.resolution)throw new Error("incidentId and resolution are required");this.db.prepare("INSERT INTO incident_resolutions_v9 VALUES(?,?,?,?,?) ON CONFLICT(incident_id) DO UPDATE SET resolution=excluded.resolution,actor_id=excluded.actor_id,created_at=excluded.created_at").run(input.incidentId,runId,input.resolution,input.actorId,new Date().toISOString());detail={incidentId:input.incidentId,resolution:input.resolution};}
  const result={ok:true,command,run:this.state.getRun(runId),detail};this.db.prepare("INSERT INTO interventions_v9 VALUES(?,?,?,?,?,?,?,?,?)").run(crypto.randomUUID(),input.requestId,runId,input.actorId,command,input.reason,JSON.stringify(input),JSON.stringify(result),new Date().toISOString());this.state.audit(runId,"RUN_INTERVENTION_APPLIED",{command,actorId:input.actorId,reason:input.reason,requestId:input.requestId,detail});return result;
 }
 list(runId:string):unknown[]{return this.db.prepare("SELECT request_id requestId,actor_id actorId,command,reason,payload,result,created_at createdAt FROM interventions_v9 WHERE run_id=? ORDER BY created_at").all(runId) as unknown[];}
}
