export type DeploymentEnvironment="preview"|"production";
export interface FirebaseDeploymentRequest{id:string;environment:DeploymentEnvironment;targetProjectId:string;targetChannel:string|null;artifactSnapshotHash:string;approvedBy:string;approvedAt:string;credentialAvailable:boolean;sourceDirectory:string}
export interface FirebaseDeploymentReceipt{providerReceiptId:string;url:string|null;version:string|null;verifiedAt:string;rollbackRef:string|null}
export interface FirebaseCommandResult{exitCode:number;stdout:string;stderr:string}
export type FirebaseCommandExecutor=(args:readonly string[],cwd:string)=>Promise<FirebaseCommandResult>;
export type FirebaseRollbackExecutor=(request:FirebaseDeploymentRequest,receipt:FirebaseDeploymentReceipt)=>Promise<{verifiedAt:string}>;

function safeId(value:string,label:string):string{const normalized=value.trim();if(!/^[a-zA-Z0-9][a-zA-Z0-9._:-]{0,127}$/.test(normalized))throw new Error(`Invalid Firebase ${label}`);return normalized;}
function strings(value:unknown,result:string[]=[]):string[]{if(typeof value==="string")result.push(value);else if(Array.isArray(value))for(const item of value)strings(item,result);else if(value&&typeof value==="object")for(const item of Object.values(value as Record<string,unknown>))strings(item,result);return result;}

export class FirebaseHostingAdapter{
 constructor(private readonly execute:FirebaseCommandExecutor|null,private readonly allowedProjects:ReadonlySet<string>,private readonly enabled:boolean,private readonly rollbackExecutor:FirebaseRollbackExecutor|null=null){}
 async deploy(request:FirebaseDeploymentRequest):Promise<FirebaseDeploymentReceipt>{const project=safeId(request.targetProjectId,"project id"),channel=request.environment==="preview"?safeId(request.targetChannel??"","preview channel"):null;if(!request.approvedBy.trim()||!Number.isFinite(Date.parse(request.approvedAt))||!/^[a-f0-9]{64}$/i.test(request.artifactSnapshotHash))throw new Error("Evidence-bound human deployment approval required");if(!this.allowedProjects.has(project))throw new Error("Firebase target project is not allowlisted");if(!this.enabled||!this.execute)throw new Error("Firebase deployment execution is disabled");if(!request.credentialAvailable)throw new Error("Firebase credential is unavailable");const args=request.environment==="preview"?["hosting:channel:deploy",channel!,"--project",project,"--json","--non-interactive"]:["deploy","--only","hosting","--project",project,"--json","--non-interactive"],result=await this.execute(args,request.sourceDirectory);if(result.exitCode!==0)throw new Error(`Firebase deployment failed: ${result.stderr.slice(0,500)}`);let parsed:unknown;try{parsed=JSON.parse(result.stdout);}catch{parsed={stdout:result.stdout};}const values=strings(parsed),url=values.find(x=>/^https:\/\//i.test(x))??(request.environment==="production"?`https://${project}.web.app`:null),version=values.find(x=>/versions?\//i.test(x))??request.artifactSnapshotHash.slice(0,12),providerReceiptId=values.find(x=>/releases?\//i.test(x))??`${project}:${request.environment}:${version}`;return{providerReceiptId,url,version,verifiedAt:new Date().toISOString(),rollbackRef:request.environment==="production"?version:null};}
 async rollback(request:FirebaseDeploymentRequest,receipt:FirebaseDeploymentReceipt):Promise<{verifiedAt:string}>{if(request.environment!=="production"||!receipt.rollbackRef)throw new Error("A production rollback reference is required");if(!this.rollbackExecutor)throw new Error("Firebase rollback executor is not configured; use the Hosting release console or REST adapter");return this.rollbackExecutor(request,receipt);}
}
