import type { DatabaseSync } from "node:sqlite";
import type { AgentCompanyHost,AgentBackendConfig } from "../../backend-config/src/index.js";
import type { CompanyOperations } from "../../company-ops/src/index.js";

export type BindingTargetKind="company"|"role"|"member";
export type PipelineRole="planner"|"worker"|"reviewer";
export interface AgentBinding{id:string;companyId:string;targetKind:BindingTargetKind;targetId:string;backend:AgentCompanyHost;modelId:string;config:Record<string,unknown>;version:number;changedBy:string;changedAt:string}
export interface ResolvedAgentBinding{executionSnapshotId:string|null;companyId:string;role:PipelineRole;memberId:string|null;backend:AgentCompanyHost;modelId:string;config:Record<string,unknown>;resolution:"demo-mode"|"member"|"role"|"company"|"runtime-default";bindingId:string|null;bindingVersion:number|null}
export interface ResolvedMeetingBinding{meetingSnapshotId:string;meetingId:string;companyId:string;participantId:string;backend:AgentCompanyHost;modelId:string;config:Record<string,unknown>;resolution:"demo-mode"|"member"|"company"|"runtime-default";bindingId:string|null;bindingVersion:number|null;createdAt:string}
const json=(value:unknown)=>JSON.stringify(value??null),parse=<T>(value:unknown)=>JSON.parse(String(value)) as T,now=()=>new Date().toISOString();
const HOSTS=new Set<AgentCompanyHost>(["standalone","legacy-nvidia","openai-compatible","claude-cli","codex-cli"]),ROLES=new Set<PipelineRole>(["planner","worker","reviewer"]);

export class AgentBindingStore{
 constructor(private readonly db:DatabaseSync,private readonly companies:CompanyOperations,private readonly runtimeDefault:AgentBackendConfig){this.db.exec("CREATE TABLE IF NOT EXISTS meeting_agent_binding_snapshots_v18(meeting_id TEXT NOT NULL,participant_id TEXT NOT NULL,meeting_snapshot_id TEXT NOT NULL,binding TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(meeting_id,participant_id));");}
 set(companyId:string,actorId:string,input:{targetKind:BindingTargetKind;targetId?:string;backend:AgentCompanyHost;modelId:string;config?:Record<string,unknown>}):AgentBinding{this.companies.require(companyId,actorId,"manage-policy");const targetId=input.targetKind==="company"?companyId:String(input.targetId??"");if(!targetId||!HOSTS.has(input.backend)||!input.modelId.trim())throw new Error("Valid binding target, backend and model are required");if(input.targetKind==="role"&&!ROLES.has(targetId as PipelineRole))throw new Error("Unknown pipeline role");if(input.targetKind==="member"&&!this.db.prepare("SELECT 1 FROM company_members_v4 WHERE company_id=? AND principal_id=?").get(companyId,targetId))throw new Error("Binding member is outside company");const config=input.config??{};if(Object.keys(config).some(key=>/(api.?key|token|secret|password|credential)/i.test(key)))throw new Error("Credentials cannot be stored in agent bindings");const prior=this.db.prepare("SELECT id,version FROM agent_bindings_v7 WHERE company_id=? AND target_kind=? AND target_id=?").get(companyId,input.targetKind,targetId) as {id:string;version:number}|undefined,id=prior?.id??crypto.randomUUID(),version=Number(prior?.version??0)+1,changedAt=now();this.db.prepare("INSERT OR REPLACE INTO agent_bindings_v7 VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,companyId,input.targetKind,targetId,input.backend,input.modelId,json(config),version,actorId,changedAt);this.audit(companyId,"AGENT_BINDING_CHANGED",{actorId,id,targetKind:input.targetKind,targetId,backend:input.backend,modelId:input.modelId,version});return this.binding(id)!;}
 list(companyId:string,actorId:string):AgentBinding[]{this.companies.require(companyId,actorId,"view");return(this.db.prepare("SELECT id FROM agent_bindings_v7 WHERE company_id=? ORDER BY target_kind,target_id").all(companyId) as Array<{id:string}>).map(row=>this.binding(row.id)!);}
 resolveRun(runId:string,role:PipelineRole):ResolvedAgentBinding{const existing=this.snapshot(runId,role);if(existing?.executionSnapshotId||existing&&!this.companies.governanceForRun(runId,role))return existing;this.freezeRun(runId);const resolved=this.snapshot(runId,role);if(!resolved)throw new Error(`Run binding context missing: ${runId}`);return resolved;}
 snapshots(runId:string):ResolvedAgentBinding[]{return(this.db.prepare("SELECT role FROM run_agent_binding_snapshots_v7 WHERE run_id=? ORDER BY role").all(runId) as Array<{role:PipelineRole}>).map(row=>this.snapshot(runId,row.role)!);}
 snapshotsForActor(runId:string,actorId:string):ResolvedAgentBinding[]{const context=this.companies.governanceForRun(runId);if(!context)throw new Error("Run is not linked to a company");this.companies.require(context.companyId,actorId,"view");return this.snapshots(runId);}
 resolveMeeting(meetingId:string,participantId:string):ResolvedMeetingBinding{const existing=this.meetingSnapshot(meetingId,participantId);if(existing)return existing;this.freezeMeeting(meetingId);const resolved=this.meetingSnapshot(meetingId,participantId);if(!resolved)throw new Error("Meeting participant binding snapshot missing");return resolved;}
 freezeMeeting(meetingId:string):string{const meeting=this.companies.meeting(meetingId);if(!meeting)throw new Error("Meeting missing");const prior=this.db.prepare("SELECT meeting_snapshot_id FROM meeting_agent_binding_snapshots_v18 WHERE meeting_id=? LIMIT 1").get(meetingId) as {meeting_snapshot_id:string}|undefined;if(prior)return prior.meeting_snapshot_id;const mode=String((this.db.prepare("SELECT mode FROM companies_v4 WHERE id=?").get(meeting.companyId) as {mode:string}).mode),meetingSnapshotId=crypto.randomUUID(),createdAt=now(),participants=this.db.prepare(`SELECT principal_id FROM company_members_v4 WHERE company_id=? AND kind='agent' AND principal_id IN (${meeting.participantIds.map(()=>"?").join(",")||"NULL"}) ORDER BY principal_id`).all(meeting.companyId,...meeting.participantIds) as Array<{principal_id:string}>;this.db.exec("BEGIN IMMEDIATE");try{if(mode!=="demo")this.ensureCompanyDefault(meeting.companyId);for(const {principal_id:participantId} of participants){const selected=mode==="demo"?null:this.find(meeting.companyId,"member",participantId)??this.find(meeting.companyId,"company",meeting.companyId),binding:ResolvedMeetingBinding=mode==="demo"?{meetingSnapshotId,meetingId,companyId:meeting.companyId,participantId,backend:"standalone",modelId:"phase0-model",config:{},resolution:"demo-mode",bindingId:null,bindingVersion:null,createdAt}:selected?{meetingSnapshotId,meetingId,companyId:meeting.companyId,participantId,backend:selected.backend,modelId:selected.modelId,config:selected.config,resolution:selected.targetKind as "member"|"company",bindingId:selected.id,bindingVersion:selected.version,createdAt}:{meetingSnapshotId,meetingId,companyId:meeting.companyId,participantId,backend:this.runtimeDefault.host,modelId:this.runtimeDefault.model,config:{},resolution:"runtime-default",bindingId:null,bindingVersion:null,createdAt};this.db.prepare("INSERT INTO meeting_agent_binding_snapshots_v18 VALUES(?,?,?,?,?)").run(meetingId,participantId,meetingSnapshotId,json(binding),createdAt);}this.audit(meeting.companyId,"MEETING_AGENT_BINDINGS_SNAPSHOTTED",{meetingId,meetingSnapshotId,participantIds:participants.map(x=>x.principal_id)});this.db.exec("COMMIT");return meetingSnapshotId;}catch(error){this.db.exec("ROLLBACK");throw error;}}
 meetingSnapshots(meetingId:string):ResolvedMeetingBinding[]{return(this.db.prepare("SELECT participant_id FROM meeting_agent_binding_snapshots_v18 WHERE meeting_id=? ORDER BY participant_id").all(meetingId) as Array<{participant_id:string}>).map(x=>this.meetingSnapshot(meetingId,x.participant_id)!);}
 freezeRun(runId:string):string|null{
  const context=this.companies.governanceForRun(runId),companyId=context?.companyId??"",mode=context?String((this.db.prepare("SELECT mode FROM companies_v4 WHERE id=?").get(companyId) as {mode:string}).mode):"live",executionSnapshotId=context?(this.companies.executionSnapshotId(runId)??crypto.randomUUID()):null;
  this.db.exec("BEGIN IMMEDIATE");
  try{
   if(context){if(mode!=="demo")this.ensureCompanyDefault(companyId);this.companies.prepareExecutionSnapshot(runId,executionSnapshotId!);}
   for(const role of ["planner","worker","reviewer"] as PipelineRole[]){
    const prior=this.snapshot(runId,role);if(prior){const linked={...prior,executionSnapshotId};this.db.prepare("UPDATE run_agent_binding_snapshots_v7 SET binding=?,execution_snapshot_id=? WHERE run_id=? AND role=?").run(json(linked),executionSnapshotId,runId,role);continue;}
    const memberId=context?(this.companies.roleProfileForRun(runId,role)?.memberId??null):this.memberForRun(runId,role);let resolved:ResolvedAgentBinding;
    if(mode==="demo")resolved={executionSnapshotId,companyId,role,memberId,backend:"standalone",modelId:"phase0-model",config:{},resolution:"demo-mode",bindingId:null,bindingVersion:null};
    else{const selected=context?((memberId?this.find(companyId,"member",memberId):null)??this.find(companyId,"role",role)??this.find(companyId,"company",companyId)):null;resolved=selected?{executionSnapshotId,companyId,role,memberId,backend:selected.backend,modelId:selected.modelId,config:selected.config,resolution:selected.targetKind,bindingId:selected.id,bindingVersion:selected.version}:{executionSnapshotId,companyId,role,memberId,backend:this.runtimeDefault.host,modelId:this.runtimeDefault.model,config:{},resolution:"runtime-default",bindingId:null,bindingVersion:null};}
    this.db.prepare("INSERT INTO run_agent_binding_snapshots_v7(run_id,role,company_id,member_id,binding,resolution,created_at,execution_snapshot_id) VALUES(?,?,?,?,?,?,?,?)").run(runId,role,companyId,memberId,json(resolved),resolved.resolution,now(),executionSnapshotId);
   }
   if(context){this.companies.completeExecutionSnapshot(runId,executionSnapshotId!);this.companies.startPlanningInExecutionSnapshot(runId,executionSnapshotId!);this.audit(companyId,"RUN_AGENT_BINDINGS_SNAPSHOTTED",{runId,executionSnapshotId});}this.db.exec("COMMIT");return executionSnapshotId;
  }catch(error){this.db.exec("ROLLBACK");throw error;}
 }
 private ensureCompanyDefault(companyId:string):void{if(this.find(companyId,"company",companyId))return;const id=crypto.randomUUID(),changedAt=now();this.db.prepare("INSERT INTO agent_bindings_v7 VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,companyId,"company",companyId,this.runtimeDefault.host,this.runtimeDefault.model,json({}),1,"system-runtime-default",changedAt);this.audit(companyId,"AGENT_BINDING_DEFAULTED",{id,backend:this.runtimeDefault.host,modelId:this.runtimeDefault.model});}
 private memberForRun(runId:string,role:PipelineRole):string|null{const responsibility=role==="worker"?"executor":role==="reviewer"?"reviewer":"owner",row=this.db.prepare("SELECT a.principal_id FROM assignments_v3 a JOIN board_tasks_v3 t ON t.id=a.task_id WHERE t.run_id=? AND a.kind='agent' AND a.responsibility=? ORDER BY a.principal_id LIMIT 1").get(runId,responsibility) as {principal_id:string}|undefined;return row?.principal_id??null;}
 private find(companyId:string,targetKind:BindingTargetKind,targetId:string):AgentBinding|null{const row=this.db.prepare("SELECT id FROM agent_bindings_v7 WHERE company_id=? AND target_kind=? AND target_id=?").get(companyId,targetKind,targetId) as {id:string}|undefined;return row?this.binding(row.id):null;}
 private binding(id:string):AgentBinding|null{const row=this.db.prepare("SELECT * FROM agent_bindings_v7 WHERE id=?").get(id) as Record<string,unknown>|undefined;return row?{id:String(row.id),companyId:String(row.company_id),targetKind:String(row.target_kind) as BindingTargetKind,targetId:String(row.target_id),backend:String(row.backend) as AgentCompanyHost,modelId:String(row.model_id),config:parse(row.config),version:Number(row.version),changedBy:String(row.changed_by),changedAt:String(row.changed_at)}:null;}
 private snapshot(runId:string,role:PipelineRole):ResolvedAgentBinding|null{const row=this.db.prepare("SELECT binding FROM run_agent_binding_snapshots_v7 WHERE run_id=? AND role=?").get(runId,role) as {binding:string}|undefined;return row?parse(row.binding):null;}
 private meetingSnapshot(meetingId:string,participantId:string):ResolvedMeetingBinding|null{const row=this.db.prepare("SELECT binding FROM meeting_agent_binding_snapshots_v18 WHERE meeting_id=? AND participant_id=?").get(meetingId,participantId) as {binding:string}|undefined;return row?parse(row.binding):null;}
 private audit(companyId:string,type:string,payload:unknown):void{if(this.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='company_audit_v4'").get())this.db.prepare("INSERT INTO company_audit_v4(company_id,type,payload,created_at) VALUES(?,?,?,?)").run(companyId,type,json(payload),now());}
}
