import {useEffect,useMemo,useState} from "react";
import {Link,useSearchParams} from "react-router-dom";
import PageHeader from "../components/PageHeader.tsx";
import {useSession} from "../auth/SessionContext.tsx";
import {apiGet,apiPost,readSse} from "../api.ts";
import {useToast} from "../components/ToastContext.tsx";

type Result={kind:string;id:string;title:string;description:string;status:string|null;url:string;createdAt:string|null};
type Alert={key:string;kind:string;severity:"info"|"warning"|"critical";title:string;description:string;url:string;createdAt:string;readAt:string|null};
type Company={id:string;name:string;status:"active"|"archived";role:string};
type Safety={request:null|{status:string;requestedBy:string;requestedAt:string;cancelledAt:string|null};impact:{projects:number;members:number;goals:number;meetings:number;runs:number;auditEvents:number;blockers:string[]}};
type Report={id:string;reportType:"status"|"completion"|"blocker"|"decision";status:"unread"|"read"|"acknowledged"|"escalated"|"unroutable";currentState:string;completed:string[];blocked:string[];decisionRequired:boolean;evidenceIds:string[];nextAction:string;recipientId:string|null;createdAt:string;agentInterpretation?:{status:"model"|"deterministic-fallback";interpretation:unknown;warnings:string[]}|null};
type Delegation={id:string;sourceDepartmentId:string;targetDepartmentId:string;ownerId:string;assigneeId:string|null;completionCriteria:string[];allowedScope:string[];evidence:Array<{id:string;provenance:string;trust:"untrusted-evidence"}>;deadline:string;status:string;reviewReason:string|null;completionEvidenceIds:string[];failureReason:string|null;createdAt:string};
const kindLabel:Record<string,string>={goal:"목표",project:"프로젝트",task:"Task",run:"Run",member:"직원",meeting:"회의",decision:"결정",audit:"감사",blocked:"차단",approval:"승인",validation:"검증",budget:"예산",notification:"알림",connection:"연결"};

export default function ActivityPage(){const {actorId}=useSession(),toast=useToast(),[params,setParams]=useSearchParams(),[companyId,setCompanyId]=useState(()=>params.get("companyId")??localStorage.getItem("agent-company-os.lastCompany")??""),[companies,setCompanies]=useState<Company[]>([]),[query,setQuery]=useState(()=>params.get("q")??""),[results,setResults]=useState<Result[]>([]),[alerts,setAlerts]=useState<Alert[]>([]),[reports,setReports]=useState<Report[]>([]),[delegations,setDelegations]=useState<Delegation[]>([]),[safety,setSafety]=useState<Safety|null>(null),[tab,setTab]=useState<"alerts"|"reports"|"search"|"safety">((params.get("tab") as any)||"alerts"),[filter,setFilter]=useState("unread"),[typedName,setTypedName]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[connectionState,setConnectionState]=useState<"connecting"|"connected"|"disconnected">("connecting"),[connectionDismissed,setConnectionDismissed]=useState(false);
 async function guarded(work:()=>Promise<void>){setBusy(true);setError(null);try{await work();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function load(id=companyId){const [nextAlerts,nextReports,nextDelegations,nextSafety]=await Promise.all([apiGet<Alert[]>(`/api/companies/${encodeURIComponent(id)}/alerts?actor=${encodeURIComponent(actorId)}`),apiGet<Report[]>(`/api/companies/${encodeURIComponent(id)}/reports?actor=${encodeURIComponent(actorId)}`),apiGet<Delegation[]>(`/api/companies/${encodeURIComponent(id)}/delegations?actor=${encodeURIComponent(actorId)}`),apiGet<Safety>(`/api/companies/${encodeURIComponent(id)}/deletion-request?actor=${encodeURIComponent(actorId)}`)]);setCompanyId(id);setAlerts(nextAlerts);setReports(nextReports);setDelegations(nextDelegations);setSafety(nextSafety);localStorage.setItem("agent-company-os.lastCompany",id);const goalId=params.get("goalId");setParams(goalId?{companyId:id,tab,goalId}:{companyId:id,tab},{replace:true});}
 useEffect(()=>{void apiGet<Company[]>(`/api/companies?actor=${encodeURIComponent(actorId)}`).then(items=>{setCompanies(items);const id=items.some(x=>x.id===companyId)?companyId:items[0]?.id??"";if(id)void guarded(()=>load(id));}).catch(e=>setError(e instanceof Error?e.message:String(e)));},[]);
 useEffect(()=>{if(!companyId)return;let stopped=false,controller:AbortController|undefined,cursor=0;setConnectionState("connecting");const loop=async()=>{while(!stopped){controller=new AbortController();try{await readSse(`/api/events?companyId=${encodeURIComponent(companyId)}&after=${cursor}`,controller.signal,event=>{cursor=Math.max(cursor,event.id);},()=>{setConnectionState("connected");setConnectionDismissed(false);});if(!stopped)setConnectionState("disconnected");}catch{if(controller.signal.aborted)return;setConnectionState("disconnected");setConnectionDismissed(false);}if(!stopped)await new Promise(resolve=>window.setTimeout(resolve,1500));}};void loop();return()=>{stopped=true;controller?.abort();};},[companyId]);
 function search(){return guarded(async()=>{const items=await apiGet<Result[]>(`/api/companies/${encodeURIComponent(companyId)}/search?actor=${encodeURIComponent(actorId)}&q=${encodeURIComponent(query)}`);setResults(items);setTab("search");setParams(params.get("goalId")?{companyId,tab:"search",q:query,goalId:params.get("goalId")!}:{companyId,tab:"search",q:query},{replace:true});});}
 function read(item:Alert){if(item.kind==="connection"){setConnectionDismissed(true);return Promise.resolve();}return guarded(async()=>{if(!item.readAt)await apiPost(`/api/companies/${encodeURIComponent(companyId)}/alerts/${encodeURIComponent(item.key)}/read`,{actorId});await load();});}
 function reportAction(item:Report,action:"read"|"acknowledge"|"escalate"){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/reports/${encodeURIComponent(item.id)}/${action}`,{actorId});await load();});}
 function interpretReport(item:Report){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/reports/${encodeURIComponent(item.id)}/interpret`,{actorId});await load();});}
 function startDelegation(item:Delegation){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/delegations/${encodeURIComponent(item.id)}/actions/start`,{actorId});await load();});}
 function archive(){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/actions/archive`,{actorId});toast("회사를 안전하게 보관했습니다.");await refreshCompanies();await load();});}
 function restore(){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/actions/restore`,{actorId});toast("회사를 운영 상태로 복구했습니다.");await refreshCompanies();await load();});}
 async function refreshCompanies(){setCompanies(await apiGet<Company[]>(`/api/companies?actor=${encodeURIComponent(actorId)}`));}
 function requestDeletion(){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/deletion-request`,{actorId,companyName:typedName});toast("물리 삭제가 아닌 운영자 검토용 삭제 대기를 등록했습니다.");setTypedName("");await load();});}
 function cancelDeletion(){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/deletion-request/cancel`,{actorId});toast("삭제 대기를 취소했습니다.");await load();});}
 const connectionAlert:Alert|null=connectionState==="disconnected"&&!connectionDismissed?{key:"connection:sse",kind:"connection",severity:"critical",title:"실시간 연결이 끊겼습니다",description:"자동 재연결 중입니다. 연결이 복구될 때까지 화면 정보가 늦게 반영될 수 있습니다.",url:`/operations?companyId=${encodeURIComponent(companyId)}`,createdAt:new Date().toISOString(),readAt:null}:null;
 const company=companies.find(x=>x.id===companyId),focusedGoalId=params.get("goalId"),allAlerts=connectionAlert?[connectionAlert,...alerts]:alerts,visibleAlerts=useMemo(()=>allAlerts.filter(x=>filter==="all"||filter==="unread"&&!x.readAt||filter===x.severity),[alerts,connectionAlert,filter]),recentOutcomeReports=reports.filter(report=>report.reportType==="completion"||report.completed.length>0||report.decisionRequired||report.blocked.length>0).slice(0,3),openOutcomeCount=reports.filter(report=>report.status==="unread"||report.decisionRequired).length;
 return <div className="activity-page"><PageHeader title="결과·활동" description="AI 회사가 남긴 결과 보고, 검증 근거, 위험 신호, 회의·결정 기록을 한곳에서 확인합니다."/><section className="activity-toolbar card"><label>회사<select value={companyId} onChange={e=>void guarded(()=>load(e.target.value))}>{companies.map(x=><option key={x.id} value={x.id}>{x.name} · {x.status}</option>)}</select></label><form role="search" onSubmit={e=>{e.preventDefault();void search();}}><input aria-label="결과·활동 근거 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="맡긴 일, Task, Run, 직원, 회의, 결정 검색"/><button disabled={busy||query.trim().length<2}>검색</button></form><span className={`connection-state state-${connectionState}`} role="status">{connectionState==="connected"?"실시간 연결":connectionState==="connecting"?"연결 중":"재연결 중"}</span><span className="activity-unread" aria-label={`읽지 않은 업무 신호 ${allAlerts.filter(x=>!x.readAt).length}개`}>{allAlerts.filter(x=>!x.readAt).length}</span></section>{error&&<p className="error" role="alert">{error}</p>}
 {focusedGoalId&&<section className="card" aria-label="선택 업무 결과 활동"><div className="section-heading"><div><span className="eyebrow">GOAL ACTIVITY</span><h2>선택한 맡긴 일의 결과와 활동을 보는 중입니다</h2><p>이 화면에서 관련 알림, 보고, 검색 결과, 감사 기록을 확인하고 필요한 조치를 이어갑니다.</p></div><span className="badge">{focusedGoalId.slice(0,8)}</span></div><div className="badge-row"><Link className="button-link" to={`/goals?companyId=${encodeURIComponent(companyId)}&goalId=${encodeURIComponent(focusedGoalId)}`}>맡긴 일 상세</Link><Link className="button-link" to={`/pixel-office?companyId=${encodeURIComponent(companyId)}&goalId=${encodeURIComponent(focusedGoalId)}`}>픽셀 오피스 Live View</Link><Link className="button-link" to={`/reviews?companyId=${encodeURIComponent(companyId)}`}>결정 필요</Link></div></section>}
 <section className="result-first-summary card" aria-label="최근 맡긴 일 결과 요약"><div className="section-heading"><div><span className="eyebrow">OUTCOME FIRST</span><h2>최근 맡긴 일 결과</h2><p>시간순 로그를 보기 전에 완료·차단·결정 필요 상태를 먼저 확인합니다.</p></div><span className="badge">확인 필요 {openOutcomeCount}</span></div>{recentOutcomeReports.length?<div className="outcome-card-grid">{recentOutcomeReports.map(report=><article key={report.id} className={report.decisionRequired||report.blocked.length?"outcome-needs-action":"outcome-done"}><span>{report.reportType} · {report.status}</span><strong>{report.currentState}</strong>{report.completed.length>0&&<small>완료 {report.completed.slice(0,2).join(" · ")}</small>}{report.blocked.length>0&&<small>차단 {report.blocked.slice(0,2).join(" · ")}</small>}<p>다음 조치: {report.nextAction}</p><div>{report.decisionRequired?<Link className="button-link" to={`/reviews?companyId=${encodeURIComponent(companyId)}`}>결정하러 가기</Link>:<button className="secondary" disabled={busy} onClick={()=>void reportAction(report,"acknowledge")}>확인 완료</button>}</div></article>)}</div>:<div className="activity-empty compact"><strong>아직 새 결과 보고가 없습니다.</strong><span>업무가 완료되거나 막히면 여기에 먼저 표시됩니다.</span></div>}</section>
 <nav className="activity-tabs" aria-label="통합 활동 영역">{(["alerts","reports","search","safety"] as const).map(x=><button key={x} className={tab===x?"active":""} aria-pressed={tab===x} onClick={()=>{setTab(x);const goalId=params.get("goalId");setParams(goalId?{companyId,tab:x,goalId}:{companyId,tab:x},{replace:true});}}>{x==="alerts"?"활동 신호":x==="reports"?`결과 보고 ${reports.filter(r=>r.status==="unread"||r.decisionRequired).length}`:x==="search"?"근거 검색":"회사 안전 관리"}</button>)}</nav>
 {tab==="alerts"&&<section className="activity-layout"><aside><h2>활동 신호 필터</h2>{["unread","critical","warning","info","all"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x==="unread"?"읽지 않음":x==="all"?"전체":x} <span>{x==="unread"?allAlerts.filter(a=>!a.readAt).length:x==="all"?allAlerts.length:allAlerts.filter(a=>a.severity===x).length}</span></button>)}</aside><div className="activity-feed" role="feed" aria-label="회사 활동 신호">{visibleAlerts.map(item=><article key={item.key} className={`alert-${item.severity} ${item.readAt?"read":""}`}><i aria-hidden="true"/><div><header><span>{kindLabel[item.kind]??item.kind}</span><time>{new Date(item.createdAt).toLocaleString("ko-KR")}</time></header><h2>{item.title}</h2><p>{item.description}</p><footer><Link to={item.url} onClick={()=>void read(item)}>관련 근거 보기</Link>{!item.readAt&&<button className="secondary" onClick={()=>void read(item)}>읽음</button>}</footer></div></article>)}{!visibleAlerts.length&&<div className="activity-empty"><strong>조건에 맞는 활동 신호가 없습니다.</strong><span>새 위험 신호와 진행 알림은 실시간으로 이 목록에 합쳐집니다.</span></div>}</div></section>}
 {tab==="reports"&&<section className="activity-feed" role="feed" aria-label="결과 보고함">{reports.map(item=><article key={item.id} className={`alert-${item.reportType==="blocker"||item.decisionRequired?"critical":"info"} ${item.status==="acknowledged"?"read":""}`}><i aria-hidden="true"/><div><header><span>{item.reportType} · {item.status}</span><time>{new Date(item.createdAt).toLocaleString("ko-KR")}</time></header><h2>{item.currentState}</h2>{item.completed.length>0&&<p>완료: {item.completed.join(", ")}</p>}{item.blocked.length>0&&<p>차단: {item.blocked.join(", ")}</p>}<p>다음 조치: {item.nextAction}</p><small>근거: {item.evidenceIds.join(", ")}</small><footer>{(item.status==="unread"||item.status==="escalated")&&<button className="secondary" onClick={()=>void reportAction(item,"read")}>읽음</button>}{item.status!=="acknowledged"&&item.status!=="unroutable"&&<button onClick={()=>void reportAction(item,"acknowledge")}>확인 완료</button>}{item.status!=="unroutable"&&<button className="secondary" onClick={()=>void reportAction(item,"escalate")}>상위 보고</button>}</footer></div></article>)}{!reports.length&&<div className="activity-empty"><strong>현재 확인할 결과 보고가 없습니다.</strong><span>업무 상태 전이와 검증 결과가 발생하면 보고가 이곳에 라우팅됩니다.</span></div>}</section>}
 {tab==="reports"&&<section className="search-results" aria-label="Agent 보고 해석"><header><h2>역할 관점 해석</h2><span>{reports.filter(x=>x.agentInterpretation).length}건</span></header>{reports.map(item=><article key={`interpret:${item.id}`}><span className="result-kind kind-report">해석</span><div><strong>{item.currentState} · {item.agentInterpretation?.status??"미생성"}</strong>{item.agentInterpretation?<pre>{JSON.stringify(item.agentInterpretation.interpretation,null,2)}</pre>:<p>결정론적 사실은 변경하지 않고 위험과 제안만 추가합니다.</p>}</div><button className="secondary" disabled={busy} onClick={()=>void interpretReport(item)}>역할 관점 생성</button></article>)}</section>}
 {tab==="reports"&&<section className="search-results" aria-label="부서 간 위임과 인계"><header><h2>위임·인계</h2><span>{delegations.length}건</span></header>{delegations.map(item=><article key={item.id}><span className={`result-kind kind-${item.status}`}>인계</span><div><strong>{item.sourceDepartmentId} → {item.targetDepartmentId} · {item.status}</strong><p>Owner {item.ownerId} · 담당 {item.assigneeId??"검토 대기"} · 기한 {new Date(item.deadline).toLocaleString("ko-KR")}</p><small>완료 기준: {item.completionCriteria.join(", ")} · Scope: {item.allowedScope.join(", ")} · 이전 산출물은 untrusted evidence</small>{item.failureReason&&<p>실패: {item.failureReason}</p>}</div>{item.assigneeId===actorId&&(item.status==="approved"||item.status==="reassigned")&&<button disabled={busy} onClick={()=>void startDelegation(item)}>업무 시작</button>}</article>)}{!delegations.length&&<div className="activity-empty"><strong>현재 관련된 위임·인계가 없습니다.</strong><span>타 부서 위임은 대상 부서 관리자 검토 후 담당자에게 전달됩니다.</span></div>}</section>}
 {tab==="search"&&<section className="search-results" aria-live="polite"><header><h2>검색 결과</h2><span>{results.length}건</span></header>{results.map(item=><Link key={`${item.kind}:${item.id}`} to={item.url}><span className={`result-kind kind-${item.kind}`}>{kindLabel[item.kind]??item.kind}</span><div><strong>{item.title}</strong><p>{item.description}</p><small>{item.status??""}{item.createdAt?` · ${new Date(item.createdAt).toLocaleString("ko-KR")}`:""}</small></div><b aria-hidden="true">→</b></Link>)}{query&&results.length===0&&<div className="activity-empty"><strong>검색 결과가 없습니다.</strong><span>두 글자 이상의 다른 검색어를 사용하세요.</span></div>}</section>}
 {tab==="safety"&&company&&safety&&<section className="safety-panel"><header><div><span className={`company-state state-${company.status}`}>{company.status==="active"?"운영 중":"보관"}</span><h2>{company.name}</h2></div>{company.status==="active"?<button className="secondary" disabled={busy||safety.impact.blockers.length>0} onClick={()=>void archive()}>안전 보관</button>:<button onClick={()=>void restore()}>운영 복구</button>}</header><div className="impact-grid">{Object.entries(safety.impact).filter(([key])=>key!=="blockers").map(([key,value])=><article key={key}><span>{key}</span><strong>{String(value)}</strong></article>)}</div>{safety.impact.blockers.length>0&&<div className="safety-blockers" role="alert"><strong>현재 보관·삭제 차단 조건</strong>{safety.impact.blockers.map(x=><span key={x}>{x}</span>)}</div>}<section className="deletion-zone"><h3>삭제 대기 요청</h3><p>데이터를 즉시 지우지 않습니다. 보관된 회사만 이름 재입력과 영향 확인 후 운영자 검토 대기로 전환합니다.</p>{safety.request?.status==="pending"?<div className="pending-deletion"><strong>삭제 검토 대기 중</strong><span>{safety.request.requestedBy} · {new Date(safety.request.requestedAt).toLocaleString("ko-KR")}</span><button className="secondary" onClick={()=>void cancelDeletion()}>삭제 대기 취소</button></div>:<div className="deletion-confirm"><label>회사명 재입력<input value={typedName} onChange={e=>setTypedName(e.target.value)} placeholder={company.name}/></label><button disabled={busy||company.status!=="archived"||typedName!==company.name||safety.impact.blockers.length>0} onClick={()=>void requestDeletion()}>삭제 검토 요청</button></div>}</section></section>}
 </div>}
