import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import PageHeader from "../components/PageHeader.tsx";
import CompanyModeBadge from "../components/CompanyModeBadge.tsx";
import ConfirmButton from "../components/ConfirmButton.tsx";
import { useSession } from "../auth/SessionContext.tsx";
import { apiGet, apiPost } from "../api.ts";
import { useToast } from "../components/ToastContext.tsx";
import type { CompanyMode, CompanyRecord } from "../types.ts";

type CompanyListItem=CompanyRecord&{role:string;projectCount:number};

export default function CompaniesPage(){
  const {actorId}=useSession(),navigate=useNavigate(),toast=useToast();
  const [companies,setCompanies]=useState<CompanyListItem[]>([]),[filter,setFilter]=useState<"active"|"archived">("active"),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[createOpen,setCreateOpen]=useState(false);
  const [id,setId]=useState(""),[name,setName]=useState(""),[budget,setBudget]=useState("100"),[mode,setMode]=useState<CompanyMode>("live"),[editing,setEditing]=useState<string|null>(null),[editName,setEditName]=useState(""),[editBudget,setEditBudget]=useState("0"),[editMode,setEditMode]=useState<CompanyMode>("live");
  async function load(){setError(null);try{const items=await apiGet<CompanyListItem[]>(`/api/companies?actor=${encodeURIComponent(actorId)}`);setCompanies(Array.isArray(items)?items:[]);}catch(e){setError(e instanceof Error?e.message:String(e));}}
  useEffect(()=>{void load();},[actorId]);
  const visible=useMemo(()=>companies.filter(item=>item.status===filter&&(!query.trim()||`${item.name} ${item.id}`.toLowerCase().includes(query.trim().toLowerCase()))),[companies,filter,query]);
  function select(item:CompanyListItem){localStorage.setItem("agent-company-os.lastCompany",item.id);navigate(`/company?companyId=${encodeURIComponent(item.id)}`);}
  async function create(){setBusy(true);setError(null);try{const companyId=id.trim().toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-|-$/g,""),workspaceId=`${companyId}-workspace`;if(!companyId||!name.trim())throw new Error("회사 ID와 이름을 입력하세요.");await apiPost("/api/workspaces",{id:workspaceId,name:`${name.trim()} Workspace`});await apiPost<CompanyRecord>("/api/companies",{id:companyId,name:name.trim(),workspaceId,budgetLimit:Number(budget),mandatoryReviews:["review"],mandatoryApprovals:["result"],allowedTools:["build","test","lint","security"],ownerId:actorId,mode});localStorage.setItem("agent-company-os.lastCompany",companyId);toast("회사를 생성했습니다.");navigate(`/company?companyId=${encodeURIComponent(companyId)}`);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  function beginEdit(item:CompanyListItem){setEditing(item.id);setEditName(item.name);setEditBudget(String(item.budgetLimit));setEditMode(item.mode);}
  async function save(item:CompanyListItem){setBusy(true);setError(null);try{await apiPost(`/api/companies/${encodeURIComponent(item.id)}/actions/update`,{actorId,name:editName,budgetLimit:Number(editBudget),mode:editMode});setEditing(null);toast("회사 정보를 수정했습니다.");await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function lifecycle(item:CompanyListItem,action:"archive"|"restore"){setBusy(true);setError(null);try{await apiPost(`/api/companies/${encodeURIComponent(item.id)}/actions/${action}`,{actorId});if(action==="archive"&&localStorage.getItem("agent-company-os.lastCompany")===item.id)localStorage.removeItem("agent-company-os.lastCompany");toast(action==="archive"?"회사를 보관했습니다.":"회사를 복구했습니다.");await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  return <div className="companies-page">
    <PageHeader title="내 회사" description="운영할 회사를 선택하거나 새 회사를 만듭니다." />
    <section className="company-list-toolbar card" aria-label="회사 목록 도구"><div className="section-tabs"><button className={filter==="active"?"active":""} aria-pressed={filter==="active"} onClick={()=>setFilter("active")}>운영 중 {companies.filter(x=>x.status==="active").length}</button><button className={filter==="archived"?"active":""} aria-pressed={filter==="archived"} onClick={()=>setFilter("archived")}>보관 {companies.filter(x=>x.status==="archived").length}</button></div><input aria-label="회사 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="회사명 또는 ID 검색"/><button onClick={()=>setCreateOpen(value=>!value)}>{createOpen?"생성 취소":"새 회사 만들기"}</button></section>
    {createOpen&&<section className="company-create card" aria-labelledby="company-create-title"><h2 id="company-create-title">새 회사</h2><div className="company-form-grid"><label>회사 ID<input value={id} onChange={e=>setId(e.target.value)} placeholder="my-company"/></label><label>회사명<input value={name} onChange={e=>setName(e.target.value)} placeholder="My Company"/></label><label>초기 예산<input type="number" min="0" value={budget} onChange={e=>setBudget(e.target.value)}/></label><label>운영 모드<select value={mode} onChange={e=>setMode(e.target.value as CompanyMode)}><option value="live">실제 운영</option><option value="demo">데모</option></select></label></div><p className="field-help">기본 검토·결과 승인·검증 도구 정책과 전용 Workspace가 함께 생성됩니다.</p><button disabled={busy||!id.trim()||!name.trim()||Number(budget)<0} onClick={()=>void create()}>{busy?"생성 중…":"회사 생성 후 들어가기"}</button></section>}
    {error&&<p className="error" role="alert">{error}</p>}
    {visible.length?<section className="company-card-grid" aria-label={filter==="active"?"운영 중인 회사":"보관된 회사"}>{visible.map(item=><article className="company-selection-card" key={item.id}>
      {editing===item.id?<><div className="company-form-grid compact"><label>회사명<input value={editName} onChange={e=>setEditName(e.target.value)}/></label><label>예산<input type="number" value={editBudget} onChange={e=>setEditBudget(e.target.value)}/></label><label>모드<select value={editMode} onChange={e=>setEditMode(e.target.value as CompanyMode)}><option value="live">실제 운영</option><option value="demo">데모</option></select></label></div><div className="row"><button disabled={busy||!editName.trim()} onClick={()=>void save(item)}>저장</button><button className="secondary" onClick={()=>setEditing(null)}>취소</button></div></>:<><header><div className="company-mark" aria-hidden="true">{item.name.slice(0,2).toUpperCase()}</div><div><h2>{item.name}</h2><p>{item.id}</p></div><CompanyModeBadge mode={item.mode}/></header><dl><div><dt>내 역할</dt><dd>{item.role}</dd></div><div><dt>프로젝트</dt><dd>{item.projectCount}</dd></div><div><dt>예산</dt><dd>{item.budgetLimit}</dd></div><div><dt>상태</dt><dd>{item.status==="active"?"운영 중":"보관"}</dd></div></dl><footer>{item.status==="active"&&<button onClick={()=>select(item)}>회사 들어가기</button>}{item.role==="owner"&&<button className="secondary" onClick={()=>beginEdit(item)}>수정</button>}{item.role==="owner"&&(item.status==="active"?<ConfirmButton label="보관" confirmLabel="다시 눌러 보관" disabled={busy} onConfirm={()=>void lifecycle(item,"archive")}/>:<button className="secondary" disabled={busy} onClick={()=>void lifecycle(item,"restore")}>운영 복구</button>)}</footer></>}
    </article>)}</section>:<section className="empty-company-state"><div className="company-mark large" aria-hidden="true">+</div><h2>{filter==="active"?"운영 중인 회사가 없습니다.":"보관된 회사가 없습니다."}</h2><p>{filter==="active"?"새 회사를 만들어 첫 목표를 시작하세요.":"보관한 회사는 여기에서 다시 운영 상태로 복구할 수 있습니다."}</p>{filter==="active"&&<button onClick={()=>setCreateOpen(true)}>새 회사 만들기</button>}</section>}
  </div>;
}
