import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import PageHeader from "../components/PageHeader.tsx";
import { useSession } from "../auth/SessionContext.tsx";
import { apiGet, apiPost } from "../api.ts";
import { useToast } from "../components/ToastContext.tsx";
import { safeUserText, runStatusLabel, uuid } from "../format.ts";

type GoalStatus="draft"|"active"|"blocked"|"completed"|"cancelled";
type DeliveryStage="discovery"|"delivery-planning"|"build"|"release"|"operate";
type DeliveryStageStatus="pending"|"in-progress"|"validation-waiting"|"review-waiting"|"owner-approval-waiting"|"revision-requested"|"approved"|"blocked"|"cancelled";
interface DeliveryProcessSnapshot {process:{id:string;version:number;currentStage:DeliveryStage;status:string};currentStageInstance:{id:string;stage:DeliveryStage;attempt:number;status:DeliveryStageStatus;runId:string|null;meetingId:string|null};stages:Array<{id:string;stage:DeliveryStage;attempt:number;status:DeliveryStageStatus;runId:string|null;meetingId:string|null}>;artifactSnapshots:Array<{id:string;stageInstanceId:string;version:number;artifactIds:string[];stale:boolean}>;ownerReview:{id:string;status:"pending"|"approved"|"revision-requested"|"on-hold";koreanSummary:string;decisions:string[];risks:string[];openItems:string[];evidenceIds:string[];snapshotHash:string}|null;deployment:{provider:"firebase";environment:"preview"|"production";action:"deploy"|"skip";targetProjectId:string|null;targetChannel:string|null;status:string;receipt:{url:string|null;verifiedAt:string}|null;failure:string|null}|null}
interface Goal {id:string;companyId:string;title:string;description:string;status:GoalStatus;ownerId:string;completionCriteria:string[];budgetLimit:number;dueAt:string|null;projectCount:number;projectIds?:string[];progress:number;blocked:number;pendingApprovals:number;validationFailures:number;spent:number}
interface Task {id:string;projectId:string;milestoneId:string|null;title:string;status:string;runId:string|null;spent:number;budgetLimit:number;assignments?:Array<{principalId:string;responsibility:string}>;run?:{id:string;status:string;spent:number}|null;approvals?:Array<{status:string}>;artifacts?:Array<{id:string}>;stale?:unknown[]}
interface GoalSnapshot {goal:Goal;deliveryProcess:DeliveryProcessSnapshot|null;metrics:{total:number;done:number;progress:number;blocked:number;pendingApprovals:number;validationFailures:number;spent:number;budget:number};projects:Array<{project:{id:string;name:string;spent:number;budgetLimit:number};milestones:Array<{id:string;title:string;status:string;progress:{total:number;done:number}}> ;tasks:Task[]}>;nextActions:string[];timeline:Array<{type:string;createdAt:string;projectId?:string;payload?:unknown}>;snapshotHash:string}
interface GoalLaunchResponse {goal:Goal;deliveryProcess:DeliveryProcessSnapshot;provisioning:{department:{id:string;name:string;created:boolean};team:Array<{id:string;created:boolean;responsibility:string}>;projectId:string;milestoneId:string;taskId:string;runId:string};snapshot:GoalSnapshot}
interface Company {id:string;name:string;role:string;projectCount:number;status:string}
interface Portfolio {portfolio:{projects:Array<{project:{id:string;name:string}}>}}
type ViewMode="hierarchy"|"board"|"timeline";

const statusLabel:Record<string,string>={draft:"초안",active:"진행",blocked:"차단",completed:"완료",cancelled:"취소","in-progress":"진행 중",ready:"준비",review:"검토",backlog:"대기",done:"완료"};
const deliveryStages:DeliveryStage[]=["discovery","delivery-planning","build","release","operate"];
const deliveryStageLabel:Record<DeliveryStage,string>={discovery:"기획","delivery-planning":"실행계획",build:"개발",release:"배포",operate:"운영·완료"};
const deliveryStatusLabel:Record<DeliveryStageStatus,string>={pending:"시작 대기","in-progress":"Agent 작업 중","validation-waiting":"자동 검증 대기","review-waiting":"팀 검토 대기","owner-approval-waiting":"오너 결정 필요","revision-requested":"수정 요청됨",approved:"승인 완료",blocked:"차단됨",cancelled:"취소됨"};
const eventLabel:Record<string,string>={"goal.created":"목표 생성","goal.updated":"목표 수정","goal.status.changed":"목표 상태 변경",GOAL_CREATED:"목표 생성",GOAL_UPDATED:"목표 수정",GOAL_STATUS_CHANGED:"목표 상태 변경",BOARD_TASK_CREATED:"업무 생성",TASK_ASSIGNED:"담당자 배정",TASK_TRANSITIONED:"업무 상태 변경",RUN_LINKED:"실행 연결",PROJECT_BUDGET_SETTLED:"예산 정산",VALIDATION_COMPLETED:"자동 검증 완료",GOAL_DELIVERY_PROCESS_STARTED:"목표 진행 시작",GOAL_DELIVERY_STAGE_TRANSITIONED:"진행 단계 변경",GOAL_DELIVERY_OWNER_REVIEW_REQUESTED:"오너 검토 요청",MEETING_SUMMARY_DRAFTED:"회의 요약 생성"};
function timelineLabel(type:string){return eventLabel[type]??(type.includes("MEETING")?"회의 활동":type.includes("APPROVAL")?"승인 활동":type.includes("RUN")?"실행 활동":type.includes("TASK")?"업무 활동":"진행 기록");}

export default function GoalsPage(){
  const {actorId}=useSession(),toast=useToast(),[params,setParams]=useSearchParams();
  const [companyId,setCompanyId]=useState(()=>params.get("companyId")??localStorage.getItem("agent-company-os.lastCompany")??"");
  const [companies,setCompanies]=useState<Company[]>([]),[goals,setGoals]=useState<Goal[]>([]),[snapshot,setSnapshot]=useState<GoalSnapshot|null>(null),[projects,setProjects]=useState<Array<{id:string;name:string}>>([]);
  const [selectedGoalId,setSelectedGoalId]=useState(()=>params.get("goalId")??""),[view,setView]=useState<ViewMode>("hierarchy"),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
  const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[criteria,setCriteria]=useState(""),[budget,setBudget]=useState("20"),[dueAt,setDueAt]=useState(""),[projectId,setProjectId]=useState("");
  const [autoSetup,setAutoSetup]=useState(true),[repoPath,setRepoPath]=useState("."),[requestedPaths,setRequestedPaths]=useState("src"),[launchNote,setLaunchNote]=useState<string|null>(null);
  const [rough,setRough]=useState(""),[draftBusy,setDraftBusy]=useState(false),[draftNote,setDraftNote]=useState<string|null>(null);
  const [revisionReason,setRevisionReason]=useState("");
  const [changeMessage,setChangeMessage]=useState("");
  const [deploymentChoice,setDeploymentChoice]=useState<""|"skip"|"preview"|"production">(""),[firebaseProject,setFirebaseProject]=useState(""),[firebaseChannel,setFirebaseChannel]=useState("goal-preview"),[deploymentConfirmation,setDeploymentConfirmation]=useState("");
  async function guarded(work:()=>Promise<void>){setBusy(true);setError(null);try{await work();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function load(id=companyId,requestedGoal=selectedGoalId){
    const [items,company]=await Promise.all([apiGet<Goal[]>(`/api/companies/${encodeURIComponent(id)}/goals?actor=${encodeURIComponent(actorId)}`),apiGet<Portfolio>(`/api/companies/${encodeURIComponent(id)}?actor=${encodeURIComponent(actorId)}`)]);
    const available=company.portfolio.projects.map(x=>x.project);setGoals(items);setProjects(available);setCompanyId(id);localStorage.setItem("agent-company-os.lastCompany",id);
    const goalId=items.some(x=>x.id===requestedGoal)?requestedGoal:items[0]?.id??"";setSelectedGoalId(goalId);setProjectId(available[0]?.id??"");
    if(goalId)setSnapshot(await apiGet<GoalSnapshot>(`/api/companies/${encodeURIComponent(id)}/goals/${encodeURIComponent(goalId)}?actor=${encodeURIComponent(actorId)}`));else setSnapshot(null);
    setParams(goalId?{companyId:id,goalId}:{companyId:id},{replace:true});
  }
  useEffect(()=>{void apiGet<Company[]>(`/api/companies?actor=${encodeURIComponent(actorId)}`).then(items=>{const active=items.filter(x=>x.status==="active");setCompanies(active);const id=active.some(x=>x.id===companyId)?companyId:active[0]?.id??"";if(id)void guarded(()=>load(id,params.get("goalId")??""));}).catch(e=>setError(e instanceof Error?e.message:String(e)));},[]);
  function selectGoal(id:string){setSelectedGoalId(id);void guarded(()=>load(companyId,id));}
  function createGoal(){return guarded(async()=>{const completionCriteria=criteria.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),id=uuid(),due=dueAt?new Date(`${dueAt}T23:59:59`).toISOString():null;if(autoSetup){const result=await apiPost<GoalLaunchResponse>(`/api/companies/${encodeURIComponent(companyId)}/goals/launch`,{actorId,id,title,description,ownerId:actorId,completionCriteria,budgetLimit:Number(budget),dueAt:due,repoPath,requestedPaths:requestedPaths.split(",").map(x=>x.trim()).filter(Boolean),requestedRisk:"medium"});setLaunchNote(`${result.provisioning.department.name} · Agent ${result.provisioning.team.length}명 · 프로젝트와 첫 Run을 자동 구성했습니다.`);toast("목표를 만들고 Agent 실행 준비를 시작했습니다.");}else{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/goals`,{actorId,id,title,description,ownerId:actorId,completionCriteria,budgetLimit:Number(budget),dueAt:due,status:"draft"});setLaunchNote("목표만 초안으로 저장했습니다. 프로젝트와 담당자는 직접 연결하세요.");toast("회사 목표 초안을 생성했습니다.");}setTitle("");setDescription("");setCriteria("");setRough("");setDraftNote(null);await load(companyId,id);});}
  async function draftFromRough(){if(!rough.trim())return;setDraftBusy(true);setError(null);setDraftNote(null);try{const draft=await apiPost<{title:string;description:string;completionCriteria:string[];status:"model"|"fallback";warnings:string[]}>(`/api/companies/${encodeURIComponent(companyId)}/goals/draft`,{actorId,rough});setTitle(draft.title);setDescription(draft.description);setCriteria(draft.completionCriteria.join("\n"));setDraftNote(draft.status==="fallback"?"AI 모델이 설정되지 않았거나 응답이 없어 입력하신 내용을 그대로 옮겼습니다. 목표명과 완료 기준을 직접 정리해 주세요.":"AI가 구체화한 초안입니다. 제출 전에 검토·수정하세요.");}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setDraftBusy(false);}}
  function linkProject(){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/goals/${encodeURIComponent(selectedGoalId)}/projects`,{actorId,projectId});toast("프로젝트를 목표에 연결했습니다.");await load(companyId,selectedGoalId);});}
  function provisionExistingGoal(){return guarded(async()=>{const result=await apiPost<GoalLaunchResponse>(`/api/companies/${encodeURIComponent(companyId)}/goals/${encodeURIComponent(selectedGoalId)}/actions/provision`,{actorId,repoPath:".",requestedPaths:["src"],requestedRisk:"medium"});setLaunchNote(`${result.provisioning.department.name} · Agent ${result.provisioning.team.length}명 · 프로젝트와 첫 Run을 기존 목표에 연결했습니다.`);toast("기존 목표의 자동 실행 구성을 시작했습니다.");await load(companyId,selectedGoalId);});}
  function retryCurrentStageRun(){return guarded(async()=>{const runId=snapshot?.deliveryProcess?.currentStageInstance.runId;if(!runId)throw new Error("재시도할 Run이 없습니다.");await apiPost(`/api/runs/${encodeURIComponent(runId)}/actions/retry`,{userId:actorId});toast("실패한 단계의 재시도를 시작했습니다.");await load(companyId,selectedGoalId);});}
  function transition(status:GoalStatus){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/goals/${encodeURIComponent(selectedGoalId)}/actions/transition`,{actorId,status});toast(`목표 상태를 ${statusLabel[status]}으로 변경했습니다.`);await load(companyId,selectedGoalId);});}
  function transitionDelivery(decision:"approved"|"revision-requested"|"on-hold"|"resume"){return guarded(async()=>{const delivery=snapshot?.deliveryProcess;if(!delivery?.ownerReview)return;if(!["approved","resume"].includes(decision)&&!revisionReason.trim())throw new Error(decision==="on-hold"?"보류 사유를 먼저 입력해 주세요.":"수정할 내용을 먼저 입력해 주세요.");let deployment:unknown;if(decision==="approved"&&delivery.process.currentStage==="release"){if(!deploymentChoice)throw new Error("배포 여부를 선택해 주세요.");if(deploymentChoice!=="skip"&&!firebaseProject.trim())throw new Error("Firebase 프로젝트 ID를 입력해 주세요.");if(deploymentChoice==="production"&&deploymentConfirmation!==`DEPLOY ${firebaseProject.trim()}`)throw new Error("운영 배포 확인 문구가 대상 프로젝트와 일치하지 않습니다.");deployment={action:deploymentChoice==="skip"?"skip":"deploy",environment:deploymentChoice==="production"?"production":"preview",targetProjectId:deploymentChoice==="skip"?null:firebaseProject.trim(),targetChannel:deploymentChoice==="preview"?firebaseChannel.trim()||`goal-${selectedGoalId.slice(0,12)}`:null,expectedSnapshotHash:delivery.ownerReview.snapshotHash,confirmation:deploymentChoice==="production"?deploymentConfirmation:undefined};}await apiPost(`/api/companies/${encodeURIComponent(companyId)}/goals/${encodeURIComponent(selectedGoalId)}/delivery-process/owner-review`,{actorId,decision,reason:revisionReason.trim()||undefined,deployment});setRevisionReason("");setDeploymentChoice("");setDeploymentConfirmation("");toast(decision==="approved"?"현재 단계를 승인하고 다음 단계로 넘겼습니다.":decision==="on-hold"?"현재 검토를 보류했습니다.":decision==="resume"?"오너 검토를 다시 시작했습니다.":"수정 요청을 기록하고 새 작업 시도를 만들었습니다.");await load(companyId,selectedGoalId);});}
  function submitChangeRequest(){return guarded(async()=>{if(!changeMessage.trim())throw new Error("추가 요구사항을 입력해 주세요.");await apiPost(`/api/companies/${encodeURIComponent(companyId)}/goals/${encodeURIComponent(selectedGoalId)}/delivery-process/change-requests`,{actorId,id:uuid(),message:changeMessage.trim()});setChangeMessage("");toast("추가 요구사항의 영향을 분류하고 새 작업 단계를 시작했습니다.");await load(companyId,selectedGoalId);});}
  const tasks=useMemo(()=>snapshot?.projects.flatMap(p=>p.tasks.map(t=>({...t,projectName:p.project.name})))??[],[snapshot]);
  const firstTask=tasks[0],automationSteps=[{label:"목표 확정",done:snapshot?.goal.status!=="draft"},{label:"프로젝트·마일스톤 구성",done:Boolean(snapshot?.projects.length)},{label:"실행·검토 Agent 배정",done:Boolean(firstTask?.assignments&&firstTask.assignments.length>=2)},{label:"첫 Run 계획 시작",done:Boolean(firstTask?.run)}];
  const delivery=snapshot?.deliveryProcess??null,deliveryStageState=Object.fromEntries(deliveryStages.map(stage=>[stage,[...(delivery?.stages??[])].reverse().find(item=>item.stage===stage)??null])) as Record<DeliveryStage,DeliveryProcessSnapshot["stages"][number]|null>;
  const currentStageRun=delivery?.currentStageInstance.runId?tasks.find(task=>task.runId===delivery.currentStageInstance.runId)?.run??null:null,currentStageFailed=currentStageRun?.status==="FAILED";
  // 프로젝트는 회사 내 목표 하나에만 연결할 수 있으므로, 어떤 목표에든 이미 연결된 프로젝트는 선택지에서 제외한다.
  const linkedIds=new Set(goals.flatMap(g=>g.projectIds??[]));for(const item of snapshot?.projects??[])linkedIds.add(item.project.id);
  const linkable=projects.filter(x=>!linkedIds.has(x.id));
  return <div className="goals-page">
    <PageHeader title="회사 목표" description="회사 목표부터 프로젝트·마일스톤·Task·Run·검증·승인 근거까지 한 흐름으로 추적합니다."/>
    <section className="goal-toolbar card" aria-label="목표 회사 선택"><label>회사<select value={companyId} onChange={e=>void guarded(()=>load(e.target.value,""))}>{companies.map(x=><option key={x.id} value={x.id}>{x.name} · {x.role}</option>)}</select></label><button className="secondary" disabled={busy||!companyId} onClick={()=>void guarded(()=>load())}>새로고침</button><Link className="button-link" to={`/reviews?companyId=${encodeURIComponent(companyId)}${delivery?.ownerReview?`&reviewId=${encodeURIComponent(delivery.ownerReview.id)}`:""}`}>오너 결정 센터</Link><Link className="button-link" to={`/company?companyId=${encodeURIComponent(companyId)}`}>회사 현황</Link><Link className="button-link" to={`/pixel-office?companyId=${encodeURIComponent(companyId)}${selectedGoalId?`&goalId=${encodeURIComponent(selectedGoalId)}`:""}`}>Pixel Office</Link><Link className="button-link" to={`/meetings?companyId=${encodeURIComponent(companyId)}${selectedGoalId?`&goalId=${encodeURIComponent(selectedGoalId)}`:""}`}>목표 회의</Link></section>
    {error&&<p className="error" role="alert">{error}</p>}
    <div className="goal-workspace">
      <aside className="goal-sidebar" aria-label="회사 목표 목록">
        <div className="goal-sidebar-heading"><div><span className="eyebrow">PORTFOLIO</span><h2>목표 {goals.length}</h2></div><span className="goal-count">{goals.filter(x=>x.status==="active").length} 진행</span><span className="mobile-scroll-cue">좌우로 밀어 더 보기 →</span></div>
        <div className="goal-list">{goals.map(goal=><button key={goal.id} className={`goal-list-item ${selectedGoalId===goal.id?"selected":""}`} onClick={()=>selectGoal(goal.id)} aria-pressed={selectedGoalId===goal.id}><span className={`goal-status status-${goal.status}`}>{statusLabel[goal.status]}</span><strong>{safeUserText(goal.title)}</strong><small>{goal.projectCount}개 프로젝트 · {goal.progress}%</small><span className="goal-progress"><i style={{width:`${goal.progress}%`}}/></span>{(goal.blocked>0||goal.pendingApprovals>0)&&<span className="goal-alert">차단 {goal.blocked} · 승인 {goal.pendingApprovals}</span>}</button>)}</div>
        {!goals.length&&<div className="goal-empty"><strong>첫 회사 목표를 만드세요.</strong><span>완료 기준과 예산을 먼저 명확히 정의합니다.</span></div>}
        <details className="goal-create" open={!goals.length}><summary>+ 새 목표 만들기</summary><div className="goal-form"><label>대략적인 설명 (선택, 한두 줄이면 충분)<textarea value={rough} onChange={e=>setRough(e.target.value)} rows={2} placeholder="예: 신규 고객이 첫 프로젝트를 3일 안에 시작할 수 있게 온보딩을 자동화하고 싶음"/></label><button type="button" disabled={draftBusy||!rough.trim()} onClick={()=>void draftFromRough()}>{draftBusy?"AI가 구체화하는 중…":"AI로 구체화"}</button>{draftNote&&<p className="field-help">{draftNote}</p>}<label>목표명 (필수)<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="예: 고객 온보딩 자동화 출시"/></label><label>설명<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={2}/></label><label>완료 기준 (필수, 한 줄에 하나씩)<textarea value={criteria} onChange={e=>setCriteria(e.target.value)} rows={3} placeholder="한 줄에 하나씩 입력"/></label><div className="goal-form-row"><label>예산<input type="number" min={autoSetup?1:0} value={budget} onChange={e=>setBudget(e.target.value)}/></label><label>완료 예정일<input type="date" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label></div><label className="goal-auto-toggle"><input type="checkbox" checked={autoSetup} onChange={e=>setAutoSetup(e.target.checked)}/><span><strong>프로젝트와 Agent를 자동 구성</strong><small>실행팀·마일스톤·Task·담당 Agent를 만들고 첫 Run을 계획 승인 단계까지 진행합니다.</small></span></label>{autoSetup&&<div className="goal-auto-options"><label>저장소 경로<input value={repoPath} onChange={e=>setRepoPath(e.target.value)} placeholder="."/></label><label>작업 허용 경로 (쉼표 구분)<input value={requestedPaths} onChange={e=>setRequestedPaths(e.target.value)} placeholder="src"/></label></div>}<button disabled={busy||!title.trim()||!criteria.trim()||Number(budget)<(autoSetup?1:0)} onClick={()=>void createGoal()}>{busy?"조직과 실행 흐름을 구성하는 중…":autoSetup?"목표 만들고 실행 시작":"목표 초안만 저장"}</button>{!busy&&(!title.trim()||!criteria.trim())&&<p className="field-help">{!title.trim()?"목표명을 입력하세요.":"완료 기준을 한 줄 이상 입력하세요."}</p>}</div></details>
      </aside>
      <main className="goal-detail">
        {!snapshot?<section className="goal-detail-empty"><span aria-hidden="true">◎</span><h2>목표를 선택하거나 생성하세요.</h2><p>선택한 목표의 진행 흐름과 완료 근거가 여기에 표시됩니다.</p></section>:<>
          <header className="goal-detail-header"><div><div className="goal-title-line"><span className={`goal-status status-${snapshot.goal.status}`}>{statusLabel[snapshot.goal.status]}</span><h2>{safeUserText(snapshot.goal.title)}</h2></div><p>{safeUserText(snapshot.goal.description||"목표 설명이 없습니다.","목표 설명 인코딩 확인 필요")}</p><div className="goal-meta"><span>Owner {snapshot.goal.ownerId}</span><span>기한 {snapshot.goal.dueAt?new Date(snapshot.goal.dueAt).toLocaleDateString("ko-KR"):"미정"}</span><span>완료 기준 {snapshot.goal.completionCriteria.length}개</span></div></div><div className="goal-actions">{snapshot.goal.status==="draft"&&<button onClick={()=>void transition("active")}>목표 시작</button>}{snapshot.goal.status==="active"&&<><button className="secondary" onClick={()=>void transition("blocked")}>차단 표시</button><button onClick={()=>void transition("completed")}>완료 검증</button></>}{snapshot.goal.status==="blocked"&&<button onClick={()=>void transition("active")}>진행 재개</button>}</div></header>
          {launchNote&&<p className="goal-launch-note" role="status">{launchNote}</p>}
          <section className="goal-automation" aria-label="자동 실행 진행 상태"><header><div><span className="eyebrow">AUTOMATION</span><strong>목표에서 실행까지</strong></div><span>{automationSteps.filter(x=>x.done).length}/{automationSteps.length} 구성</span></header><ol>{automationSteps.map((step,index)=><li key={step.label} className={step.done?"done":index===automationSteps.findIndex(x=>!x.done)?"current":""}><i aria-hidden="true">{step.done?"✓":index+1}</i><span>{step.label}</span></li>)}</ol>{firstTask?.run?<Link to={`/execution?companyId=${encodeURIComponent(companyId)}&goalId=${encodeURIComponent(selectedGoalId)}&projectId=${encodeURIComponent(firstTask.projectId)}&runId=${encodeURIComponent(firstTask.run.id)}`}>Run {runStatusLabel(firstTask.run.status)} 확인 →</Link>:!snapshot.projects.length&&["draft","active"].includes(snapshot.goal.status)?<button disabled={busy||snapshot.goal.budgetLimit<=0} title={snapshot.goal.budgetLimit<=0?"자동 실행 전에 목표 예산을 1 이상 설정해야 합니다.":undefined} onClick={()=>void provisionExistingGoal()}>{busy?"자동 구성 중…":"기존 목표 자동 구성 시작"}</button>:null}</section>
          <section className="goal-delivery" aria-label="목표 수행 단계">
            <header><div><span className="eyebrow">DELIVERY PROCESS</span><h3>기획부터 운영까지</h3></div>{delivery&&<span className={`delivery-state ${currentStageFailed?"state-blocked":`state-${delivery.process.status}`}`}>{deliveryStageLabel[delivery.process.currentStage]} · {currentStageFailed?"실패 · 재시도 필요":deliveryStatusLabel[delivery.currentStageInstance.status]}</span>}</header>
            {!delivery?<div className="delivery-empty"><strong>단계 프로세스가 아직 연결되지 않았습니다.</strong><span>프로젝트가 없는 기존 목표는 자동 구성을 시작하면 기획 단계가 생성됩니다.</span></div>:<>
              <ol className="delivery-stepper">{deliveryStages.map((stage,index)=>{const item=deliveryStageState[stage],isCurrent=delivery.process.currentStage===stage;return <li key={stage} className={`${item?.status==="approved"?"complete":""} ${isCurrent?"current":""}`}><i>{item?.status==="approved"?"✓":index+1}</i><div><strong>{deliveryStageLabel[stage]}</strong><small>{item?deliveryStatusLabel[item.status]:"이전 단계 승인 후 시작"}</small></div></li>;})}</ol>
              <div className="delivery-current"><div><span className="eyebrow">CURRENT</span><h4>{deliveryStageLabel[delivery.process.currentStage]} · {delivery.currentStageInstance.attempt}차 시도</h4><p>{currentStageFailed?"실패했습니다. 원인을 확인한 뒤 재시도해 주세요.":deliveryStatusLabel[delivery.currentStageInstance.status]}</p></div><div className="delivery-links">{delivery.currentStageInstance.runId&&firstTask&&<Link to={`/execution?companyId=${encodeURIComponent(companyId)}&goalId=${encodeURIComponent(selectedGoalId)}&projectId=${encodeURIComponent(firstTask.projectId)}&runId=${encodeURIComponent(delivery.currentStageInstance.runId)}`}>연결된 Run 보기</Link>}{delivery.currentStageInstance.meetingId&&<Link to={`/meetings?companyId=${encodeURIComponent(companyId)}&goalId=${encodeURIComponent(selectedGoalId)}&meetingId=${encodeURIComponent(delivery.currentStageInstance.meetingId)}`}>검토 회의 보기</Link>}<span>유효 근거 {delivery.artifactSnapshots.filter(item=>item.stageInstanceId===delivery.currentStageInstance.id&&!item.stale).flatMap(item=>item.artifactIds).length}개</span></div></div>
              {currentStageFailed&&delivery.currentStageInstance.runId&&<aside className="owner-review owner-review-held delivery-run-failed" role="alert"><div><span className="eyebrow">RUN FAILED</span><h4>{deliveryStageLabel[delivery.process.currentStage]} Agent 실행에 실패했습니다</h4><p>자동 진행이 멈췄습니다. 실행 상세에서 실패 근거를 확인하거나 이 화면에서 같은 단계부터 재시도할 수 있습니다.</p></div><div className="owner-review-actions"><Link className="button-link secondary" to={`/execution?companyId=${encodeURIComponent(companyId)}&goalId=${encodeURIComponent(selectedGoalId)}&projectId=${encodeURIComponent(firstTask?.projectId??"")}&runId=${encodeURIComponent(delivery.currentStageInstance.runId)}`}>실패 원인 보기</Link><button disabled={busy} onClick={()=>void retryCurrentStageRun()}>이 단계 재시도</button></div></aside>}
              {delivery.currentStageInstance.status==="owner-approval-waiting"&&delivery.ownerReview&&<aside className="owner-review owner-review-callout" aria-label="오너 검토 요청"><div><span className="eyebrow">DECISION REQUIRED</span><h4>{deliveryStageLabel[delivery.process.currentStage]} 검토 패킷이 준비됐습니다</h4><p>{safeUserText(delivery.ownerReview.koreanSummary)}</p></div><dl><div><dt>팀 검토</dt><dd>결정 {delivery.ownerReview.decisions.length} · 위험 {delivery.ownerReview.risks.length} · 미해결 {delivery.ownerReview.openItems.length}</dd></div><div><dt>승인 대상</dt><dd>snapshot {delivery.ownerReview.snapshotHash.slice(0,8)}</dd></div></dl><div className="owner-review-actions"><Link className="button-link" to={`/reviews?companyId=${encodeURIComponent(companyId)}&reviewId=${encodeURIComponent(delivery.ownerReview.id)}`}>검토 패킷 열기</Link></div></aside>}
              {delivery.deployment&&<aside className={`deployment-receipt deployment-${delivery.deployment.status}`} aria-label="배포 기록"><strong>{delivery.deployment.action==="skip"?"배포 안 함 · 사용자 결정":`Firebase ${delivery.deployment.environment==="production"?"Production":"Preview"} · ${delivery.deployment.status}`}</strong><span>{delivery.deployment.targetProjectId??"사용자가 배포하지 않기로 결정"}{delivery.deployment.receipt?.url&&<> · <a href={delivery.deployment.receipt.url} target="_blank" rel="noreferrer">배포 URL</a></>}</span>{delivery.deployment.failure&&<small>{safeUserText(delivery.deployment.failure)}</small>}</aside>}
              {delivery.currentStageInstance.status==="blocked"&&delivery.ownerReview?.status==="on-hold"&&<aside className="owner-review owner-review-held" aria-label="보류된 오너 검토"><div><span className="eyebrow">ON HOLD</span><h4>{deliveryStageLabel[delivery.process.currentStage]} 검토가 보류됐습니다</h4><p>기존 검토 snapshot을 그대로 유지합니다. 준비가 되면 같은 근거에서 검토를 재개할 수 있습니다.</p></div><div className="owner-review-actions"><button disabled={busy} onClick={()=>void transitionDelivery("resume")}>검토 재개</button></div></aside>}
              {delivery.process.status==="completed"&&<aside className="change-request" aria-label="완료 후 추가 요구사항"><div><span className="eyebrow">CHANGE REQUEST</span><h4>완료본은 보존한 채 추가 작업을 요청할 수 있습니다</h4><p>채팅처럼 요구사항을 입력하면 영향 범위를 기획·실행계획·개발·배포 중 하나로 분류하고, 해당 단계의 새 프로세스 버전에서 이어갑니다.</p></div><label>추가 요구사항<textarea rows={3} value={changeMessage} onChange={event=>setChangeMessage(event.target.value)} placeholder="예: 관리자 화면에서 모바일 필터가 잘리지 않도록 수정하고 다시 검증해 줘"/></label><button disabled={busy||!changeMessage.trim()} onClick={()=>void submitChangeRequest()}>{busy?"영향을 분류하는 중…":"추가 요구사항 보내기"}</button></aside>}
            </>}
          </section>
          <section className="goal-kpis" aria-label="목표 핵심 지표"><article><span>전체 진행률</span><strong>{snapshot.metrics.progress}%</strong><small>{snapshot.metrics.done}/{snapshot.metrics.total} Task</small></article><article><span>비용</span><strong>{snapshot.metrics.spent.toFixed(1)}</strong><small>/ 목표 {snapshot.goal.budgetLimit}</small></article><article className={snapshot.metrics.blocked?"danger":""}><span>차단</span><strong>{snapshot.metrics.blocked}</strong><small>즉시 조치</small></article><article className={snapshot.metrics.pendingApprovals?"warning":""}><span>승인 대기</span><strong>{snapshot.metrics.pendingApprovals}</strong><small>결정 필요</small></article><article className={snapshot.metrics.validationFailures?"danger":""}><span>검증 실패</span><strong>{snapshot.metrics.validationFailures}</strong><small>재검증 필요</small></article></section>
          <section className="goal-next-actions"><strong>다음 행동</strong>{snapshot.nextActions.length?snapshot.nextActions.map(x=><span key={x}>{x}</span>):<span>완료 근거가 충족되었습니다.</span>}<div className="goal-link-project"><select value={projectId} onChange={e=>setProjectId(e.target.value)} disabled={!linkable.length}>{linkable.length?linkable.map(x=><option key={x.id} value={x.id}>{x.name}</option>):<option>연결 가능한 프로젝트 없음</option>}</select><button className="secondary" disabled={busy||!projectId||!linkable.length} onClick={()=>void linkProject()}>프로젝트 연결</button></div></section>
          <nav className="goal-view-tabs" aria-label="목표 보기 방식">{(["hierarchy","board","timeline"] as const).map(mode=><button key={mode} className={view===mode?"active":""} aria-pressed={view===mode} onClick={()=>setView(mode)}>{mode==="hierarchy"?"계층":mode==="board"?"보드":"타임라인"}</button>)}</nav>
          {view==="hierarchy"&&<section className="goal-hierarchy">{snapshot.projects.map(item=><article key={item.project.id} className="goal-project"><header><div><span className="eyebrow">PROJECT</span><Link to={`/projects?companyId=${encodeURIComponent(companyId)}&goalId=${encodeURIComponent(selectedGoalId)}&projectId=${encodeURIComponent(item.project.id)}`}>{safeUserText(item.project.name)}</Link></div><span>{item.project.spent}/{item.project.budgetLimit}</span></header>{item.milestones.map(m=><div key={m.id} className="goal-milestone"><div className="goal-milestone-title"><strong>{safeUserText(m.title)}</strong><span>{statusLabel[m.status]??m.status} · {m.progress.done}/{m.progress.total}</span></div>{item.tasks.filter(t=>t.milestoneId===m.id).map(t=><TaskRow key={t.id} task={t} companyId={companyId} goalId={selectedGoalId}/>)}</div>)}{item.tasks.filter(t=>!t.milestoneId).map(t=><TaskRow key={t.id} task={t} companyId={companyId} goalId={selectedGoalId}/>)}</article>)}{!snapshot.projects.length&&<div className="goal-detail-empty compact"><h3>연결된 프로젝트가 없습니다.</h3><p>위의 프로젝트 연결 메뉴에서 목표 수행 범위를 지정하세요.</p></div>}</section>}
          {view==="board"&&<section className="goal-board">{["backlog","ready","in-progress","review","blocked","done"].map(status=><div className="goal-board-column" key={status}><header><strong>{statusLabel[status]}</strong><span>{tasks.filter(t=>t.status===status).length}</span></header>{tasks.filter(t=>t.status===status).map(t=><article key={t.id}><small>{safeUserText(t.projectName)}</small><strong>{safeUserText(t.title)}</strong>{t.run&&<Link to={`/execution?companyId=${encodeURIComponent(companyId)}&goalId=${encodeURIComponent(selectedGoalId)}&projectId=${encodeURIComponent(t.projectId)}&runId=${encodeURIComponent(t.run.id)}`}>Run {runStatusLabel(t.run.status)}</Link>}<span>{t.spent}/{t.budgetLimit}</span></article>)}</div>)}</section>}
          {view==="timeline"&&<section className="goal-timeline">{snapshot.timeline.map((event,index)=><article key={`${event.createdAt}-${index}`}><time>{new Date(event.createdAt).toLocaleString("ko-KR")}</time><i aria-hidden="true"/><div><strong title={event.type}>{timelineLabel(event.type)}</strong>{event.projectId&&<Link to={`/projects?companyId=${encodeURIComponent(companyId)}&goalId=${encodeURIComponent(selectedGoalId)}&projectId=${encodeURIComponent(event.projectId)}`}>프로젝트 근거 보기</Link>}</div></article>)}</section>}
        </>}
      </main>
    </div>
  </div>;
}

function TaskRow({task,companyId,goalId}:{task:Task;companyId:string;goalId:string}){return <div className="goal-task"><span className={`task-state task-${task.status}`}>{statusLabel[task.status]??task.status}</span><strong>{safeUserText(task.title)}</strong><span className="goal-evidence">결과물 {task.artifacts?.length??0} · 승인 {task.approvals?.length??0}{task.stale?.length?` · stale ${task.stale.length}`:""}</span>{task.run?<Link to={`/execution?companyId=${encodeURIComponent(companyId)}&goalId=${encodeURIComponent(goalId)}&projectId=${encodeURIComponent(task.projectId)}&runId=${encodeURIComponent(task.run.id)}`}>Run {runStatusLabel(task.run.status)} →</Link>:<span className="muted">Run 미연결</span>}</div>}
