import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import PageHeader from "../components/PageHeader.tsx";
import { useSession } from "../auth/SessionContext.tsx";
import { apiGet, apiPost, readSse } from "../api.ts";
import { useToast } from "../components/ToastContext.tsx";
import { uuid } from "../format.ts";

type MeetingStatus="scheduled"|"live"|"decision-pending"|"ended"|"cancelled";
type MessageKind="question"|"opinion"|"instruction"|"decision"|"agent"|"system";
interface Meeting{id:string;companyId:string;goalId:string|null;projectId:string|null;runId:string|null;title:string;purpose:string;hostId:string;participantIds:string[];agenda:string[];status:MeetingStatus;scheduledAt:string|null;startedAt:string|null;endedAt:string|null;paused:boolean;messageCount:number;decisionCount:number;canParticipate:boolean}
interface Message{id:string;speakerId:string;kind:MessageKind;targetType:"all"|"member"|"agenda"|"goal-task";targetId:string|null;content:string;evidence:string[];followUp:null|{title:string;assigneeId:string|null;dueAt:string|null;completionCriteria:string[];budgetLimit:number};createdAt:string}
interface Summary{status:"draft"|"confirmed";paragraph:string;agendaSummaries:Array<{agenda:string;summary:string}>;decisions:string[];openItems:string[];risks:string[];followUps:Array<{title:string;assigneeId:string|null}>;createdTaskIds:string[];confirmedBy:string|null}
interface AgentTurn{id:string;round:number;participantId:string;status:"pending"|"running"|"completed"|"failed"|"cancelled"|"execution-uncertain";dispatchState:string;tokens:number;cost:number;error:string|null;promptHash:string}
interface Snapshot{meeting:Meeting;messages:Message[];summary:Summary|null;members:Array<{principalId:string;role:string;kind:string}>;context:{goal:{id:string;title:string}|null;project:{id:string;name:string}|null;run:{id:string;status:string}|null};agentTurns?:AgentTurn[];semanticSummary?:{status:"model"|"canonical-fallback";summary:Record<string,unknown>;warnings:string[]}|null}
interface Center{goals:Array<{id:string;title:string}>;portfolio:{projects:Array<{project:{id:string;name:string};tasks:Array<{runId:string|null;run?:{id:string;status:string}|null}>}>};pixel:{agents:Array<{principal_id:string}>}}
interface Company{id:string;name:string;role:string;status:string}
const statusLabel:Record<MeetingStatus,string>={scheduled:"예정",live:"진행 중","decision-pending":"결정 대기",ended:"종료",cancelled:"취소"};
const kindLabel:Record<MessageKind,string>={question:"질문",opinion:"의견",instruction:"지시",decision:"결정",agent:"Agent",system:"시스템"};

export default function MeetingsPage(){
 const {actorId}=useSession(),toast=useToast(),[params,setParams]=useSearchParams(),[companyId,setCompanyId]=useState(()=>params.get("companyId")??localStorage.getItem("agent-company-os.lastCompany")??""),[meetingId,setMeetingId]=useState(()=>params.get("meetingId")??"");
 const mountedRef=useRef(true);
 const [companies,setCompanies]=useState<Company[]>([]),[meetings,setMeetings]=useState<Meeting[]>([]),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[center,setCenter]=useState<Center|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[unread,setUnread]=useState(0),[connected,setConnected]=useState(false),[showEvidence,setShowEvidence]=useState(false);
 const [title,setTitle]=useState(""),[purpose,setPurpose]=useState(""),[agenda,setAgenda]=useState(""),[goalId,setGoalId]=useState(()=>params.get("goalId")??""),[projectId,setProjectId]=useState(()=>params.get("projectId")??""),[participants,setParticipants]=useState("");
 const [kind,setKind]=useState<MessageKind>("opinion"),[targetType,setTargetType]=useState<Message["targetType"]>("all"),[targetId,setTargetId]=useState(""),[content,setContent]=useState(""),[evidence,setEvidence]=useState(""),[followUpTitle,setFollowUpTitle]=useState("");
 const transcriptRef=useRef<HTMLDivElement|null>(null),atBottomRef=useRef(true);
 async function guarded(work:()=>Promise<void>){setBusy(true);setError(null);try{await work();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 const load=useCallback(async(id=companyId,selected=meetingId)=>{const [items,nextCenter]=await Promise.all([apiGet<Meeting[]>(`/api/companies/${encodeURIComponent(id)}/meetings?actor=${encodeURIComponent(actorId)}`),apiGet<Center>(`/api/companies/${encodeURIComponent(id)}?actor=${encodeURIComponent(actorId)}`)]);if(!mountedRef.current)return;setMeetings(items);setCenter(nextCenter);setCompanyId(id);localStorage.setItem("agent-company-os.lastCompany",id);const nextId=items.some(x=>x.id===selected)?selected:items.find(x=>x.status==="live")?.id??items[0]?.id??"";setMeetingId(nextId);if(nextId){const nextSnapshot=await apiGet<Snapshot>(`/api/companies/${encodeURIComponent(id)}/meetings/${encodeURIComponent(nextId)}?actor=${encodeURIComponent(actorId)}`);if(!mountedRef.current)return;setSnapshot(nextSnapshot);}else setSnapshot(null);if(!mountedRef.current)return;const query=new URLSearchParams({companyId:id});if(nextId)query.set("meetingId",nextId);setParams(query,{replace:true});},[actorId,companyId,meetingId,setParams]);
 useEffect(()=>{mountedRef.current=true;return()=>{mountedRef.current=false;};},[]);
 useEffect(()=>{void apiGet<Company[]>(`/api/companies?actor=${encodeURIComponent(actorId)}`).then(items=>{const active=items.filter(x=>x.status==="active");setCompanies(active);const id=active.some(x=>x.id===companyId)?companyId:active[0]?.id??"";if(id)void guarded(()=>load(id,meetingId));}).catch(e=>setError(e instanceof Error?e.message:String(e)));},[]);
 useEffect(()=>{if(!companyId||!meetingId)return;const controller=new AbortController();void readSse(`/api/events?companyId=${encodeURIComponent(companyId)}`,controller.signal,event=>{const data=event.data as {payload?:{meetingId?:string}};if(data?.payload?.meetingId!==meetingId)return;if(atBottomRef.current)void load(companyId,meetingId);else setUnread(x=>x+1);},()=>setConnected(true)).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:String(e));});return()=>controller.abort();},[companyId,meetingId]);
 function selectMeeting(id:string){setUnread(0);setShowEvidence(false);setMeetingId(id);void guarded(()=>load(companyId,id));}
 function createMeeting(){return guarded(async()=>{const id=uuid();await apiPost(`/api/companies/${encodeURIComponent(companyId)}/meetings`,{actorId,id,goalId:goalId||null,projectId:projectId||null,runId:null,title,purpose,hostId:actorId,participantIds:participants.split(",").map(x=>x.trim()).filter(Boolean),agenda:agenda.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),scheduledAt:null});toast("회의를 생성했습니다.");setTitle("");setPurpose("");setAgenda("");await load(companyId,id);});}
 function transition(status:MeetingStatus){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/meetings/${encodeURIComponent(meetingId)}/actions/transition`,{actorId,status});toast(`회의 상태를 ${statusLabel[status]}으로 변경했습니다.`);await load(companyId,meetingId);});}
 function pause(paused:boolean){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/meetings/${encodeURIComponent(meetingId)}/actions/${paused?"pause":"resume"}`,{actorId});await load(companyId,meetingId);});}
 function send(){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/meetings/${encodeURIComponent(meetingId)}/messages`,{actorId,id:uuid(),kind,targetType,targetId:targetId||null,content,evidence:evidence.split(",").map(x=>x.trim()).filter(Boolean),followUp:followUpTitle?{title:followUpTitle,assigneeId:null,dueAt:null,completionCriteria:["회의 결정 이행"],budgetLimit:0}:null});setContent("");setFollowUpTitle("");await load(companyId,meetingId);requestAnimationFrame(()=>transcriptRef.current?.scrollTo({top:transcriptRef.current.scrollHeight}));});}
 function confirm(){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/meetings/${encodeURIComponent(meetingId)}/summary/confirm`,{actorId});toast("회의 요약과 후속 Task를 확정했습니다.");await load(companyId,meetingId);});}
 function initializeAgents(){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/meetings/${encodeURIComponent(meetingId)}/agent-turns`,{actorId,limits:{maxTokens:6000,maxCost:10,maxRounds:3,deadline:new Date(Date.now()+15*60_000).toISOString(),maxTokensPerTurn:1000,maxCostPerTurn:2,maxRetries:1,leaseMs:60_000,maxOutputBytes:4000}});toast("Agent 회의 turn과 Backend snapshot을 생성했습니다.");await load(companyId,meetingId);});}
 function runNextAgent(){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/meetings/${encodeURIComponent(meetingId)}/agent-turns/run-next`,{actorId});await load(companyId,meetingId);});}
 function runAgentProtocol(){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/meetings/${encodeURIComponent(meetingId)}/agent-turns/protocol`,{actorId});await load(companyId,meetingId);});}
 function enqueueRound(round:number){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/meetings/${encodeURIComponent(meetingId)}/agent-turns/round`,{actorId,round});await load(companyId,meetingId);});}
 function generateSemanticSummary(){return guarded(async()=>{await apiPost(`/api/companies/${encodeURIComponent(companyId)}/meetings/${encodeURIComponent(meetingId)}/summary/semantic`,{actorId});await load(companyId,meetingId);});}
 const selected=snapshot?.meeting,projectOptions=center?.portfolio.projects.map(x=>x.project)??[],members=snapshot?.members??[],agentTurns=snapshot?.agentTurns??[],targetOptions=targetType==="member"?members.map(x=>({id:x.principalId,label:x.principalId})):targetType==="agenda"?(selected?.agenda??[]).map(x=>({id:x,label:x})):[];
 return <div className="meetings-page"><PageHeader title="회의" description="진행 중 대화를 실시간으로 확인하고, 감사 가능한 질문·의견·지시·결정으로 개입합니다."/>
  <section className="meeting-toolbar card"><label>회사<select value={companyId} onChange={e=>void guarded(()=>load(e.target.value,""))}>{companies.map(x=><option key={x.id} value={x.id}>{x.name} · {x.role}</option>)}</select></label><button className="secondary" disabled={busy} onClick={()=>void guarded(()=>load())}>새로고침</button><Link className="button-link" to={`/company?companyId=${encodeURIComponent(companyId)}`}>회사 현황</Link><Link className="button-link" to={`/goals?companyId=${encodeURIComponent(companyId)}${selected?.goalId?`&goalId=${encodeURIComponent(selected.goalId)}`:""}`}>목표 현황</Link><span className="meeting-live-state"><i className={`status-dot ${connected?"status-good":"status-warning"}`}/>{connected?"실시간 연결":"연결 대기"}</span></section>{error&&<p className="error" role="alert">{error}</p>}
  <div className="meeting-shell"><aside className="meeting-list-panel"><header><div><span className="eyebrow">MEETINGS</span><h2>회의 {meetings.length}</h2></div><span>{meetings.filter(x=>x.status==="live").length} 진행</span><span className="mobile-scroll-cue">좌우로 밀어 더 보기 →</span></header><div className="meeting-list">{meetings.map(item=><button key={item.id} className={meetingId===item.id?"selected":""} onClick={()=>selectMeeting(item.id)}><span className={`meeting-status status-${item.status}`}>{statusLabel[item.status]}</span><strong>{item.title}</strong><small>{item.hostId} · 발언 {item.messageCount} · 결정 {item.decisionCount}</small><em>{item.purpose}</em></button>)}</div>{!meetings.length&&<p className="meeting-empty">등록된 회의가 없습니다.</p>}<details className="meeting-create"><summary>+ 새 회의 만들기</summary><div><label>회의 제목<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>목적<textarea rows={2} value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><label>안건<textarea rows={3} value={agenda} onChange={e=>setAgenda(e.target.value)} placeholder="한 줄에 하나"/></label><label>연결 목표<select value={goalId} onChange={e=>setGoalId(e.target.value)}><option value="">선택 안 함</option>{center?.goals.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label>연결 프로젝트<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">선택 안 함</option>{projectOptions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>참석자 ID<input value={participants} onChange={e=>setParticipants(e.target.value)} placeholder="쉼표로 구분"/></label><button disabled={busy||!title.trim()||!purpose.trim()||!agenda.trim()} onClick={()=>void createMeeting()}>회의 생성</button></div></details></aside>
   <main className="meeting-room">{!snapshot?<section className="meeting-room-empty"><span>◌</span><h2>회의를 선택하세요.</h2><p>실시간 발언과 결정 근거가 표시됩니다.</p></section>:<><header className="meeting-room-header"><div><div><span className={`meeting-status status-${selected!.status}`}>{statusLabel[selected!.status]}</span><h2>{selected!.title}</h2>{selected!.paused&&<b>일시중지</b>}</div><p>{selected!.purpose}</p><nav>{snapshot.context.goal&&<Link to={`/goals?companyId=${encodeURIComponent(companyId)}&goalId=${encodeURIComponent(snapshot.context.goal.id)}`}>목표 · {snapshot.context.goal.title}</Link>}{snapshot.context.project&&<Link to={`/projects?companyId=${encodeURIComponent(companyId)}&projectId=${encodeURIComponent(snapshot.context.project.id)}${selected!.goalId?`&goalId=${encodeURIComponent(selected!.goalId)}`:""}`}>프로젝트 · {snapshot.context.project.name}</Link>}{snapshot.context.run&&<Link to={`/execution?companyId=${encodeURIComponent(companyId)}&runId=${encodeURIComponent(snapshot.context.run.id)}&projectId=${encodeURIComponent(selected!.projectId??"")}`}>Run · {snapshot.context.run.status}</Link>}</nav></div><div className="meeting-controls">{selected!.status==="scheduled"&&<><button onClick={()=>void transition("live")}>회의 시작</button><button className="secondary" onClick={()=>void transition("cancelled")}>취소</button></>}{selected!.status==="live"&&<><button className="secondary" onClick={()=>void pause(!selected!.paused)}>{selected!.paused?"재개":"일시중지"}</button><button className="secondary" onClick={()=>void transition("decision-pending")}>결정 대기</button><button onClick={()=>void transition("ended")}>회의 종료</button></>}{selected!.status==="decision-pending"&&<><button onClick={()=>void transition("live")}>논의 재개</button><button className="secondary" onClick={()=>void transition("ended")}>회의 종료</button></>}</div></header>
    {["ended","cancelled"].includes(selected!.status)&&<section className="meeting-owner-brief" aria-labelledby="owner-review-heading"><header><div><span className="eyebrow">오너 검토</span><h3 id="owner-review-heading">회의 결과 요약</h3></div><span className={`meeting-status status-${selected!.status}`}>{statusLabel[selected!.status]}</span></header><p>발언 {snapshot.messages.length}건을 검토했습니다. 명시적 결정 {snapshot.summary?.decisions.length??0}건, 위험·이견 {snapshot.summary?.risks.length??0}건, 미해결 질문 {snapshot.summary?.openItems.length??0}건입니다.</p>{snapshot.summary?.decisions.length?<div className="owner-decision-list">{snapshot.summary.decisions.map(item=><span key={item}>{item}</span>)}</div>:<p className="owner-brief-warning">명시적으로 기록된 결정이 없습니다. 승인 전에 회의 요약과 단계 검토 기록을 확인하세요.</p>}<button className="secondary" aria-expanded={showEvidence} onClick={()=>setShowEvidence(value=>!value)}>{showEvidence?"원문·기술 근거 접기":"원문·기술 근거 보기"}</button></section>}
    {(selected!.status==="live"||selected!.status==="decision-pending"||showEvidence)&&<div className="meeting-three-column"><aside className="meeting-participants"><h3>참석자·상태</h3>{members.filter(x=>selected!.participantIds.includes(x.principalId)).map(member=><article key={member.principalId}><span>{member.principalId.slice(0,2).toUpperCase()}</span><div><strong>{member.principalId}</strong><small>{member.role} · {member.kind}</small></div><i className="status-dot status-good"/></article>)}<h3>안건</h3><ol>{selected!.agenda.map((item,index)=><li key={item}><span>{index+1}</span>{item}</li>)}</ol><h3>Agent turns</h3>{agentTurns.length===0?<button disabled={busy||selected!.status!=="live"||selected!.paused} onClick={()=>void initializeAgents()}>Agent 회의 준비</button>:<><button disabled={busy||selected!.status!=="live"||selected!.paused||!agentTurns.some(x=>x.status==="pending"||x.dispatchState==="result-stored")} onClick={()=>void runNextAgent()}>다음 Agent 발언</button><button disabled={busy||selected!.status!=="live"||selected!.paused} onClick={()=>void runAgentProtocol()}>3라운드 제한 실행</button>{[2,3].map(round=><button className="secondary" key={round} disabled={busy||agentTurns.some(x=>x.round===round)} onClick={()=>void enqueueRound(round)}>{round}라운드 생성</button>)}{agentTurns.map(turn=><article key={turn.id}><span>{turn.round}</span><div><strong>{turn.participantId}</strong><small>{turn.status} · {turn.tokens} tokens</small>{turn.error&&<small>{turn.error}</small>}</div></article>)}</>}</aside>
     <section className="meeting-transcript"><div className="meeting-transcript-head"><h3>실시간 회의 내용</h3>{unread>0&&<button onClick={()=>{setUnread(0);void load(companyId,meetingId);}}>새 발언 {unread}</button>}</div><div className="meeting-message-stream" ref={transcriptRef} onScroll={e=>{const el=e.currentTarget;atBottomRef.current=el.scrollHeight-el.scrollTop-el.clientHeight<40;if(atBottomRef.current)setUnread(0);}}>{snapshot.messages.map(message=><article key={message.id} className={`message-${message.kind}`}><header><span>{message.speakerId.slice(0,2).toUpperCase()}</span><strong>{message.speakerId}</strong><b>{kindLabel[message.kind]}</b><time>{new Date(message.createdAt).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})}</time></header><p>{message.content}</p>{message.evidence.length>0&&<footer>{message.evidence.map(x=><code key={x}>{x}</code>)}</footer>}</article>)}{!snapshot.messages.length&&<div className="meeting-empty-transcript">아직 발언이 없습니다.</div>}</div><div className="meeting-composer"><div><label>개입 방식<select value={kind} onChange={e=>setKind(e.target.value as MessageKind)}><option value="question">질문</option><option value="opinion">의견</option><option value="instruction">지시</option><option value="decision">결정</option></select></label><label>대상<select value={targetType} onChange={e=>{setTargetType(e.target.value as Message["targetType"]);setTargetId("");}}><option value="all">전체 참석자</option><option value="member">특정 직원</option><option value="agenda">특정 안건</option><option value="goal-task">현재 목표·Task</option></select></label>{targetOptions.length>0&&<label>세부 대상<select value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">선택</option>{targetOptions.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>}</div><textarea aria-label="회의 메시지" rows={3} value={content} onChange={e=>setContent(e.target.value)} placeholder="질문, 의견 또는 결정을 입력하세요."/><div><input aria-label="연결 근거" value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="근거 ID, 쉼표 구분"/><input aria-label="후속 Task" value={followUpTitle} onChange={e=>setFollowUpTitle(e.target.value)} placeholder="후속 Task 제목(선택)"/><button disabled={busy||selected!.status!=="live"||selected!.paused||!content.trim()} onClick={()=>void send()}>전송</button></div></div></section>
     <aside className="meeting-decisions"><h3>결정·근거</h3>{snapshot.messages.filter(x=>x.kind==="decision").map(x=><article key={x.id}><strong>{x.content}</strong><small>{x.speakerId}</small>{x.evidence.map(e=><code key={e}>{e}</code>)}</article>)}{!snapshot.messages.some(x=>x.kind==="decision")&&<p>확정된 결정이 없습니다.</p>}<h3>후속 Task</h3>{snapshot.messages.filter(x=>x.followUp).map(x=><article key={x.id}><strong>{x.followUp!.title}</strong><small>요약 확정 후 생성</small></article>)}</aside></div>}
    {snapshot.summary&&(selected!.status==="live"||selected!.status==="decision-pending"||showEvidence)&&<section className="meeting-summary"><header><div><span className="eyebrow">회의 요약</span><h3>회의 요약 · {snapshot.summary.status==="draft"?"초안":"확정"}</h3></div>{snapshot.summary.status==="draft"&&<button disabled={busy} onClick={()=>void confirm()}>요약·후속 Task 확정</button>}</header><p>{snapshot.summary.paragraph}</p><div><article><strong>결정</strong>{snapshot.summary.decisions.map(x=><span key={x}>{x}</span>)}</article><article><strong>미결</strong>{snapshot.summary.openItems.map(x=><span key={x}>{x}</span>)}</article><article><strong>위험·이견</strong>{snapshot.summary.risks.map(x=><span key={x}>{x}</span>)}</article><article><strong>생성 Task</strong>{snapshot.summary.createdTaskIds.map(x=><Link key={x} to={`/projects?companyId=${encodeURIComponent(companyId)}&projectId=${encodeURIComponent(selected!.projectId??"")}`}>{x}</Link>)}</article></div></section>}
   {snapshot.summary&&selected!.status==="ended"&&showEvidence&&<section className="meeting-summary"><header><div><span className="eyebrow">근거 의미 계층</span><h3>의미 요약 · {snapshot.semanticSummary?.status??"미생성"}</h3></div><button className="secondary" disabled={busy} onClick={()=>void generateSemanticSummary()}>근거 기반 의미 요약</button></header>{snapshot.semanticSummary?<><pre>{JSON.stringify(snapshot.semanticSummary.summary,null,2)}</pre>{snapshot.semanticSummary.warnings.map(x=><code key={x}>{x}</code>)}</>:<p>결정론적 요약은 유지되며 선택적 모델 실패 시 그대로 사용됩니다.</p>}</section>}
   </>}</main></div></div>;
}
