import type {DatabaseSync} from "node:sqlite";
import type {CompanyOperations,CompanyRole} from "../../company-ops/src/index.js";
import type {OperationalStore} from "../../operations/src/index.js";

export type CharacterStyle="executive"|"manager"|"developer"|"reviewer"|"specialist"|"general";
export interface OfficeFloor{floor:number;name:string;unlockLevel:number;zones:string[]}
const floors:OfficeFloor[]=[{floor:1,name:"Delivery Floor",unlockLevel:1,zones:["planning","development","qa","approval"]},{floor:2,name:"Collaboration Floor",unlockLevel:4,zones:["meeting","project-a","project-b"]},{floor:3,name:"Specialist Floor",unlockLevel:5,zones:["security-review","performance-review","accessibility-review"]},{floor:4,name:"Executive Floor",unlockLevel:8,zones:["briefing","portfolio","incident-command"]},{floor:5,name:"Expansion Floor",unlockLevel:10,zones:["multi-company","simulation","archive"]}];
const styleFor=(role:string,specialty:string|null):CharacterStyle=>specialty?"specialist":role==="owner"||role==="executive"?"executive":role==="department-manager"?"manager":role.includes("review")?"reviewer":role==="member"?"developer":"general";
export class OfficeManagement{
 constructor(private readonly db:DatabaseSync,private readonly companies:CompanyOperations,private readonly operations:OperationalStore){this.db.exec(`CREATE TABLE IF NOT EXISTS office_staff_v10(company_id TEXT NOT NULL,principal_id TEXT NOT NULL,specialty TEXT,appearance TEXT NOT NULL,hired_at TEXT NOT NULL,PRIMARY KEY(company_id,principal_id));CREATE TABLE IF NOT EXISTS office_placements_v10(company_id TEXT NOT NULL,principal_id TEXT NOT NULL,floor INTEGER NOT NULL,zone TEXT NOT NULL,desk INTEGER NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(company_id,principal_id));CREATE TABLE IF NOT EXISTS office_decorations_v10(id TEXT PRIMARY KEY,company_id TEXT NOT NULL,floor INTEGER NOT NULL,zone TEXT NOT NULL,kind TEXT NOT NULL,x INTEGER NOT NULL,y INTEGER NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS office_themes_v11(company_id TEXT PRIMARY KEY,theme TEXT NOT NULL,updated_by TEXT NOT NULL,updated_at TEXT NOT NULL);`);}
 hire(companyId:string,actorId:string,input:{principalId:string;departmentId:string|null;role:CompanyRole;specialty?:string|null;appearance?:Record<string,string>}):unknown{this.companies.require(companyId,actorId,"manage-policy");if(!input.principalId.trim())throw new Error("principalId is required");this.companies.addMember(companyId,actorId,input.principalId,input.role,input.departmentId);const specialty=input.specialty?.trim()||null,appearance=input.appearance??{palette:styleFor(input.role,specialty)};this.db.prepare("INSERT INTO office_staff_v10 VALUES(?,?,?,?,?)").run(companyId,input.principalId,specialty,JSON.stringify(appearance),new Date().toISOString());this.place(companyId,actorId,{principalId:input.principalId,floor:specialty?3:1,zone:specialty?`${specialty}-review`:"development",desk:this.count(companyId)});this.emit(companyId,"OFFICE_STAFF_HIRED",{actorId,principalId:input.principalId,specialty});return this.snapshot(companyId,actorId);}
 place(companyId:string,actorId:string,input:{principalId:string;floor:number;zone:string;desk:number}):unknown{this.companies.require(companyId,actorId,"manage-policy");if(!floors.some(x=>x.floor===input.floor&&x.zones.includes(input.zone)))throw new Error("Unknown or locked office zone");if(!this.db.prepare("SELECT 1 FROM company_members_v4 WHERE company_id=? AND principal_id=?").get(companyId,input.principalId))throw new Error("Company staff missing");this.db.prepare("INSERT INTO office_placements_v10 VALUES(?,?,?,?,?,?) ON CONFLICT(company_id,principal_id) DO UPDATE SET floor=excluded.floor,zone=excluded.zone,desk=excluded.desk,updated_at=excluded.updated_at").run(companyId,input.principalId,input.floor,input.zone,input.desk,new Date().toISOString());this.emit(companyId,"OFFICE_STAFF_PLACED",{actorId,...input});return this.snapshot(companyId,actorId);}
 decorate(companyId:string,actorId:string,input:{floor:number;zone:string;kind:string;x:number;y:number}):unknown{this.companies.require(companyId,actorId,"manage-policy");if(!floors.some(x=>x.floor===input.floor&&x.zones.includes(input.zone)))throw new Error("Unknown office zone");const id=crypto.randomUUID();this.db.prepare("INSERT INTO office_decorations_v10 VALUES(?,?,?,?,?,?,?,?)").run(id,companyId,input.floor,input.zone,input.kind,input.x,input.y,new Date().toISOString());this.emit(companyId,"OFFICE_DECORATION_PLACED",{actorId,id,...input});return this.snapshot(companyId,actorId);}
 updateDecoration(companyId:string,actorId:string,input:{id:string;floor:number;zone:string;x:number;y:number}):unknown{this.companies.require(companyId,actorId,"manage-policy");if(!floors.some(x=>x.floor===input.floor&&x.zones.includes(input.zone)))throw new Error("Unknown office zone");if(this.db.prepare("UPDATE office_decorations_v10 SET floor=?,zone=?,x=?,y=? WHERE id=? AND company_id=?").run(input.floor,input.zone,input.x,input.y,input.id,companyId).changes!==1)throw new Error("Decoration missing");this.emit(companyId,"OFFICE_DECORATION_MOVED",{actorId,...input});return this.snapshot(companyId,actorId);}
 removeDecoration(companyId:string,actorId:string,id:string):unknown{this.companies.require(companyId,actorId,"manage-policy");if(this.db.prepare("DELETE FROM office_decorations_v10 WHERE id=? AND company_id=?").run(id,companyId).changes!==1)throw new Error("Decoration missing");this.emit(companyId,"OFFICE_DECORATION_REMOVED",{actorId,id});return this.snapshot(companyId,actorId);}
 setTheme(companyId:string,actorId:string,theme:string):unknown{this.companies.require(companyId,actorId,"manage-policy");if(!["classic","night","forest","high-contrast"].includes(theme))throw new Error("Unsupported office theme");this.db.prepare("INSERT INTO office_themes_v11 VALUES(?,?,?,?) ON CONFLICT(company_id) DO UPDATE SET theme=excluded.theme,updated_by=excluded.updated_by,updated_at=excluded.updated_at").run(companyId,theme,actorId,new Date().toISOString());this.emit(companyId,"OFFICE_THEME_CHANGED",{actorId,theme});return this.visualSnapshot(companyId,actorId);}
 replay(companyId:string,actorId:string,after:number,limit:number):unknown{this.companies.require(companyId,actorId,"view");const bounded=Math.min(500,Math.max(1,limit)),events=this.operations.events(companyId,after,bounded);return{companyId,after,limit:bounded,events,nextAfter:events.at(-1)?.cursor??after,hasMore:events.length===bounded};}
 visualSnapshot(companyId:string,actorId:string):unknown{const base=this.snapshot(companyId,actorId) as Record<string,unknown>,row=this.db.prepare("SELECT theme FROM office_themes_v11 WHERE company_id=?").get(companyId) as {theme:string}|undefined;return{...base,theme:row?.theme??"classic",availableThemes:["classic","night","forest","high-contrast"]};}
 snapshot(companyId:string,actorId:string):unknown{this.companies.require(companyId,actorId,"view");const members=this.db.prepare("SELECT principal_id principalId,department_id departmentId,role,kind FROM company_members_v4 WHERE company_id=? ORDER BY principal_id").all(companyId) as Array<{principalId:string;departmentId:string|null;role:string;kind:"human"|"agent"}>,profiles=this.db.prepare("SELECT principal_id principalId,specialty,appearance FROM office_staff_v10 WHERE company_id=?").all(companyId) as Array<{principalId:string;specialty:string|null;appearance:string}>,placements=this.db.prepare("SELECT principal_id principalId,floor,zone,desk FROM office_placements_v10 WHERE company_id=?").all(companyId) as Array<{principalId:string;floor:number;zone:string;desk:number}>,projects=this.db.prepare("SELECT project_id projectId,department_id departmentId,priority FROM company_projects_v4 WHERE company_id=? ORDER BY priority DESC,project_id").all(companyId),staff=members.map((x,index)=>{const p=profiles.find(y=>y.principalId===x.principalId),placement=placements.find(y=>y.principalId===x.principalId)??{principalId:x.principalId,floor:1,zone:x.role==="owner"||x.role==="executive"?"planning":"development",desk:index};return{...x,specialty:p?.specialty??null,appearance:p?JSON.parse(p.appearance):{palette:styleFor(x.role,null)},characterStyle:styleFor(x.role,p?.specialty??null),placement};}),decorations=this.db.prepare("SELECT id,floor,zone,kind,x,y FROM office_decorations_v10 WHERE company_id=? ORDER BY floor,zone,id").all(companyId);return{companyId,floors,staff,decorations,projects,capacity:{staff:staff.length,target:30,utilization:staff.length/30},accessibility:{keyboardNavigation:true,reducedMotion:true,highContrast:true,screenReaderSummary:true}};}
 private count(companyId:string):number{return Number((this.db.prepare("SELECT COUNT(*) n FROM company_members_v4 WHERE company_id=?").get(companyId) as {n:number}).n)}
 private emit(companyId:string,type:string,payload:Record<string,unknown>):void{this.operations.emit({tenantId:companyId,aggregateType:"office",aggregateId:companyId,type,payload});}
}
